const collectionPhrasesEN = {
    // Amanecer
    dawnPhrasesEN : [
        "The morning whispers promises to the wind.",
        "The dawn awakens with a sigh of light.",
        "A golden balm caresses the horizon.",
        "The sky dresses in soft watercolors.",
        "A murmur of hope travels through the air.",
        "Silence gives way to the timid light.",
        "The world stretches and yawns in colors.",
        "The aurora teaches magic without words.",
        "Everything is reborn in that sacred moment.",
        "A golden heartbeat starts the day.",
        "The early breeze brings new beginnings.",
        "A poem of light is born in the sky.",
        "The gloom surrenders to the golden light.",
        "A warm whisper awakens the earth.",
        "The horizon lights up in calmness.",
        "A silent melody rules the dawn.",
        "The sky breathes in pastel tones.",
        "Life peeks out from behind the veil of night.",
        "The sun raises its first timid greeting.",
        "Hope filters through each ray.",
        "The world awakens in golden murmurs.",
        "An eternal moment bathed in light.",
        "The aurora paints its first lines.",
        "An embrace of light covers the morning.",
        "The day begins with a warm sigh.",
        "A canvas of calm unfolds.",
        "Clarity hints itself in the fresh air.",
        "A silent song announces the day.",
        "The essence of dawn fills the soul.",
        "The sky reveals its peaceful face.",
        "A golden murmur rocks the horizon.",
        "The promise of a new chapter vibrates.",
        "The air vibrates with tones of hope.",
        "Whispers of light caress the gloom.",
        "The aurora awakens with softness.",
        "A golden halo envelops the earth.",
        "Every morning, a new possibility is reborn.",
        "The silence of dawn whispers life.",
        "A caress of sun breaks through slowly.",
        "The night dissolves with sweetness.",
        "A soft glimmer kisses the sky.",
        "The aurora embraces the nocturnal silence.",
        "A verse of light is recited by the horizon.",
        "The freshness of dawn fills the lungs.",
        "A new air carries the promise.",
        "The calm before the day's heartbeat.",
        "A breath of light travels without hurry.",
        "The atmosphere vibrates in soft tones.",
        "A nascent sky offers serenity.",
        "The world awakens in a whisper.",
        "A caress of dawn penetrates the soul.",
        "The space fills with delicate light.",
        "The dawn writes poems without ink.",
        "A kiss of sun awakens the calm.",
        "The aurora opens its purple wings.",
        "The day begins with a gesture of peace.",
        "A warm sigh over the sleeping moor.",
        "Light dances in the morning mist.",
        "A soft crescendo of clarity.",
        "The sun murmurs its good morning.",
        "The aurora spills its warm gold.",
        "A stage of calm and color.",
        "The horizon breathes in calm.",
        "A visual poem is born in the sky.",
        "Freshness slips through every window.",
        "The aurora unfolds its soft wings.",
        "A moment of eternity at dawn.",
        "The promise of light can be felt.",
        "The morning air tastes like hope.",
        "An awakening in calm and light.",
        "The day announces itself without rush.",
        "A solar caress for the soul.",
        "The gloom surrenders slowly.",
        "A voiceless song envelops the world.",
        "The aurora blows with sweetness.",
        "A glimmer starts the day's heartbeat.",
        "The morning gives its first breath.",
        "A golden kiss revives the senses.",
        "The promise of the day is drawn.",
        "A sigh of color opens the eyes.",
        "The sun peeks out with respect.",
        "Calm is adorned with light.",
        "A warm halo touches the landscape.",
        "The morning unfolds in silence.",
        "A luminous murmur floods the air.",
        "The aurora sings without words.",
        "A peaceful embrace upon waking.",
        "Beauty is born without fanfare.",
        "A moment of pure serenity.",
        "The aurora blossoms in the sky.",
        "The dawn writes its own anthem.",
        "Light dances in the calm.",
        "A whisper of soft colors.",
        "The morning puts on its new cloak.",
        "A promise in every gust.",
        "The gloom melts into gold.",
        "A murmur of day is born.",
        "The aurora exhales peace.",
        "A silent heartbeat awakens.",
        "Light dresses the world in dawn.",
        "A kiss of aurora awakens spirits.",
        "The morning breathes without rush.",
        "A dawn with a soft touch.",
        "The aurora caresses the silence.",
        "A golden halo kisses the day.",
        "A moment tinged with calm.",
        "Light whispers in the gloom.",
        "A song without notes announces the day.",
        "The morning dances without sound.",
        "The aurora is born with delicacy.",
        "A warm murmur awakens.",
        "Light envelops the horizon.",
        "A golden sigh expands.",
        "The aurora offers its cloak.",
        "A moment where everything is possible.",
        "The morning peeks out in calm.",
        "A verse of light travels across the sky.",
        "The gloom turns into hope.",
        "A murmur of aurora envelops.",
        "The calm of the dawn embraces you.",
        "A warm kiss awakens the senses.",
        "The aurora breathes serenity.",
        "A golden moment of peace.",
        "Light touches the soul.",
        "A morning whisper lulls.",
        "The morning is born in whispers.",
        "A halo of calm extends.",
        "The aurora caresses without rush.",
        "A soft glimmer fills the air.",
        "Light invites you to smile.",
        "A moment of gold in the morning.",
        "The aurora is reflected in your eyes.",
        "A murmur of calm envelops you.",
        "The morning premieres with light.",
        "A golden sigh inhabits the sky.",
        "The aurora whispers to the heart.",
        "A moment without noise, only light.",
        "Light awakens you with tenderness.",
        "A halo of hope at dawn.",
        "The aurora embraces you softly.",
        "A golden murmur runs through the day.",
        "The morning begins in calm.",
        "A moment of love upon waking.",
        "Light dresses the horizon in peace.",
        "A whisper of aurora rests the soul.",
        "The aurora gives you a new song.",
        "A halo of light dances with you.",
        "The morning is a living poem.",
        "An eternal moment of serenity.",
        "The aurora invites you to be reborn."
    ],
    // Mañana
    dayPhrasesEN : [
        "The day begins with a whisper of light.",
        "The morning is dressed in soft tones.",
        "A breath of hope travels through the air.",
        "Clarity floods the senses.",
        "A moment of peace floods everything.",
        "The day's energy awakens your dreams.",
        "The world stretches in calm and color.",
        "An inner song announces the dawn.",
        "The morning breeze whispers promises to you.",
        "The atmosphere vibrates with optimism.",
        "Awaken the soul with a soft melody.",
        "The daylight sings in silence.",
        "The soft rays caress the skin.",
        "The day premieres with delicacy.",
        "A blank canvas invites you to create.",
        "Every morning breath is a renewal.",
        "The morning shines with serenity.",
        "An embrace of light illuminates the soul.",
        "The dawn leaves a trail of tenderness.",
        "Clarity envelops you in calm.",
        "A murmur of peace starts the day.",
        "The morning freshness fills the lungs.",
        "A golden whisper awakens the spirit.",
        "Hope blossoms with the light.",
        "The morning invites you to daydream.",
        "The day presents itself with softness.",
        "The early light embraces the senses.",
        "Silence and light converse.",
        "A halo of energy floods the day.",
        "The morning dances in golden calm.",
        "A moment of gratitude is ignited.",
        "The gentle breeze caresses the mind.",
        "A flash of clarity revives.",
        "The morning feels like an embrace.",
        "A breath of life runs through your veins.",
        "The morning light gives you hope.",
        "A poem without words emerges at dawn.",
        "The morning invites you to breathe deeply.",
        "A moment of beauty envelops you.",
        "The soft light awakens you with sweetness.",
        "A murmur of inspiration begins.",
        "The day offers a new opportunity.",
        "The morning clarity cleanses the spirit.",
        "A wink of light marks the beginning.",
        "The sun's energy envelops you.",
        "A fresh air runs across your skin.",
        "The morning unfolds its magic.",
        "A silent song calls for your attention.",
        "Light seeps into every corner.",
        "A sigh of calm inhabits the environment.",
        "The day's kindness shows itself first.",
        "An aura of optimism emerges softly.",
        "The morning gives us a new chapter.",
        "An inner murmur fuels passion.",
        "Light increases your mental clarity.",
        "A breath of light guides your mind.",
        "The morning offers itself with generosity.",
        "A whisper of self-love resonates.",
        "Clarity gives you confidence.",
        "A moment of gratitude opens the day.",
        "The soft light inspires your steps.",
        "An echo of serenity invades the environment.",
        "The morning celebrates the little things.",
        "A halo of freshness permeates everything.",
        "The morning calm tangles in your senses.",
        "A whisper of light gives a welcome.",
        "The morning distills renewed energy.",
        "A golden murmur accompanies you.",
        "Light announces possibility.",
        "A breath of optimism clears the day.",
        "The morning feels like a gift.",
        "A moment of effortless beauty.",
        "The morning clarity fills your gaze.",
        "An echo of inspiration runs through you.",
        "Light begins to dance in your surroundings.",
        "A soft sigh renews your spirit.",
        "The morning shines with promises.",
        "An inner murmur drives you.",
        "Light envelops you with tenderness.",
        "A breath of hope floods the day.",
        "The morning vibrates with pure energy.",
        "A moment of magic accompanies your awakening.",
        "Clarity gives you a new perspective.",
        "An echo of gratitude travels through the air.",
        "Light opens the way to your dreams.",
        "A whisper of love for the day.",
        "The morning becomes an embrace.",
        "A murmur of light envelops the room.",
        "The morning freshness feeds your soul.",
        "A breath of serenity precedes the day.",
        "Clarity organizes your ideas.",
        "A moment of peace accompanies you.",
        "The morning murmurs sweet possibilities.",
        "A halo of energy supports the unseen.",
        "The daylight caresses your mind.",
        "A whisper of calm envelops the moment.",
        "The morning is dressed in optimism.",
        "A murmur of tenderness caresses your mouth.",
        "Clarity gives you a second wind.",
        "A breath of gratitude fuels your journey.",
        "Light renews your inner strength.",
        "A moment of connection with life.",
        "The morning resonates with good vibes.",
        "A halo of clarity envelops your thoughts.",
        "The morning light paints your plans.",
        "A whisper of possibility inhabits everything.",
        "The calm of the day settles in you.",
        "A murmur of light is reborn in your gaze.",
        "Clarity connects you with what is authentic.",
        "A breath of energy provides new serenity.",
        "The morning breathes with you.",
        "A moment of gratitude sprouts in your chest.",
        "Light accompanies you in every breath.",
        "An inner whisper fuels illusion.",
        "The morning clarity opens the mind.",
        "A murmur of tenderness fills the environment.",
        "The morning offers a moment of peace.",
        "A halo of hope sets everything in calm.",
        "Light softens your immediate surroundings.",
        "A breath of calm precedes your action.",
        "Clarity gives you wings to begin.",
        "A whisper of beauty envelops you.",
        "The morning vibrates with your enthusiasm.",
        "An inner murmur accompanies your walk.",
        "Light gives you a new breath.",
        "A moment of gratitude illuminates.",
        "Clarity opens inner paths.",
        "A halo of energy invites you to live.",
        "The morning light inspires your day.",
        "A whisper of calm gives you focus.",
        "The morning reveals itself as a companion.",
        "An inner murmur drives your awakening.",
        "Clarity begins to flow within you.",
        "A breath of hope fuels your desire.",
        "Light sustains your present moment.",
        "A moment of beauty cheers you up.",
        "The morning gives you its best version.",
        "A whisper of peace accompanies your first cup.",
        "The morning clarity guides your thoughts.",
        "Every morning brings a new page to write.",
        "Just one positive thought can change the entire day.",
        "Open your eyes to the beauty that surrounds you.",
        "Every dawn paints your soul with renewed hope.",
        "Awaken your spirit; the day awaits your brightness.",
        "Every day is a new opportunity disguised as light.",
        "The morning silence holds the peace you seek.",
        "Sow a smile today and harvest joy tomorrow.",
        "Every new dawn brings a hidden promise.",
        "May your inner light compete with the sun.",
        "The late morning offers endless opportunities.",
        "Be the energy you want to see reflected around you.",
        "In the quiet of the morning, listen to your heart.",
        "Every breath awakens a spark of possibility.",
        "Shine today with a brave and serene purpose.",
        "With every morning step, you create your path to greatness.",
        "The scent of your dreams floats in the morning air.",
        "The dawn keeps smiling even if you don't see it.",
        "Today is page 101 of your great story.",
        "A sigh of gratitude can transform your journey.",
        "Between light and shadows, choose to radiate the best of you.",
        "The morning advances, your spirit should too.",
        "Awaken to the hidden brightness within you.",
        "The rays of the sky illuminate what you are passionate about.",
        "Transform the morning air into energy for your soul.",
        "May your inner calm overcome the bustle of the day.",
        "The present is your most important canvas.",
        "Be born again in each morning inhalation.",
        "The day offers you opportunities, take them with faith.",
        "Your smile can change the rhythm of the world.",
        "Water your dreams with the light that fills the day.",
        "Today is a new chapter: make it unforgettable.",
        "Your gratitude paints the morning with vivid colors.",
        "Start the day with determination and you will end with pride.",
        "The harmony of the day is built in this moment.",
        "Believe that the day can surprise you; it usually does.",
        "Let the beat of your heart set the rhythm of the day.",
        "Your energy can light up an entire morning.",
        "Start this part of the day with a calm and open mind.",
        "In every ray, you see the promise of something beautiful.",
        "Let your inner peace guide your next action.",
        "Your dreams deserve light: this morning is their refuge.",
        "Feel the expansion of your being with each inhalation.",
        "The morning wind brings with it infinite possibilities.",
        "Today, reconnect with what makes you vibrate.",
        "Your potential is revealed when you decide to shine.",
        "Breathe gratitude and let everything flow.",
        "You are the spark that ignites an entire morning.",
        "Build the rest of the day with an act of kindness.",
        "Your attitude defines if the day will be epic or common.",
        "Let every gesture count in this late morning.",
        "Let it all go, breathe, and give the day a new chance.",
        "Your presence shines brighter than the morning sun.",
        "Make every moment a personal work of art.",
        "Start this part of the day with your gaze focused on the beautiful.",
        "Every step you take in calm is an intimate victory.",
        "May your mind find serenity in this part of the day.",
        "Let the morning witness your best version.",
        "Find the miracle in the everyday of each morning.",
        "Your positive emotion can completely rewrite the day.",
        "This piece of the morning is your chance to be reborn.",
        "May clarity guide you in every morning decision.",
        "Breathe peace and let the day adjust to you.",
        "Today, choose to rise with gratitude and love.",
        "The air gives you freshness and possibility.",
        "Allow yourself to shine without asking for permission.",
        "Feel the magic that exists in this present moment.",
        "The warmth of your smile can calm any morning.",
        "Breathe deeply; this moment defines the day you will live.",
        "Your morning decisions sow the rest of your journey.",
        "Choose to see the good; the morning rewards you with beauty.",
        "May your inner light also be a refuge for others.",
        "This part of the day is your step to reach your goals.",
        "Breathe inspiration and let everything align.",
        "Walk with intention; even small steps matter.",
        "Your heart knows the way, just listen to its murmur.",
        "Let the light remind you of how great you can be.",
        "Feel the silent company of the late morning.",
        "This stretch of the day invites you to create, to dream, and to love.",
        "Make calm your best tool to move forward.",
        "Your determination is the spark that ignites the day.",
        "Gratitude transforms an ordinary day into a memorable one.",
        "Be the reflection of the peace you wish for the world.",
        "May your dreams have wings this morning.",
        "Be reborn in this stretch between the past and the immediate future.",
        "The day's energy matures with you, without rush.",
        "Find beauty in the simplicity of this moment.",
        "May your heart feel as light as the morning air.",
        "Breathe the certainty that today can be extraordinary."
    ],
    // Mediodia
    middayPhrasesEN : [
        "The sun reaches its most generous point.",
        "A full breath invites you to gather yourself.",
        "Light floods the day with clarity.",
        "Every moment can be a blank canvas.",
        "The day feels wider and brighter.",
        "The energy of midday travels through the air.",
        "A moment to appreciate what you are capable of.",
        "The day's clarity rains opportunities.",
        "Silence and light embrace you tightly.",
        "Your smile can illuminate this warm hour.",
        "A breath of wind caresses the senses.",
        "This moment is a gift of sun and calm.",
        "Life pulses with intensity at this point.",
        "A murmur of inspiration envelops you.",
        "The calm of midday balances the soul.",
        "A pause to be grateful for what you have.",
        "The horizon shows itself in its maximum light.",
        "Your day discovers the next level.",
        "A moment of brightness in full plenitude.",
        "Energy and serenity mix in your chest.",
        "A conscious breath relaxes and centers.",
        "Light reveals hidden possibilities.",
        "Everything seems more possible under this sun.",
        "A moment to reconnect with yourself.",
        "The clarity of midday inspires ideas.",
        "Your spirit dances with intense light.",
        "The warm air whispers confidence to you.",
        "A moment of respite between plans.",
        "Light and silence dialogue softly.",
        "Take a pause and observe your breathing.",
        "This stretch of the day invites you to create.",
        "Energy pulsates with total clarity.",
        "A murmur of gratitude flows within you.",
        "The warmth of the day supports your steps.",
        "A full moment of focus and calm.",
        "The sunlight paints your goals.",
        "Inner silence in full clarity.",
        "The intensity of the light empowers the spirit.",
        "A deep breath to strengthen the day.",
        "Mental clarity reaches its peak.",
        "A moment of connection with the essential.",
        "Light offers concentrated strength and beauty.",
        "Your attention awakens at this point.",
        "A breath of warmth to ignite your ideas.",
        "Calm and energy converge in you.",
        "A moment to be grateful for your path.",
        "The harmony of the day is felt at its maximum.",
        "Light reveals what truly matters.",
        "A moment to reconnect with your dreams.",
        "The clarity of the sun balances the soul.",
        "A murmur of confidence is born within you.",
        "The fullness of midday embraces your spirit.",
        "A breath to recharge your intentions.",
        "Light discovers new directions.",
        "A moment to sow gratitude.",
        "The day's energy vibrates in your being.",
        "A moment to align mind and heart.",
        "The warmth of the sun caresses your spirit.",
        "A breath of calm in the midst of the hustle.",
        "The daylight is poetry without words.",
        "An inner space to look at yourself.",
        "The clarity of midday sustains you.",
        "A murmur of peace vibrates in the air.",
        "The sun's energy awakens action.",
        "A moment to be grateful and move forward.",
        "The warmth of the day renews your strength.",
        "A breath to connect with your essence.",
        "Intense light reveals what you carry inside.",
        "A moment to strengthen your intentions.",
        "Mental clarity reaches its best version.",
        "A murmur of hope envelops your chest.",
        "The day's energy propels you forward.",
        "A moment to reorder your thoughts.",
        "The warmth of the sun fills you with optimism.",
        "A paused breath before resuming your course.",
        "The light of midday is concentrated strength.",
        "A moment to honor your effort.",
        "The day's clarity illuminates your purpose.",
        "A murmur of light activates your inner self.",
        "The radiated energy propels you with certainty.",
        "A moment to be grateful for the journey so far.",
        "The warmth of the day strengthens your wings.",
        "A breath full of clarity and confidence.",
        "Light reveals the value of what you are doing.",
        "A moment to reconnect with your goals.",
        "The clarity of midday inspires decisions.",
        "A murmur of serenity accompanies your step.",
        "The day's energy envelops you in fullness.",
        "A moment to align heart and action.",
        "The solar warmth reminds you of your capability.",
        "A breath to cultivate inner gratitude.",
        "The daylight enhances your determination.",
        "A moment to feel your inner strength.",
        "Mental clarity shines in this stretch.",
        "A murmur of peace strengthens your spirit.",
        "The energy of midday fills you with focus.",
        "A moment to be grateful and reconnect.",
        "The warmth of the sun embodies your passion.",
        "A breath to center your intentions.",
        "Light reveals the beauty of the everyday.",
        "A moment to honor your commitment.",
        "The day's clarity gives you new wings.",
        "A murmur of light accompanies your senses.",
        "The energy of midday guides your steps.",
        "A moment to sow new intentions.",
        "The warmth of the sky shelters your purpose.",
        "The sun embraces your energy with tenderness.",
        "A moment of peace in the middle of the day.",
        "Intense light caresses your projects.",
        "A warm breath for the soul.",
        "The energy of midday renews your impulse.",
        "A moment to be grateful for this vibrant day.",
        "The warmth of the sun comforts the spirit.",
        "A breath of vitality runs through your being.",
        "The fullness of the day recharges your spirit.",
        "A moment of inner connection under the light.",
        "The clarity of midday inspires new ideas.",
        "A murmur of sun feeds your emotions.",
        "Light awakens your dormant creativity.",
        "A soft breath between intense actions.",
        "Warmth envelops every cell of your body.",
        "A moment to reconnect with your intentions.",
        "The energy of midday drives your purpose.",
        "A moment to regain your center.",
        "The sunlight reveals the essential.",
        "A sigh of calm in the middle of the day.",
        "Clarity guides you with firmness and tenderness.",
        "A murmur of gratitude illuminates your surroundings.",
        "The warmth of the day nourishes your heart.",
        "A breath full of clarity and balance.",
        "The energy of midday enhances your soul.",
        "A moment to contemplate your progress.",
        "Light inspires you to continue with passion.",
        "A breath of serenity in the midst of activity.",
        "The fullness of the day fills your inner space.",
        "A joyful moment in the midst of the everyday.",
        "The solar warmth strengthens your spirit.",
        "A conscious breath to align your mind.",
        "The clarity of the sun moves forward with you.",
        "A murmur of peace fills your chest.",
        "The day's energy vibrates within you.",
        "A moment of gratitude for what has been lived.",
        "Light accompanies you in every decision.",
        "A breath of calm in the midst of the routine.",
        "Fullness envelops you with softness.",
        "A moment to reflect and recharge.",
        "The warmth of midday kisses your spirit.",
        "A breath of creation under the sun.",
        "Clarity propels you towards your goals.",
        "A murmur of light strengthens your essence.",
        "The day's energy feels powerful.",
        "A moment of harmony in your journey.",
        "Light sustains you with delicacy.",
        "A breath of gratitude illuminates your step.",
        "The fullness of midday nourishes your being.",
        "A moment of connection with the authentic.",
        "The solar warmth inspires you to keep going.",
        "A breath to rediscover yourself.",
        "The day's clarity awakens your focus.",
        "A murmur of peace runs through your thoughts.",
        "The energy of midday vibrates in your blood.",
        "A moment of pause with intention.",
        "The sunlight paints your being with optimism.",
        "A breath of calm in the midst of the hustle.",
        "The fullness of the day is felt in the air.",
        "A moment to align body, mind, and soul.",
        "The warmth of midday gifts you with fullness.",
        "A breath to refine your intentions.",
        "Clarity strengthens you in every choice.",
        "A murmur of light fills your inner space.",
        "The sun's energy envelops you with life.",
        "A moment of internal reconnection.",
        "The light of midday caresses your purpose.",
        "A breath of serenity accompanies you.",
        "The fullness of the day vibrates in you.",
        "A moment to honor your journey.",
        "The solar warmth strengthens your presence.",
        "A vital breath in the middle of the day.",
        "The clarity of the sun guides your path.",
        "A murmur of gratitude sustains your journey.",
        "The energy of midday renews your impulse.",
        "A moment of calm in the whirlwind.",
        "Light inspires you to shine with transparency.",
        "A breath of serenity renews you.",
        "The fullness of the day filters into your days.",
        "A moment to be grateful for what has been achieved.",
        "The warmth of the sun accompanies your steps.",
        "An inner breath in the midst of the hustle.",
        "The clarity of midday recognizes your value.",
        "A murmur of peace revitalizes your essence.",
        "The day's energy pulses in your heart.",
        "A conscious moment of gratitude.",
        "Light embraces you with softness.",
        "A breath of calm to nourish your spirit.",
        "The fullness of midday inspires you.",
        "A moment to regain your harmony.",
        "The solar warmth strengthens your confidence.",
        "A breath full of pure clarity.",
        "Clarity propels you towards new goals.",
        "A murmur of light sustains your essence.",
        "The sun's energy vibrates in your being.",
        "A moment of full reconnection.",
        "The light of midday caresses your inner self.",
        "A breath of serenity illuminates your being.",
        "The fullness of the day recharges your mind.",
        "A moment to honor your path.",
        "The warmth of the sun gifts you with presence.",
        "A vital breath strengthens your spirit.",
        "The clarity of midday guides your steps.",
        "A murmur of gratitude flows in you.",
        "The day's energy sustains your impulse.",
        "A conscious moment of well-being.",
        "The sunlight accompanies your growth.",
        "A breath of calm elevates your intention.",
        "The fullness of midday nourishes your being.",
        "A moment to reconnect with your essence.",
        "The solar warmth inspires your walk."
    ],
    // Tarde
    afternoonPhrasesEN : [
        "The afternoon envelops you with its golden light.",
        "A sigh of sun softens the day.",
        "This stretch of the day invites reflection.",
        "The light becomes warm and enveloping.",
        "A murmur of calm permeates the environment.",
        "The afternoon caresses your thoughts.",
        "A moment to reconnect with the present.",
        "Serenity spreads with every ray.",
        "A golden moment to breathe deeply.",
        "The afternoon light paints your emotions.",
        "A breath of peace runs through your essence.",
        "The atmosphere whispers tranquility.",
        "This stretch of the day awakens inspiration.",
        "The afternoon brings sweet promises with it.",
        "A serene murmur accompanies your walk.",
        "The light becomes softer and more comforting.",
        "A moment to be grateful for who you are.",
        "The afternoon invites a conscious pause.",
        "A warm embrace of light surrounds you.",
        "The day's calm finds its peak.",
        "A breath to align your inner self.",
        "Light filters through with a gentle tenderness.",
        "A soft silence awakens your intuition.",
        "The afternoon resonates with a silent song.",
        "A golden murmur fills the air.",
        "The warm light strengthens your ideas.",
        "A moment to appreciate the simple things.",
        "The atmosphere becomes contemplative.",
        "A breath of clarity illuminates your mind.",
        "The afternoon embraces you without a rush.",
        "A moment of gratitude in the temperate light.",
        "The light becomes an intimate refuge.",
        "A soft murmur brings you serenity.",
        "Calm diffuses in every ray.",
        "A golden breath comforts the day.",
        "The afternoon unfolds its peaceful cloak.",
        "A warm sigh floods the environment.",
        "The golden light awakens creativity.",
        "A moment to reconnect with yourself.",
        "The afternoon gifts you its inner peace.",
        "A faint murmur envelops you.",
        "The light settles upon your thoughts.",
        "A deep breath renews you.",
        "The afternoon builds spaces of calm.",
        "A moment to sow gratitude.",
        "The light draws tranquil shadows.",
        "A breath of inspiration caresses you.",
        "The atmosphere vibrates with harmony.",
        "A murmur of light strengthens your being.",
        "The afternoon balances your energy.",
        "A moment to strengthen your dreams.",
        "The light invites you to create without noise.",
        "A conscious breath supports you.",
        "The atmosphere beats with serenity.",
        "A breath of beauty inhabits this stretch.",
        "The afternoon whispers full presence to you.",
        "A warm murmur strengthens your soul.",
        "The light clings to your serenity.",
        "A moment to create from the heart.",
        "The afternoon caresses your senses.",
        "A breath of gratitude accompanies you.",
        "The atmosphere becomes a refuge.",
        "A breath of calm animates your being.",
        "The light envelops you with softness.",
        "A golden murmur harmonizes your ideas.",
        "The afternoon consolidates your inner balance.",
        "A moment to honor your journey.",
        "The light softens every thought.",
        "A vital breath strengthens your being.",
        "The atmosphere vibrates with calming light.",
        "A breath of clarity illuminates your essence.",
        "The afternoon gifts you silent creativity.",
        "A murmur of gratitude resonates.",
        "The light fills your spirit with tenderness.",
        "A moment of gentle introspection.",
        "The atmosphere becomes pure contemplation.",
        "A breath to realign your energy.",
        "The afternoon embraces you without demands.",
        "A breath of hope runs through your veins.",
        "The golden light beautifies the moment.",
        "A serene murmur calms your worries.",
        "The afternoon offers you its best version.",
        "A moment to savor the stillness.",
        "The light filters into your inner self.",
        "A conscious breath embraces your mind.",
        "The atmosphere radiates comforting light.",
        "A breath of peace runs through your being.",
        "The afternoon feels like a visual poem.",
        "A murmur of calm strengthens your center.",
        "The light guides you toward the essential.",
        "A moment of authentic connection.",
        "The atmosphere offers you an internal refuge.",
        "A breath of light renews your impulse.",
        "The afternoon gifts you serene clarity.",
        "A breath of gratitude embraces your day.",
        "The light settles softly on your spirit.",
        "A moment to reaffirm your purposes.",
        "The atmosphere envelops you in calm.",
        "An inner murmur awakens your soul.",
        "The afternoon vibrates with a silent song.",
        "A breath to value what has been achieved.",
        "The light nourishes you with fullness.",
        "A breath of serenity grounds your surroundings.",
        "The calm atmosphere beats along with you.",
        "A moment to feel your strength.",
        "The afternoon resonates with golden secrets.",
        "A breath of light caresses the spirit.",
        "The evening warmth awakens your dreams.",
        "A moment to listen to your breathing.",
        "The afternoon envelops you in subtle serenity.",
        "A soft murmur strengthens your inner self.",
        "The light enters your being without a rush.",
        "A conscious breath reconnects the soul.",
        "The afternoon calm spreads through the environment.",
        "A moment to sow inner silence.",
        "The golden light supports every step.",
        "A moment of gratitude filters into you.",
        "The afternoon whispers a sweet confidence.",
        "A breath of tenderness envelops your senses.",
        "The atmosphere beats with evening softness.",
        "A slow breath centers your thoughts.",
        "The afternoon embraces the end of the day.",
        "A murmur of calm accompanies you.",
        "The intense light releases inner harmony.",
        "A moment to reconnect with the profound.",
        "The evening stillness caresses your mind.",
        "A breath of inspiration runs across your skin.",
        "The afternoon feels like a warm hug.",
        "A breath to value what has been achieved.",
        "The light gifts you a haven of peace.",
        "A moment to align body and mind.",
        "The afternoon flows with a peaceful rhythm.",
        "An inner murmur encourages your confidence.",
        "The golden light keeps you from rushing.",
        "A moment to be grateful for this stretch.",
        "The atmosphere is tinged with calm and sweetness.",
        "A breath of gratitude in each exhale.",
        "The afternoon breathes along with your silence.",
        "An evening breath renews energies.",
        "The light rests softly on your spirit.",
        "A moment to feel your heart beat.",
        "The evening calm strengthens your spirit.",
        "A serene murmur guides you.",
        "The afternoon protects you in its warm cloak.",
        "A breath to reconnect with your center.",
        "The golden light envelops your thoughts.",
        "A moment of acoustic introspection.",
        "The atmosphere vibrates softly and constantly.",
        "A breath of calm runs through your consciousness.",
        "The afternoon offers you an inner refuge.",
        "A moment to revitalize your purpose.",
        "The evening light sustains your balance.",
        "A murmur of gratitude emerges.",
        "The afternoon presents itself with nobility.",
        "A breath to continue with intention.",
        "The golden calm comforts your steps.",
        "A moment to redefine your well-being.",
        "The soft light refines your sensitivity.",
        "A breath of clarity within you.",
        "The afternoon sings without words.",
        "A conscious breath accompanies your essence.",
        "The atmosphere flows with serenity.",
        "A moment to emphasize your present.",
        "The golden light harmonizes your ideas.",
        "A calm murmur nourishes your spirit.",
        "The afternoon intoxicates your senses.",
        "A breath of peace comforts you.",
        "The afternoon illuminates your stillness.",
        "A deep breath aligns your being.",
        "The evening light invites reflection.",
        "A moment to be grateful for this journey.",
        "The atmosphere whispers tranquility.",
        "A moment to open the heart.",
        "The golden light evokes inner tenderness.",
        "A breath of calm strengthens your inner self.",
        "The afternoon covers you with its peaceful cloak.",
        "A soft murmur encourages your thoughts.",
        "The light filters through like a silent embrace.",
        "A longed-for breath upon reaching this stretch.",
        "The evening calm becomes a presence.",
        "A moment to nourish your essence.",
        "The peaceful atmosphere conveys security.",
        "A breath of inspiration illuminates your path.",
        "The afternoon feels like a serene song.",
        "A breath that orders your ideas.",
        "The light rests delicately on you.",
        "A moment to deepen the inner connection.",
        "The afternoon resumes the day's pulse.",
        "An intimate murmur restores the spirit.",
        "The evening light strengthens your introspection.",
        "A gentle breath accompanies your rest.",
        "Calm envelops your present moment.",
        "A breath of gratitude embraces you.",
        "The afternoon gifts you silent clarity.",
        "A moment to contemplate your energy.",
        "The atmosphere is charged with kindness.",
        "A comforting murmur fills the air.",
        "The golden light anchors you to the moment.",
        "A breath to close this day's chapter.",
        "The afternoon breathes with you in calm.",
        "A breath of beauty reveals itself.",
        "The light beautifies your inner silence.",
        "A moment to value your path.",
        "The atmosphere becomes an internal refuge.",
        "A moment of peace envelops you.",
        "The afternoon resonates with your essence.",
        "A soft murmur rests on your chest.",
        "The evening light accompanies your reflection.",
        "A breath that calms the hustle.",
        "Calm accompanies you in this stretch.",
        "A breath of inspiration sustains you.",
        "The afternoon shows its kindest face.",
        "A moment to be grateful for what you've learned.",
        "The atmosphere opens before your gaze.",
        "A murmur of calm embraces your heart.",
        "The soft light illuminates your well-being.",
        "A breath to complete your journey.",
        "The afternoon vibrates with silent hope."
    ],
    // Atardecer
    sunsetPhrasesEN : [
        "The sky spills out in tones of fire.",
        "A sigh of light descends on the horizon.",
        "The evening calm paints everything in gold.",
        "A moment to find yourself in the beauty.",
        "The sun says goodbye with a warm embrace.",
        "A murmur of gratitude tinges the afternoon.",
        "The colors of dusk caress the soul.",
        "A breath of serenity in every reflection.",
        "The afternoon sings its song in silence.",
        "A breath to appreciate the ephemeral.",
        "The atmosphere is dressed in soft tones.",
        "A moment where the day becomes art.",
        "The sky floats in a golden palette.",
        "A murmur of calm crosses your chest.",
        "The descending light balances the spirit.",
        "A breath of poetry in the twilight.",
        "The afternoon becomes a soft whisper.",
        "A moment to be grateful for this gift.",
        "The calm of the sunset envelops the environment.",
        "A warm murmur nourishes your thoughts.",
        "The light tames as the day falls.",
        "A breath of nostalgia transforms the sky.",
        "The afternoon accompanies you in its fullness.",
        "A moment of golden introspection.",
        "The atmosphere vibrates in twilight tones.",
        "A soft murmur sustains you from the sky.",
        "The golden light outlines your dreams.",
        "An autumnal sigh dresses the afternoon.",
        "The calm of dusk fills your senses.",
        "An instant refuge of peace and color.",
        "The dreamlike afternoon takes your breath away.",
        "A breath of light soothes the mind.",
        "The atmosphere shines like brushstrokes.",
        "An evening murmur nourishes the inner self.",
        "The afternoon becomes an emotional stage.",
        "A moment to reconnect with patience.",
        "The light glides sweetly through the air.",
        "A breath of calm seals the day.",
        "The calm of the sunset whispers in your ear.",
        "A golden murmur embraces your dreams.",
        "The afternoon blossoms in soft hues.",
        "A moment to savor the lightness.",
        "The atmosphere expands slowly.",
        "An intimate murmur accompanies the sky.",
        "The soft light invites you to contemplate.",
        "A breath of gratitude colors the surroundings.",
        "The afternoon breathes with refined elegance.",
        "A moment to merge with nature.",
        "The evening serenity enlivens your senses.",
        "A golden murmur cradles the day.",
        "The light of dusk balances the spirit.",
        "A moment of unexpected beauty.",
        "The atmosphere is dressed in golden calm.",
        "An evening sigh caresses the heart.",
        "The afternoon becomes a song without words.",
        "A breath of light strengthens your peace.",
        "The calm of twilight protects you.",
        "A moment to close with gratitude.",
        "The fading light envelops you softly.",
        "A warm murmur fills your thoughts.",
        "The afternoon becomes a visual poem.",
        "A breath of serenity shelters you.",
        "The atmosphere flows with evening sweetness.",
        "A moment of luminous introspection.",
        "The golden light outlines your ideas.",
        "A murmur of calm sustains your spirit.",
        "The afternoon offers you an intimate refuge.",
        "A breath of gratitude runs through your chest.",
        "The serenity of the sunset embraces you.",
        "A moment to reconnect with your essence.",
        "The descending light guides you to rest.",
        "A murmur of light affirms your inner self.",
        "The afternoon radiates a comforting silence.",
        "A breath of peace inhabits every breath.",
        "The atmosphere turns into silent poetry.",
        "A moment to be grateful for the present.",
        "The evening light dissolves your fatigue.",
        "A golden murmur repairs your balance.",
        "The afternoon envelops you with soft hues.",
        "A breath of calm dissolves tensions.",
        "The evening serenity reconnects you.",
        "A moment to nurture your tranquility.",
        "The fading light illuminates your introspection.",
        "An evening murmur inspires calm.",
        "The afternoon offers its golden embrace.",
        "A breath of gratitude matures your calm.",
        "The atmosphere is adorned with light silence.",
        "A moment to merge with the day.",
        "The final light outlines your aspirations.",
        "A soft murmur accompanies your dusk.",
        "The afternoon becomes an inner mirror.",
        "A breath of serenity connects you to the here and now.",
        "The evening calm envelops you without rush.",
        "A moment of fullness and depth.",
        "The golden light strengthens your well-being.",
        "An inner murmur sustains your spirit.",
        "The afternoon gathers the best of your day.",
        "A breath of gratitude accompanies the closing.",
        "The evening atmosphere invites you to silence.",
        "A moment to align heart and mind.",
        "The light says goodbye, beautifying the landscape.",
        "A golden murmur revives your essence.",
        "The afternoon is sealed with a warm sigh.",
        "A breath of calm bids farewell to the twilight.",
        "The serenity of dusk comforts your steps.",
        "A moment to release tensions.",
        "The evening light covers your thoughts.",
        "An intimate murmur frames your smile.",
        "The afternoon extends in its golden embrace.",
        "A breath of gratitude culminates the day.",
        "The atmosphere becomes a serene witness.",
        "A moment to be grateful and let go.",
        "The descending light offers a kind farewell.",
        "A soft murmur ends the journey.",
        "The afternoon offers its final kiss of light.",
        "A breath of calm caresses the twilight.",
        "The evening serenity nourishes your inner self."
    ],
    // Noche
    nightPhrasesEN : [
        "The night begins to whisper.",
        "The sky is tinged with deep blue.",
        "The stars awaken slowly.",
        "The moon peeks out timidly.",
        "The cool air caresses the skin.",
        "The city lights flicker like fireflies.",
        "It's time to let yourself be carried away by dreams.",
        "The day says goodbye with a sigh.",
        "The quiet of the night invites reflection.",
        "Silence becomes company.",
        "The shadows lengthen with elegance.",
        "The night dresses up.",
        "The night sky is a starry canvas.",
        "The night breeze brings secrets with it.",
        "The streets empty, but the city is still alive.",
        "It's the perfect time for a cup of tea.",
        "Darkness is not absence, but presence.",
        "The stars tell ancient stories.",
        "The full moon illuminates the path.",
        "The night is young and full of promises.",
        "It's time to let the mind fly free.",
        "The serenity of the night envelops the soul.",
        "The distant lights seem to whisper songs.",
        "The nightly quiet is a balm for the spirit.",
        "It's time to let go and rest.",
        "The night becomes a cozy refuge.",
        "The stars seem closer than ever.",
        "The full moon reflects forgotten dreams.",
        "The city sleeps, but thoughts awaken.",
        "The night is a poem without words.",
        "The shadows dance to the rhythm of the wind.",
        "It's the perfect moment for a silent embrace.",
        "Darkness hides beauty in every corner.",
        "The city lights are stars on earth.",
        "The night invites calm and introspection.",
        "It's time to let yourself be carried away by the soul's music.",
        "The full moon reflects shared secrets.",
        "The stars twinkle like distant promises.",
        "The night is a blank canvas for dreams.",
        "It's time to close your eyes and travel.",
        "Darkness is not fear, it is mystery.",
        "The city lights are modern fireflies.",
        "The night is a refuge for deep thoughts.",
        "It's time to let the heart speak.",
        "The full moon illuminates the lost paths.",
        "The stars are the eyes of the universe.",
        "The night is a sigh of the day.",
        "It's time to listen to the silence.",
        "Darkness hides stories to be told.",
        "The distant lights are beacons in the distance.",
        "The night is the stage for dreams.",
        "It's time to let the mind be free.",
        "The full moon is a mirror of the soul.",
        "The stars are the footprints of time.",
        "The night is a warm and silent embrace.",
        "It's time to let yourself be carried away by imagination.",
        "Darkness hides beauty within itself.",
        "The city lights are trapped stars.",
        "The night invites reflection and rest.",
        "It's time to let the soul relax.",
        "The full moon illuminates the secrets of the heart.",
        "The stars are the laughter of the universe.",
        "The night is a journey without maps.",
        "It's time to let go and rest.",
        "Darkness hides magic in its silence.",
        "The distant lights are dreams to be fulfilled.",
        "The night is the refuge of poets.",
        "It's time to let thoughts flow.",
        "The full moon reflects the beauty of the soul.",
        "The stars are the words of the sky.",
        "The night is a canvas for dreams.",
        "It's time to close your eyes and fly.",
        "Darkness hides stories to be discovered.",
        "The city lights are stars in motion.",
        "The night invites calm and serenity.",
        "It's time to let the heart express itself.",
        "The full moon illuminates hidden desires.",
        "The stars are the sighs of the universe.",
        "The night is an endless poem.",
        "It's time to listen to the murmur of the wind.",
        "Darkness hides beauty in its mystery.",
        "The distant lights are forgotten memories.",
        "The night is the refuge of lost dreams.",
        "It's time to let the mind be free.",
        "The full moon reflects the inner light.",
        "The stars are the footprints of the gods.",
        "The night is a silent embrace.",
        "It's time to let yourself be carried away by peace.",
        "Darkness hides secrets to be revealed.",
        "The city lights are shooting stars.",
        "The night invites reflection and calm.",
        "It's time to let the soul relax.",
        "The full moon illuminates the lonely paths.",
        "The stars are the eyes of the sky.",
        "The night is a sigh of the day.",
        "It's time to listen to the silence.",
        "Darkness hides stories to be told.",
        "The distant lights are beacons in the distance.",
        "The night is the stage for dreams.",
        "It's time to let the mind be free.",
        "The full moon is a mirror of the soul.",
        "The stars are the footprints of time.",
        "The night is a warm and silent embrace.",
        "It's time to let yourself be carried away by imagination.",
        "Darkness hides beauty within itself.",
        "The city lights are trapped stars.",
        "The night invites reflection and rest.",
        "It's time to let the soul relax.",
        "The full moon illuminates the secrets of the heart.",
        "The stars are the laughter of the universe.",
        "The night is a journey without maps.",
        "It's time to let go and rest.",
        "Darkness hides magic in its silence.",
        "The distant lights are dreams to be fulfilled.",
        "The night is the refuge of poets.",
        "It's time to let thoughts flow.",
        "The full moon reflects the beauty of the soul.",
        "The stars are the words of the sky.",
        "The night is a canvas for dreams.",
        "It's time to close your eyes and fly.",
        "Darkness hides stories to be discovered.",
        "The city lights are stars in motion.",
        "The night invites calm and serenity.",
        "It's time to let the heart express itself.",
        "The full moon illuminates hidden desires.",
        "The stars are the sighs of the universe.",
        "The night is an endless poem.",
        "It's time to listen to the murmur of the wind.",
        "Darkness hides beauty in its mystery.",
        "The distant lights are forgotten memories.",
        "The night is the refuge of lost dreams.",
        "It's time to let the mind be free.",
        "The full moon reflects the inner light.",
        "The stars are the footprints of the gods.",
        "The night is a silent embrace.",
        "It's time to let yourself be carried away by peace.",
        "Darkness hides secrets to be revealed.",
        "The city lights are shooting stars.",
        "The night invites reflection and calm.",
        "It's time to let the soul relax.",
        "The full moon illuminates the lonely paths.",
        "The stars are the eyes of the sky.",
        "The night is a sigh of the day.",
        "It's time to listen to the silence.",
        "Darkness hides stories to be told.",
        "The distant lights are beacons in the distance.",
        "The night is the stage for dreams.",
        "It's time to let the mind be free.",
        "The full moon is a mirror of the soul.",
        "The stars are the footprints of time.",
        "The night is a warm and silent embrace.",
        "It's time to let yourself be carried away by imagination.",
        "Darkness hides beauty within itself.",
        "The city lights are trapped stars.",
        "The night invites reflection and rest.",
        "It's time to let the soul relax.",
        "The full moon illuminates the secrets of the heart.",
        "The stars are the laughter of the universe.",
        "The night is a journey without maps.",
        "It's time to let go and rest.",
        "Darkness hides magic in its silence.",
        "The distant lights are dreams to be fulfilled.",
        "The night is the refuge of poets.",
        "It's time to let thoughts flow.",
        "The full moon reflects the beauty of the soul.",
        "The stars are the words of the sky.",
        "The night is a canvas for dreams.",
        "It's time to close your eyes and fly.",
        "Darkness hides stories to be discovered.",
        "The city lights are stars in motion.",
        "The night invites calm and serenity.",
        "It's time to let the heart express itself.",
        "The full moon illuminates hidden desires.",
        "The stars are the sighs of the universe.",
        "The night is an endless poem.",
        "It's time to listen to the murmur of the wind.",
        "Darkness hides beauty in its mystery.",
        "The distant lights are forgotten memories.",
        "The night is the refuge of lost dreams.",
        "The night whispers secrets to the wind's ear.",
        "The night sky is a canvas of lost stars.",
        "The moon silently watches the dreams that are born.",
        "Darkness welcomes wandering thoughts.",
        "The stars twinkle like forgotten sighs.",
        "The early morning is a whisper among the shadows.",
        "The night wind sings distant songs.",
        "The full moon illuminates the lonely paths.",
        "The silence of the night is a refuge for the soul.",
        "The stars are the eyes of the universe watching.",
        "The night is a poem without words.",
        "The murmur of the wind is the voice of darkness.",
        "The moon reflects the dreams that have not yet been told.",
        "The shadows lengthen like lost memories.",
        "The night sky is a sea of sailing stars.",
        "The night is a canvas where dreams are painted.",
        "The silence of the early morning is a deep song.",
        "The stars are the jewels of the night's mantle.",
        "The full moon is a lighthouse in the darkness.",
        "The night is a warm and silent embrace.",
        "The shadows dance to the rhythm of the night wind.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul.",
        "The night is a sigh of the universe.",
        "The stars are the promises of the sky.",
        "The full moon is a mirror of the night.",
        "The silence of the early morning is a deep song.",
        "The shadows lengthen like lost memories.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul.",
        "The night is a sigh of the universe.",
        "The stars are the promises of the sky.",
        "The full moon is a mirror of the night.",
        "The silence of the early morning is a deep song.",
        "The shadows lengthen like lost memories.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul.",
        "The night is a sigh of the universe.",
        "The stars are the promises of the sky.",
        "The full moon is a mirror of the night.",
        "The silence of the early morning is a deep song.",
        "The shadows lengthen like lost memories.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul.",
        "The night is a sigh of the universe.",
        "The stars are the promises of the sky.",
        "The full moon is a mirror of the night.",
        "The silence of the early morning is a deep song.",
        "The shadows lengthen like lost memories.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul.",
        "The night is a sigh of the universe.",
        "The stars are the promises of the sky.",
        "The full moon is a mirror of the night.",
        "The silence of the early morning is a deep song.",
        "The shadows lengthen like lost memories.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul.",
        "The night is a sigh of the universe.",
        "The stars are the promises of the sky.",
        "The full moon is a mirror of the night.",
        "The silence of the early morning is a deep song.",
        "The shadows lengthen like lost memories.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul.",
        "The night is a sigh of the universe.",
        "The stars are the promises of the sky.",
        "The full moon is a mirror of the night.",
        "The silence of the early morning is a deep song.",
        "The shadows lengthen like lost memories.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul.",
        "The night is a sigh of the universe.",
        "The stars are the promises of the sky.",
        "The full moon is a mirror of the night.",
        "The silence of the early morning is a deep song.",
        "The shadows lengthen like lost memories.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul.",
        "The night is a sigh of the universe.",
        "The stars are the promises of the sky.",
        "The full moon is a mirror of the night.",
        "The silence of the early morning is a deep song.",
        "The shadows lengthen like lost memories.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul.",
        "The night is a sigh of the universe.",
        "The stars are the promises of the sky.",
        "The full moon is a mirror of the night.",
        "The silence of the early morning is a deep song.",
        "The shadows lengthen like lost memories.",
        "The starry sky is a map of lost dreams.",
        "The moon silently observes the world's secrets.",
        "Darkness hides stories to be discovered.",
        "The stars are the footprints of the gods in the sky.",
        "The night is a refuge for lonely thoughts.",
        "The night wind caresses forgotten memories.",
        "The full moon illuminates the paths of the wandering soul.",
        "The shadows lengthen like sighs in the gloom.",
        "The night sky is a mirror of the human soul."
    ]
};

export default collectionPhrasesEN;