const collectionPhrasesES = {
    // Amanecer
    dawnPhrasesES : [
        "La mañana susurra promesas al viento.",
        "El alba despierta con un suspiro de luz.",
        "Un bálsamo dorado acaricia el horizonte.",
        "El cielo se viste de acuarelas suaves.",
        "Un murmullo de esperanza recorre el aire.",
        "El silencio abre paso a la luz tímida.",
        "El mundo se estira y bosteza en colores.",
        "La aurora enseña magia sin palabras.",
        "Todo renace en ese instante sagrado.",
        "Un latido dorado inicia el día.",
        "La brisa temprana trae nuevos comienzos.",
        "Un poema de luz nace en el cielo.",
        "La penumbra se rinde ante el dorado.",
        "Un susurro cálido despierta la tierra.",
        "El horizonte se enciende en calma.",
        "Una melodía silenciosa gobierna el alba.",
        "El cielo respira en tonos pastel.",
        "La vida asoma detrás del velo nocturno.",
        "El sol alza su primer saludo tímido.",
        "La esperanza se filtra en cada rayo.",
        "El mundo despierta en murmullos dorados.",
        "Un instante eterno bañado en luz.",
        "La aurora pinta sus primeras líneas.",
        "Un abrazo de luz cubre la mañana.",
        "El día comienza con un suspiro cálido.",
        "Un lienzo de calma se despliega.",
        "La claridad se insinúa en el aire fresco.",
        "Un canto silente anuncia el día.",
        "La esencia del amanecer llena el alma.",
        "El cielo descubre su rostro apacible.",
        "Un murmullo áureo mece el horizonte.",
        "La promesa de un nuevo capítulo vibra.",
        "El aire vibra con tonos de esperanza.",
        "Susurros de luz acarician la penumbra.",
        "La aurora despierta con suavidad.",
        "Un halo dorado envuelve la tierra.",
        "Cada mañana renace la posibilidad.",
        "El silencio del alba susurra vida.",
        "Una caricia de sol irrumpe despacio.",
        "La noche se disuelve con dulzura.",
        "Un destello suave besa el cielo.",
        "La aurora abraza el silencio nocturno.",
        "Un verso de luz recita el horizonte.",
        "La frescura del alba llena los pulmones.",
        "Un aire nuevo carga la promesa.",
        "La calma previa al latido del día.",
        "Un soplo de luz viaja sin prisa.",
        "La atmósfera vibra en tonos suaves.",
        "Un cielo naciente regala serenidad.",
        "El mundo despierta en un susurro.",
        "Una caricia de amanecer penetra el alma.",
        "El espacio se llena de luz delicada.",
        "El alba escribe poemas sin tinta.",
        "Un beso de sol despierta la calma.",
        "La aurora abre sus alas púrpura.",
        "El día comienza con un gesto de paz.",
        "Suspiro cálido sobre el páramo dormido.",
        "La luz danza en la bruma matinal.",
        "Un suave crescendo de claridad.",
        "El sol murmura su buen día.",
        "La aurora derrama su oro tibio.",
        "Un escenario de calma y color.",
        "El horizonte respira en calma.",
        "Un poema visual nace en el cielo.",
        "La frescura se cuela por cada ventana.",
        "La aurora despliega sus alas suaves.",
        "Un instante de eternidad al alba.",
        "La promesa de la luz se siente.",
        "El aire matutino sabe a esperanza.",
        "Un despertar en calma y luz.",
        "El día se anuncia sin prisa.",
        "Una caricia solar para el alma.",
        "La penumbra se rinde lentamente.",
        "Un canto sin voz envuelve el mundo.",
        "La aurora sopla con dulzura.",
        "Un destello inicia el latido del día.",
        "La mañana regala su primer aliento.",
        "Un beso áureo revive los sentidos.",
        "La promesa del día se dibuja.",
        "Un suspiro de color abre los ojos.",
        "El sol asoma con respeto.",
        "La calma se adorna con luz.",
        "Un halo tibio roza el paisaje.",
        "La mañana se despliega en silencio.",
        "Un murmullo luminoso inunda el aire.",
        "La aurora canta sin palabras.",
        "Un abrazo apacible al despertar.",
        "La belleza nace sin escándalo.",
        "Un instante de serenidad pura.",
        "La aurora florece en el cielo.",
        "El alba escribe su propio himno.",
        "La luz danza en la calma.",
        "Un susurro de colores suaves.",
        "La mañana estrena su manto.",
        "Una promesa en cada ráfaga.",
        "La penumbra se funde en oro.",
        "Un murmullo de día nace.",
        "La aurora exhala paz.",
        "Un latido silencioso despierta.",
        "La luz viste el mundo de albor.",
        "Un beso de aurora despierta ánimos.",
        "La mañana respira sin prisas.",
        "Un amanecer de tacto suave.",
        "La aurora acaricia el silencio.",
        "Un halo dorado besa el día.",
        "Un instante teñido de calma.",
        "La luz susurra en la penumbra.",
        "Un canto sin notas anuncia el día.",
        "La mañana danza sin sonido.",
        "La aurora nace con delicadeza.",
        "Un murmullo cálido despierta.",
        "La luz envuelve el horizonte.",
        "Un suspiro dorado se expande.",
        "La aurora regala su manto.",
        "Un instante donde todo es posible.",
        "La mañana se asoma en calma.",
        "Un verso de luz recorre el cielo.",
        "La penumbra se convierte en esperanza.",
        "Un murmullo de aurora envuelve.",
        "La calma del amanecer te abraza.",
        "Un beso tibio despierta sentidos.",
        "La aurora respira serenidad.",
        "Un instante dorado de paz.",
        "La luz toca el alma.",
        "Un susurro matinal arrulla.",
        "La mañana nace en susurros.",
        "Un halo de calma se extiende.",
        "La aurora acaricia sin prisa.",
        "Un destello suave llena el aire.",
        "La luz te invita a sonreír.",
        "Un instante de oro en la mañana.",
        "La aurora se refleja en tus ojos.",
        "Un murmullo de calma te envuelve.",
        "La mañana se estrena con luz.",
        "Un suspiro dorado habita el cielo.",
        "La aurora susurra al corazón.",
        "Un instante sin ruido, solo luz.",
        "La luz te despierta con ternura.",
        "Un halo de esperanza al alba.",
        "La aurora te abraza suavemente.",
        "Un murmullo dorado recorre el día.",
        "La mañana inicia en calma.",
        "Un instante de amor al despertar.",
        "La luz viste el horizonte de paz.",
        "Un susurro de aurora reposa el alma.",
        "La aurora te regala un nuevo canto.",
        "Un halo de luz danza contigo.",
        "La mañana es un poema vivo.",
        "Un instante eterno de serenidad.",
        "La aurora te invita a renacer."
    ],
    // Mañana
    dayPhrasesES : [
        "El día comienza con un susurro de luz.",
        "La mañana se viste de tonos suaves.",
        "Un soplo de esperanza recorre el aire.",
        "La claridad inunda los sentidos.",
        "Un instante de paz inunda todo.",
        "La energía del día despierta tus sueños.",
        "El mundo se estira en calma y color.",
        "Un canto interior anuncia el amanecer.",
        "La brisa matinal te susurra promesas.",
        "La atmósfera vibra con optimismo.",
        "Despierta el alma con suave melodía.",
        "La luz del día canta en silencio.",
        "Los rayos suaves acarician la piel.",
        "El día se estrena con delicadeza.",
        "Un lienzo en blanco te invita a crear.",
        "Cada respiro matutino es renovación.",
        "La mañana brilla con serenidad.",
        "Un abrazo de luz ilumina el alma.",
        "El alba deja un rastro de ternura.",
        "La claridad te envuelve en calma.",
        "Un murmullo de paz inicia el día.",
        "La frescura matinal llena los pulmones.",
        "Un susurro dorado despierta el ánimo.",
        "La esperanza florece con la luz.",
        "La mañana invita a soñar despierto.",
        "El día se presenta con suavidad.",
        "La luz temprana abraza los sentidos.",
        "El silencio y la luz conversan.",
        "Un halo de energía inunda el día.",
        "La mañana danza en calma dorada.",
        "Un momento de gratitud se enciende.",
        "La brisa suave acaricia la mente.",
        "Un destello de claridad reaviva.",
        "La mañana se siente como abrazo.",
        "Un soplo de vida corre por tus venas.",
        "La luz matinal te regala esperanza.",
        "Un poema sin palabras emerge al alba.",
        "La mañana te invita a respirar profundo.",
        "Un instante de belleza te envuelve.",
        "La luz suave te despierta con dulzura.",
        "Un murmullo de inspiración empieza.",
        "El día ofrece una nueva oportunidad.",
        "La claridad matinal limpia el ánimo.",
        "Un guiño de luz marca el comienzo.",
        "La energía del sol te envuelve.",
        "Un aire fresco recorre tu piel.",
        "La mañana despliega su magia.",
        "Un canto silencioso reclama tu atención.",
        "La luz se cuela por cada rincón.",
        "Un suspiro de calma habita el ambiente.",
        "La bondad del día asoma primero.",
        "Un aura de optimismo emerge suavemente.",
        "La mañana nos regala un nuevo capítulo.",
        "Un murmullo interior aviva la pasión.",
        "La luz aumenta tu claridad mental.",
        "Un soplo de luz guía tu mente.",
        "La mañana se ofrece con generosidad.",
        "Un susurro de amor propio resuena.",
        "La claridad te regala confianza.",
        "Un instante de gratitud abre el día.",
        "La luz suave inspira tus pasos.",
        "Un eco de serenidad invade el ambiente.",
        "La mañana celebra las pequeñas cosas.",
        "Un halo de frescura impregna todo.",
        "La calma matinal se enreda en tus sentidos.",
        "Un susurro de luz da la bienvenida.",
        "La mañana destila energía renovada.",
        "Un murmullo dorado te acompaña.",
        "La luz anuncia la posibilidad.",
        "Un soplo de optimismo despeja el día.",
        "La mañana se siente como un regalo.",
        "Un instante de belleza sin esfuerzo.",
        "La claridad matinal llena tu mirada.",
        "Un eco de inspiración te recorre.",
        "La luz comienza a bailar en tu entorno.",
        "Un suspiro suave renueva tu ánimo.",
        "La mañana brilla con promesas.",
        "Un murmullo interior te impulsa.",
        "La luz te envuelve con ternura.",
        "Un soplo de esperanza inunda el día.",
        "La mañana vibra con energía pura.",
        "Un instante de magia acompaña tu despertar.",
        "La claridad te da nueva perspectiva.",
        "Un eco de gratitud recorre el aire.",
        "La luz abre camino a tus sueños.",
        "Un susurro de amor por el día.",
        "La mañana se convierte en abrazo.",
        "Un murmullo de luz envuelve la estancia.",
        "La frescura matinal alimenta tu alma.",
        "Un soplo de serenidad antecede al día.",
        "La claridad pianifica tus ideas.",
        "Un instante de paz te acompaña.",
        "La mañana murmura dulces posibilidades.",
        "Un halo de energía sostiene lo invisible.",
        "La luz del día acaricia tu mente.",
        "Un susurro de calma envuelve el momento.",
        "La mañana se viste de optimismo.",
        "Un murmullo de ternura acaricia tu boca.",
        "La claridad te regala un segundo aire.",
        "Un soplo de gratitud impulsa tu jornada.",
        "La luz renueva tus fuerzas internas.",
        "Un instante de conexión con la vida.",
        "La mañana resuena con buenas vibras.",
        "Un halo de claridad envuelve tus pensamientos.",
        "La luz matutina pinta tus planes.",
        "Un susurro de posibilidad habita todo.",
        "La calma del día se asienta en ti.",
        "Un murmullo de luz renace en tu mirada.",
        "La claridad te conecta con lo auténtico.",
        "Un soplo de energía brinda nueva serenidad.",
        "La mañana respira contigo.",
        "Un instante de gratitud brota en tu pecho.",
        "La luz te acompaña en cada inspiración.",
        "Un susurro interior aviva la ilusión.",
        "La claridad matinal abre la mente.",
        "Un murmullo de ternura llena el ambiente.",
        "La mañana regala un momento de paz.",
        "Un halo de esperanza pone todo en calma.",
        "La luz suaviza tu entorno inmediato.",
        "Un soplo de calma precede tu acción.",
        "La claridad te da alas para empezar.",
        "Un susurro de belleza te envuelve.",
        "La mañana vibra con tu entusiasmo.",
        "Un murmullo interior acompaña tu andar.",
        "La luz te regala un nuevo aliento.",
        "Un instante de gratitud ilumina.",
        "La claridad abre caminos internos.",
        "Un halo de energía te invita a vivir.",
        "La luz matutina inspira tu día.",
        "Un susurro de calma te regala enfoque.",
        "La mañana se revela como compañera.",
        "Un murmullo interior impulsa tu despertar.",
        "La claridad empieza a fluir en ti.",
        "Un soplo de esperanza aviva tus ganas.",
        "La luz sostiene tu momento presente.",
        "Un instante de belleza te alegra.",
        "La mañana te entrega su mejor versión.",
        "Un susurro de paz acompaña tu primera taza.",
        "La claridad matutina guía tus pensamientos.",
        "Cada mañana trae una nueva página para escribir.",     
        "Justo un pensamiento positivo puede cambiar el día entero.", 
        "Abre los ojos a la belleza que te rodea.",                 
        "Cada amanecer pinta tu alma con esperanza renovada.",      
        "Despierta tu espíritu; el día espera tu brillo.",          
        "Cada día es una nueva oportunidad disfrazada de luz.",     
        "El silencio matinal contiene la paz que buscas.",          
        "Siembra hoy una sonrisa y cosecha alegría mañana.",        
        "Todo nuevo amanecer trae una promesa oculta.",             
        "Que tu luz interior compita con la del sol.",              
        "La mañana avanzada regala oportunidades sin fin.",         
        "Sé la energía que quieres ver reflejada alrededor.",       
        "En la quietud de la mañana, escucha tu corazón.",          
        "Cada aliento despierta una chispa de posibilidad.",        
        "Brilla hoy con un propósito valiente y sereno.",           
        "Con cada paso matutino, creas tu camino hacia lo grande.", 
        "El aroma de tus sueños flota en el aire mañanero.",        
        "El amanecer sigue sonriendo aunque no lo veas.",           
        "Hoy es la página 101 de tu gran historia.",                
        "Un suspiro de gratitud puede transformar tu jornada.",     
        "Entre luz y sombras, elige irradiar lo mejor de ti.",       
        "La mañana avanza, tu espíritu también debería hacerlo.",    
        "Despierta al brillo escondido dentro de ti.",               
        "Los rayos del cielo iluminan lo que te apasiona.",          
        "Transforma el aire de la mañana en energía para tu alma.",  
        "Que tu calma interior supere el bullicio del día.",         
        "El presente es tu lienzo más importante.",                  
        "Nace de nuevo en cada inhalación matutina.",                
        "El día te ofrece oportunidades, tómalas con fe.",           
        "Tu sonrisa puede cambiar el compás del mundo.",             
        "Riega tus sueños con la luz que ocupa el día.",             
        "Hoy es un nuevo capítulo: hazlo inolvidable.",              
        "Tu gratitud pinta la mañana con colores vivos.",            
        "Arranca el día con determinación y terminarás con orgullo.",
        "La armonía del día se construye en este instante.",         
        "Cree que el día puede sorprenderte; suele hacerlo.",          
        "Que el latido de tu corazón marque el ritmo del día.",      
        "Tu energía puede iluminar una mañana entera.",              
        "Empieza este tramo del día con mente serena y abierta.",    
        "En cada rayo ves la promesa de algo hermoso.",              
        "Deja que tu paz interior guíe tu próxima acción.",          
        "Tus sueños merecen luz: esta mañana es su refugio.",        
        "Siente la expansión de tu ser con cada inhalación.",        
        "El viento matinal trae consigo infinitas posibilidades.",   
        "Hoy reconecta con aquello que te hace vibrar.",             
        "Tu potencial se revela cuando decides brillar.",             
        "Respira agradecimiento y deja que todo fluya.",              
        "Eres la chispa que enciende una mañana entera.",             
        "Construye el resto del día con un acto de bondad.",          
        "Tu actitud define si el día será épico o común.",            
        "Deja que cada gesto cuente en esta mañana avanzada.",       
        "Suéltalo todo, respira y dale una nueva oportunidad al día.",
        "Tu presencia ilumina más que el sol de la mañana.",          
        "Haz de cada instante una obra de arte personal.",            
        "Inicia este tramo del día con la mirada centrada en lo bello.",
        "Cada paso que das en calma es una victoria íntima.",        
        "Que tu mente encuentre serenidad en este tramo del día.",   
        "Deja que la mañana sea testigo de tu mejor versión.",       
        "Encuentra el milagro en lo cotidiano de cada mañana.",      
        "Tu emoción positiva puede reescribir el día por completo.", 
        "Este pedazo de mañana es tu oportunidad para renacer.",     
        "Que la claridad te guíe en cada decisión matinal.",         
        "Respira paz y deja que el día se acomode a ti.",            
        "Hoy elige levantarte con gratitud y amor.",                 
        "El aire te regala frescura y posibilidad.",                 
        "Permítete brillar sin pedir permiso.",                      
        "Siente la magia que existe en este momento presente.",      
        "El calor de tu sonrisa puede calmar cualquier mañana.",     
        "Respira hondo; este instante define el día que vivirás.",   
        "Tus decisiones matinales siembran el resto de tu jornada.", 
        "Elige ver lo bueno; la mañana te recompensa con belleza.",   
        "Que tu luz interior sea también refugio para otros.",        
        "Esta parte del día es tu escalón para llegar a tus metas.", 
        "Respira inspiración y deja que todo concuerde.",             
        "Camina con intención; incluso los pequeños pasos importan.",  
        "Tu corazón sabe el camino, solo escucha su murmullo.",       
        "Deja que la luz te recuerde lo grande que eres capaz de ser.",
        "Siente la compañía silenciosa de la mañana avanzada.",       
        "Esta franja del día invita a crear, a soñar y a amar.",      
        "Haz de la calma tu mejor herramienta para avanzar.",         
        "Tu determinación es la chispa que enciende el día.",         
        "La gratitud transforma un día cualquiera en un día memorable.",
        "Sé el reflejo de la paz que deseas para el mundo.",          
        "Que tus sueños tengan alas esta mañana.",                   
        "Renace en este tramo entre el pasado y el futuro inmediato.",
        "La energía del día madura contigo, sin prisa.",             
        "Encuentra belleza en la simplicidad de este instante.",     
        "Que tu corazón se sienta tan ligero como el aire matutino.",
        "Respira la certeza de que hoy puede ser extraordinario.",
    ],
    // Mediodia
    middayPhrasesES : [
        "El sol llega a su punto más generoso.",
        "Un respiro pleno invita a recomponerse.",
        "La luz inunda el día con claridad.",
        "Cada momento puede ser un lienzo en blanco.",
        "El día se siente más ancho y luminoso.",
        "La energía del mediodía recorre el aire.",
        "Un instante para apreciar lo que eres capaz.",
        "La claridad del día llueve oportunidades.",
        "Silencio y luz te abrazan con fuerza.",
        "Tu sonrisa puede iluminar esta hora cálida.",
        "Un soplo de viento acaricia los sentidos.",
        "Este instante es un regalo de sol y calma.",
        "La vida palpita con intensidad en este punto.",
        "Un murmullo de inspiración te envuelve.",
        "La calma del medio día equilibra el alma.",
        "Una pausa para agradecer lo que tienes.",
        "El horizonte se muestra con su máxima luz.",
        "Tu día descubre el siguiente nivel.",
        "Un instante de brillo en plena plenitud.",
        "Energía y serenidad se mezclan en tu pecho.",
        "Un respirar consciente relaja y centra.",
        "La luz revela posibilidades ocultas.",
        "Todo parece más posible bajo este sol.",
        "Un momento para reconectar contigo.",
        "La claridad del mediodía inspira ideas.",
        "Tu espíritu danza con luz intensa.",
        "El aire cálido te susurra confianza.",
        "Un instante de respiro entre planes.",
        "La luz y el silencio dialogan suavemente.",
        "Haz una pausa y observa tu respiración.",
        "Este tramo del día te invita a crear.",
        "La energía palpita con claridad total.",
        "Un murmullo de gratitud fluye en ti.",
        "La calidez del día sostiene tus pasos.",
        "Un momento pleno de foco y calma.",
        "La luz del sol pinta tus metas.",
        "Silencio interior en plena claridad.",
        "La intensidad de la luz empodera el ánimo.",
        "Un respiro profundo para fortalecer el día.",
        "La claridad mental alcanza su cúspide.",
        "Un instante de conexión con lo esencial.",
        "La luz ofrece fuerza y belleza concentrada.",
        "Tu atención se despierta en este punto.",
        "Un soplo de calor para encender tus ideas.",
        "La calma y la energía convergen en ti.",
        "Un momento para agradecer tu camino.",
        "La armonía del día se siente al máximo.",
        "La luz revela lo que importa de verdad.",
        "Un instante para reencontrarte con tus sueños.",
        "La claridad del sol equilibra el alma.",
        "Un murmullo de confianza nace en tu interior.",
        "La plenitud del mediodía abraza tu ánimo.",
        "Un respiro para recargar tus intenciones.",
        "La luz descubre nuevas direcciones.",
        "Un momento para sembrar gratitud.",
        "La energía del día vibra en tu ser.",
        "Un instante para alinear mente y corazón.",
        "La calidez del sol acaricia tu espíritu.",
        "Un soplo de calma en medio del trajín.",
        "La luz del día es poesía sin palabras.",
        "Un espacio interior para mirarte a ti.",
        "La claridad del mediodía te sostiene.",
        "Un murmullo de paz vibra en el aire.",
        "La energía del sol despierta la acción.",
        "Un instante para agradecer y avanzar.",
        "La calidez del día renueva tus fuerzas.",
        "Un respiro para conectar con tu esencia.",
        "La luz intensa revela lo que llevas dentro.",
        "Un momento para fortalecer tus intenciones.",
        "La claridad mental alcanza su mejor versión.",
        "Un murmullo de esperanza envuelve tu pecho.",
        "La energía del día te impulsa hacia adelante.",
        "Un instante para reordenar tus pensamientos.",
        "La calidez del sol te llena de optimismo.",
        "Un respiro pausado antes de retomar rumbo.",
        "La luz del mediodía es fuerza concentrada.",
        "Un momento para honrar tu esfuerzo.",
        "La claridad del día alumbra tu propósito.",
        "Un murmullo de luz activa tu interior.",
        "La energía irradiada te impulsa con certeza.",
        "Un instante para agradecer lo recorrido.",
        "La calidez del día fortalece tus alas.",
        "Un respiro lleno de claridad y confianza.",
        "La luz revela el valor de lo que estás haciendo.",
        "Un momento para reencontrarte con tus metas.",
        "La claridad del mediodía inspira decisiones.",
        "Un murmullo de serenidad acompaña tu paso.",
        "La energía del día te envuelve en plenitud.",
        "Un instante para alinear corazón y acción.",
        "La calidez solar te recuerda tu capacidad.",
        "Un respiro para cultivar gratitud interior.",
        "La luz del día potencia tu determinación.",
        "Un momento para sentir tu fuerza interna.",
        "La claridad mental brilla en este tramo.",
        "Un murmullo de paz fortalece tu ánimo.",
        "La energía del mediodía te llena de foco.",
        "Un instante para agradecer y reconectar.",
        "La calidez del sol encarna tu pasión.",
        "Un respiro para centrar tus intenciones.",
        "La luz revela la belleza de lo cotidiano.",
        "Un momento para honrar tu compromiso.",
        "La claridad del día te da alas nuevas.",
        "Un murmullo de luz acompaña tus sentidos.",
        "La energía del mediodía guía tus pasos.",
        "Un instante para sembrar nuevas intenciones.",
        "La calidez del cielo abriga tu propósito.",
        "El sol abraza tu energía con ternura.",
        "Un instante de paz en medio del día.",
        "La luz intensa acaricia tus proyectos.",
        "Un respiro cálido para el alma.",
        "La energía del mediodía renueva tu impulso.",
        "Un momento para agradecer este día vibrante.",
        "La calidez del sol reconforta el espíritu.",
        "Un soplo de vitalidad recorre tu ser.",
        "La plenitud del día recarga tu ánimo.",
        "Un instante de conexión interior bajo la luz.",
        "La claridad del mediodía inspira nuevas ideas.",
        "Un murmullo de sol alimenta tus emociones.",
        "La luz despierta tu creatividad dormida.",
        "Un respiro suave entre acciones intensas.",
        "La calidez envuelve cada célula de tu cuerpo.",
        "Un momento para reconectar con tus intenciones.",
        "La energía del mediodía impulsa tu propósito.",
        "Un instante para recobrar tu centro.",
        "La luz del sol revela lo esencial.",
        "Un suspiro de calma en la mitad del día.",
        "La claridad te guía con firmeza y ternura.",
        "Un murmullo de gratitud ilumina tu entorno.",
        "La calidez del día nutre tu corazón.",
        "Un respiro lleno de claridad y equilibrio.",
        "La energía del mediodía potencia tu alma.",
        "Un instante para contemplar tus avances.",
        "La luz te inspira a continuar con pasión.",
        "Un soplo de serenidad en plena actividad.",
        "La plenitud del día llena tu espacio interior.",
        "Un momento alegre entre lo cotidiano.",
        "La calidez solar fortalece tu espíritu.",
        "Un respiro consciente para alinear tu mente.",
        "La claridad del sol avanza contigo.",
        "Un murmullo de paz llena tu pecho.",
        "La energía del día vibra en tu interior.",
        "Un instante de gratitud por lo vivido.",
        "La luz te acompaña en cada decisión.",
        "Un soplo de calma en medio de la rutina.",
        "La plenitud te envuelve con suavidad.",
        "Un momento para reflejar y recargar.",
        "La calidez del mediodía besa tu ánimo.",
        "Un respiro de creación bajo el sol.",
        "La claridad te impulsa hacia tus metas.",
        "Un murmullo de luz fortalece tu esencia.",
        "La energía del día se siente poderosa.",
        "Un instante de armonía en tu jornada.",
        "La luz te sostiene con delicadeza.",
        "Un soplo de gratitud ilumina tu paso.",
        "La plenitud del mediodía nutre tu ser.",
        "Un momento de conexión con lo auténtico.",
        "La calidez solar te inspira a seguir.",
        "Un respiro para reencontrarte contigo.",
        "La claridad del día despierta tu enfoque.",
        "Un murmullo de paz recorre tus pensamientos.",
        "La energía del mediodía vibra en tu sangre.",
        "Un instante de pausa con intención.",
        "La luz del sol pinta tu ser de optimismo.",
        "Un soplo de calma en medio del trajín.",
        "La plenitud del día se siente en el aire.",
        "Un momento para alinear cuerpo, mente y alma.",
        "La calidez del mediodía te regala plenitud.",
        "Un respiro para afinar tus intenciones.",
        "La claridad te fortalece en cada elección.",
        "Un murmullo de luz llena tu espacio interior.",
        "La energía del sol te envuelve de vida.",
        "Un instante de reconexión interna.",
        "La luz del mediodía acaricia tu propósito.",
        "Un soplo de serenidad te acompaña.",
        "La plenitud del día vibra en ti.",
        "Un momento para honrar tu recorrido.",
        "La calidez solar fortalece tu presencia.",
        "Un respiro vital en la mitad del día.",
        "La claridad del sol guía tu camino.",
        "Un murmullo de gratitud sustenta tu jornada.",
        "La energía del mediodía renueva tu impulso.",
        "Un instante de calma en la vorágine.",
        "La luz te inspira a brillar con transparencia.",
        "Un soplo de serenidad te renueva.",
        "La plenitud del día se filtra en tus días.",
        "Un momento para agradecer lo alcanzado.",
        "La calidez del sol acompaña tus pasos.",
        "Un respiro interior en medio del trajín.",
        "La claridad del mediodía reconoce tu valor.",
        "Un murmullo de paz revitaliza tu esencia.",
        "La energía del día pulsa en tu corazón.",
        "Un instante consciente de gratitud.",
        "La luz te abraza con suavidad.",
        "Un soplo de calma para nutrir tu espíritu.",
        "La plenitud del mediodía te inspira.",
        "Un momento para recobrar tu armonía.",
        "La calidez solar fortalece tu confianza.",
        "Un respiro lleno de claridad pura.",
        "La claridad te impulsa hacia nuevas metas.",
        "Un murmullo de luz sostiene tu esencia.",
        "La energía del sol vibra en tu ser.",
        "Un instante de reconexión plena.",
        "La luz del mediodía acaricia tu interior.",
        "Un soplo de serenidad ilumina tu ser.",
        "La plenitud del día recarga tu mente.",
        "Un momento para honrar tu camino.",
        "La calidez del sol te regala presencia.",
        "Un respiro vital fortalece tu ánimo.",
        "La claridad del mediodía guía tus pasos.",
        "Un murmullo de gratitud fluye en ti.",
        "La energía del día sostiene tu impulso.",
        "Un instante consciente de bienestar.",
        "La luz del sol acompaña tu crecimiento.",
        "Un soplo de calma eleva tu intención.",
        "La plenitud del mediodía nutre tu ser.",
        "Un momento para reconectar con tu esencia.",
        "La calidez solar inspira tu andar."
    ],
    // Tarde
    afternoonPhrasesES : [
        "La tarde te envuelve con su luz dorada.",
        "Un suspiro de sol suaviza el día.",
        "Esta franja del día invita a la reflexión.",
        "La luz se torna cálida y envolvente.",
        "Un murmullo de calma atraviesa el ambiente.",
        "La tarde acaricia tus pensamientos.",
        "Un instante para reconectar con el presente.",
        "La serenidad se esfuma en cada rayo.",
        "Un instante dorado para respirar profundo.",
        "La luz de la tarde pinta tus emociones.",
        "Un soplo de paz recorre tu esencia.",
        "La atmósfera susurra tranquilidad.",
        "Este tramo del día despierta la inspiración.",
        "La tarde trae consigo dulces promesas.",
        "Un murmullo sereno acompaña tu andar.",
        "La luz se hace más suave y reconfortante.",
        "Un instante para agradecer lo que eres.",
        "La tarde invita a la pausa consciente.",
        "Un abrazo cálido de luz te rodea.",
        "La calma del día encuentra su culmen.",
        "Un respiro para alinear tu interior.",
        "La luz se filtra con ternura tenue.",
        "Un silencio suave despierta tu intuición.",
        "La tarde resuena con una canción silenciosa.",
        "Un murmullo dorado llena el aire.",
        "La luz tibia fortalece tus ideas.",
        "Un instante para apreciar lo sencillo.",
        "La atmósfera se vuelve contemplativa.",
        "Un soplo de claridad ilumina tu mente.",
        "La tarde te abraza sin prisa.",
        "Un instante de gratitud en la luz templada.",
        "La luz se convierte en un refugio íntimo.",
        "Un murmullo suave te trae serenidad.",
        "La calma se difunde en cada rayo.",
        "Un respiro dorado reconforta el día.",
        "La tarde despliega su manto apacible.",
        "Un suspiro cálido inunda el ambiente.",
        "La luz dorada despierta la creatividad.",
        "Un instante para reconectar contigo.",
        "La tarde te regala su paz interna.",
        "Un murmullo tenue te envuelve.",
        "La luz se posa sobre tus pensamientos.",
        "Un respiro profundo te renueva.",
        "La tarde construye espacios de calma.",
        "Un instante para sembrar gratitud.",
        "La luz dibuja sombras tranquilas.",
        "Un soplo de inspiración te acaricia.",
        "La atmósfera vibra con armonía.",
        "Un murmullo de luz fortalece tu ser.",
        "La tarde equilibra tu energía.",
        "Un instante para afianzar tus sueños.",
        "La luz te invita a crear sin ruido.",
        "Un respiro consciente te respalda.",
        "La atmósfera late con serenidad.",
        "Un soplo de belleza habita este tramo.",
        "La tarde te susurra presencia plena.",
        "Un murmullo cálido fortalece tu alma.",
        "La luz se adhiere a tu serenidad.",
        "Un instante para crear desde el corazón.",
        "La tarde acaricia tus sentidos.",
        "Un respiro de gratitud te acompaña.",
        "La atmósfera se vuelve un refugio.",
        "Un soplo de calma anima tu ser.",
        "La luz te envuelve con suavidad.",
        "Un murmullo dorado armoniza tus ideas.",
        "La tarde consolida tu equilibrio interno.",
        "Un instante para honrar tu recorrido.",
        "La luz suaviza cada pensamiento.",
        "Un respiro vital fortalece tu ser.",
        "La atmósfera vibra con luz tranquilizadora.",
        "Un soplo de claridad ilumina tu esencia.",
        "La tarde te regala creatividad silenciosa.",
        "Un murmullo de gratitud resuena.",
        "La luz llena de ternura tu ánimo.",
        "Un instante de introspección suave.",
        "La atmósfera se vuelve pura contemplación.",
        "Un respiro para realinear tu energía.",
        "La tarde te abraza sin exigencia.",
        "Un soplo de esperanza recorre tus venas.",
        "La luz dorada embellece el instante.",
        "Un murmullo sereno calma tus preocupaciones.",
        "La tarde te ofrece su mejor versión.",
        "Un instante para saborear la quietud.",
        "La luz se filtra en tu interior.",
        "Un respiro consciente abraza tu mente.",
        "La atmósfera irradia luz reconfortante.",
        "Un soplo de paz recorre tu ser.",
        "La tarde se siente como un poema visual.",
        "Un murmullo de calma fortalece tu centro.",
        "La luz te guía hacia lo esencial.",
        "Un instante de conexión auténtica.",
        "La atmósfera te ofrece refugio interno.",
        "Un respiro de luz renueva tu impulso.",
        "La tarde te regala claridad serena.",
        "Un soplo de gratitud abraza tu día.",
        "La luz se posa suave sobre tu ánimo.",
        "Un instante para reafirmar tus propósitos.",
        "La atmósfera te envuelve en calma.",
        "Un murmullo interior despierta tu alma.",
        "La tarde vibra con un canto silencioso.",
        "Un respiro para valorar lo alcanzado.",
        "La luz te alimenta con plenitud.",
        "Un soplo de serenidad funda tu entorno.",
        "La atmósfera en calma late junto a ti.",
        "Un instante para sentir tu fuerza.",
        "La tarde resuena con secretos dorados.",
        "Un soplo de luz acaricia el ánimo.",
        "La calidez vespertina despierta tus sueños.",
        "Un instante para escuchar tu respiración.",
        "La tarde te envuelve en serenidad sutil.",
        "Un murmullo suave fortalece tu interior.",
        "La luz se adentra sin prisa en tu ser.",
        "Un respiro consciente reconecta el alma.",
        "La calma de la tarde contagia el ambiente.",
        "Un momento para sembrar silencio interior.",
        "La luz dorada apoya cada paso.",
        "Un instante de gratitud se filtra en ti.",
        "La tarde susurra una dulce confidencia.",
        "Un soplo de ternura envuelve tus sentidos.",
        "La atmósfera late con suavidad vespertina.",
        "Un respiro lento centra tu pensamiento.",
        "La tarde abraza el final del día.",
        "Un murmullo de calma te acompaña.",
        "La luz intensa desprende armonía interna.",
        "Un instante para reencontrarte con lo profundo.",
        "La quietud vespertina acaricia tu mente.",
        "Un soplo de inspiración recorre tu piel.",
        "La tarde se siente como un abrazo tibio.",
        "Un respiro para valorar lo alcanzado.",
        "La luz te regala un remanso de paz.",
        "Un momento para alinear cuerpo y mente.",
        "La tarde fluye con un ritmo apacible.",
        "Un murmullo interior alienta tu confianza.",
        "La luz dorada te impide apurarte.",
        "Un instante para agradecer este tramo.",
        "La atmósfera se tiñe de calma y dulzor.",
        "Un soplo de gratitud en cada exhalación.",
        "La tarde respira junto a tu silencio.",
        "Un respiro vespertino renueva energías.",
        "La luz se posa con suavidad en tu ánimo.",
        "Un instante para sentir tu corazón latir.",
        "La calma vespertina fortalece tu espíritu.",
        "Un murmullo sereno te guía.",
        "La tarde te protege en su manto cálido.",
        "Un respiro para reconectar con tu centro.",
        "La luz dorada envuelve tus pensamientos.",
        "Un momento de introspección acústica.",
        "La atmósfera vibra suave y constante.",
        "Un soplo de calma recorre tu conciencia.",
        "La tarde te ofrece un refugio interior.",
        "Un instante para revitalizar tu propósito.",
        "La luz vespertina sostiene tu equilibrio.",
        "Un murmullo de gratitud emerge.",
        "La tarde se presenta con nobleza.",
        "Un respiro para continuar con intención.",
        "La calma dorada reconforta tus pasos.",
        "Un momento para redefinir tu bienestar.",
        "La luz suave afina tu sensibilidad.",
        "Un soplo de claridad en tu interior.",
        "La tarde canta sin palabras.",
        "Un respiro consciente acompaña tu esencia.",
        "La atmósfera fluye con serenidad.",
        "Un instante para enfatizar tu presente.",
        "La luz dorada armoniza tus ideas.",
        "Un murmullo calmado nutre tu ánimo.",
        "La tarde embriaga tus sentidos.",
        "Un soplo de paz te reconforta.",
        "La tarde ilumina tu quietud.",
        "Un respiro profundo alinea tu ser.",
        "La luz vespertina invita a la reflexión.",
        "Un momento para agradecer este trayecto.",
        "La atmósfera susurra tranquilidad.",
        "Un instante para abrir el corazón.",
        "La luz dorada evoca ternura interna.",
        "Un soplo de calma fortalece tu interior.",
        "La tarde te cubre con su manto apacible.",
        "Un murmullo suave alienta tus pensamientos.",
        "La luz se filtra como abrazo silencioso.",
        "Un respiro esperado al llegar este tramo.",
        "La calma vespertina se vuelve presencia.",
        "Un instante para nutrir tu esencia.",
        "La atmósfera apacible transmite seguridad.",
        "Un soplo de inspiración ilumina tu senda.",
        "La tarde se siente como canción serena.",
        "Un respiro que ordena tus ideas.",
        "La luz se posa con delicadeza en ti.",
        "Un momento para estrechar la conexión interior.",
        "La tarde retoma el pulso del día.",
        "Un murmullo íntimo restaura el ánimo.",
        "La luz vespertina fortalece tu introspección.",
        "Un respiro manso acompaña tu reposo.",
        "La calma envuelve tu instante presente.",
        "Un soplo de gratitud te abraza.",
        "La tarde te regala claridad silenciosa.",
        "Un instante para contemplar tu energía.",
        "La atmósfera se carga de bondad.",
        "Un murmullo reconfortante llena el aire.",
        "La luz dorada te ancla al momento.",
        "Un respiro para cerrar este capítulo día.",
        "La tarde respira contigo en calma.",
        "Un soplo de belleza se revela.",
        "La luz embellece tu silencio interior.",
        "Un momento para valorar tu camino.",
        "La atmósfera se vuelve refugio interno.",
        "Un instante de paz te envuelve.",
        "La tarde resuena con tu esencia.",
        "Un murmullo suave descansa en tu pecho.",
        "La luz vespertina acompaña tu reflexión.",
        "Un respiro que calma el trajín.",
        "La calma te acompaña en este tramo.",
        "Un soplo de inspiración te sostiene.",
        "La tarde muestra su cara más amable.",
        "Un instante para agradecer lo aprendido.",
        "La atmósfera se abre ante tu mirada.",
        "Un murmullo de calma abraza tu corazón.",
        "La luz suave ilumina tu bienestar.",
        "Un respiro para completar tu jornada.",
        "La tarde vibra con esperanza silenciosa."
    ],
    // Atardecer
    sunsetPhrasesES : [
        "El cielo se derrama en tonos de fuego.",
        "Un suspiro de luz desciende en el horizonte.",
        "La calma vespertina pinta todo de oro.",
        "Un instante para encontrarte en la belleza.",
        "El sol se despide con un abrazo cálido.",
        "Un murmullo de gratitud tiñe la tarde.",
        "Los colores del ocaso acarician el alma.",
        "Un soplo de serenidad en cada reflejo.",
        "La tarde entona su canto en silencio.",
        "Un respiro para apreciar lo efímero.",
        "La atmósfera se viste de tonos suaves.",
        "Un instante donde el día se torna arte.",
        "El cielo flota en una paleta dorada.",
        "Un murmullo de calma atraviesa tu pecho.",
        "La luz descendente equilibra el ánimo.",
        "Un soplo de poesía en el crepúsculo.",
        "La tarde se convierte en un suave susurro.",
        "Un instante para agradecer este regalo.",
        "La calma del atardecer envuelve el ambiente.",
        "Un murmullo cálido nutre tus pensamientos.",
        "La luz se amansa al caer el día.",
        "Un soplo de nostalgia transforma el cielo.",
        "La tarde te acompaña en su plenitud.",
        "Un instante de introspección dorada.",
        "La atmósfera vibra en tonos crepusculares.",
        "Un murmullo suave te sostiene desde el cielo.",
        "La luz dorada perfila tus sueños.",
        "Un suspiro otoñal viste la tarde.",
        "La calma del ocaso llena tus sentidos.",
        "Un instantáneo refugio de paz y color.",
        "La tarde onírica aprieta tu respiración.",
        "Un soplo de luz apacigua la mente.",
        "La atmósfera reluce como pinceladas.",
        "Un murmullo vespertino nutre el interior.",
        "La tarde se hace escenario emocional.",
        "Un instante para reconectar con la paciencia.",
        "La luz se desliza dulcemente por el aire.",
        "Un soplo de calma sella el día.",
        "La calma del atardecer susurra al oído.",
        "Un murmullo dorado abraza tus sueños.",
        "La tarde florece en matices suaves.",
        "Un instante para saborear la ligereza.",
        "La atmósfera se expande con lentitud.",
        "Un murmullo íntimo acompaña el cielo.",
        "La luz suave te invita a contemplar.",
        "Un soplo de gratitud colorea el entorno.",
        "La tarde respira con refinada elegancia.",
        "Un instante para fundirte con la naturaleza.",
        "La serenidad vespertina aviva tus sentidos.",
        "Un murmullo dorado acuna el día.",
        "La luz del ocaso equilibra el ánimo.",
        "Un instante de belleza inesperada.",
        "La atmósfera se viste de calma dorada.",
        "Un suspiro vespertino acaricia el corazón.",
        "La tarde se hace canto sin palabras.",
        "Un soplo de luz afianza tu paz.",
        "La calma del crepúsculo te protege.",
        "Un instante para cerrar con gratitud.",
        "La luz bajada te envuelve suavemente.",
        "Un murmullo cálido llena tus pensamientos.",
        "La tarde se convierte en poema visual.",
        "Un soplo de serenidad te ampara.",
        "La atmósfera fluye con dulzura vespertina.",
        "Un instante de introspección luminosa.",
        "La luz dorada perfila tus ideas.",
        "Un murmullo de calma sostiene tu espíritu.",
        "La tarde te ofrece un refugio íntimo.",
        "Un soplo de gratitud recorre tu pecho.",
        "La serenidad del atardecer te abraza.",
        "Un instante para reconectar con tu esencia.",
        "La luz descendente te guía al receso.",
        "Un murmullo de luz firme tu interior.",
        "La tarde irradia un silencio reconfortante.",
        "Un soplo de paz habita en cada respiro.",
        "La atmósfera se torna poesía silenciosa.",
        "Un instante para agradecer el presente.",
        "La luz vespertina disuelve tu fatiga.",
        "Un murmullo dorado repara tu equilibrio.",
        "La tarde te envuelve con suaves matices.",
        "Un soplo de calma disuelve tensiones.",
        "La serenidad vespertina te reconecta.",
        "Un instante para nutrir tu tranquilidad.",
        "La luz bajada alumbra tu introspección.",
        "Un murmullo vespertino inspira calma.",
        "La tarde ofrece su abrazo dorado.",
        "Un soplo de gratitud madura tu calma.",
        "La atmósfera se adorna de silencio ligero.",
        "Un instante para fundirte con el día.",
        "La luz final perfila tus aspiraciones.",
        "Un murmullo suave acompaña tu ocaso.",
        "La tarde se convierte en espejo interior.",
        "Un soplo de serenidad te conecta al aquí.",
        "La calma vespertina te envuelve sin prisas.",
        "Un momento de plenitud y profundidad.",
        "La luz dorada afianza tu bienestar.",
        "Un murmullo interior sostiene tu ánimo.",
        "La tarde recoge lo mejor de tu día.",
        "Un soplo de gratitud acompaña el cierre.",
        "La atmósfera vespertina te invita al silencio.",
        "Un instante para alinear corazón y mente.",
        "La luz se despide embelleciendo el paisaje.",
        "Un murmullo dorado reaviva tu esencia.",
        "La tarde se sella con un suspiro cálido.",
        "Un soplo de calma despide el crepúsculo.",
        "La serenidad del ocaso reconforta tus pasos.",
        "Un instante para liberar tensiones.",
        "La luz vespertina cubre tus pensamientos.",
        "Un murmullo íntimo enmarca tu sonrisa.",
        "La tarde se extiende en su abrazo dorado.",
        "Un soplo de gratitud culmina el día.",
        "La atmósfera se vuelve testigo sereno.",
        "Un instante para agradecer y soltar.",
        "La luz descendente regala un adiós amable.",
        "Un murmullo suave termina el recorrido.",
        "La tarde ofrece su beso final de luz.",
        "Un soplo de calma acaricia el crepúsculo.",
        "La serenidad vespertina nutre tu interior."
    ],
    // Noche
    nightPhrasesES : [
        "La noche comienza a susurrar.",
        "El cielo se tiñe de azul profundo.",
        "Las estrellas despiertan lentamente.",
        "La luna se asoma tímidamente.",
        "El aire fresco acaricia la piel.",
        "Las luces de la ciudad parpadean como luciérnagas.",
        "Es hora de dejarse llevar por los sueños.",
        "El día se despide con un suspiro.",
        "La quietud de la noche invita a la reflexión.",
        "El silencio se convierte en compañía.",
        "Las sombras se alargan con elegancia.",
        "La noche se viste de gala.",
        "El cielo nocturno es un lienzo estrellado.",
        "La brisa nocturna trae consigo secretos.",
        "Las calles se vacían, pero la ciudad sigue viva.",
        "Es el momento perfecto para una taza de té.",
        "La oscuridad no es ausencia, sino presencia.",
        "Las estrellas cuentan historias antiguas.",
        "La luna llena ilumina el camino.",
        "La noche es joven y llena de promesas.",
        "Es hora de dejar que la mente vuele libre.",
        "La serenidad de la noche envuelve el alma.",
        "Las luces lejanas parecen susurrar canciones.",
        "La quietud nocturna es un bálsamo para el espíritu.",
        "Es el momento de soltar y descansar.",
        "La noche se convierte en un refugio acogedor.",
        "Las estrellas parecen más cerca que nunca.",
        "La luna llena refleja sueños olvidados.",
        "La ciudad duerme, pero los pensamientos despiertan.",
        "La noche es un poema sin palabras.",
        "Las sombras bailan al ritmo del viento.",
        "Es el instante perfecto para un abrazo silencioso.",
        "La oscuridad esconde belleza en cada rincón.",
        "Las luces de la ciudad son estrellas en la tierra.",
        "La noche invita a la calma y la introspección.",
        "Es hora de dejarse llevar por la música del alma.",
        "La luna llena refleja secretos compartidos.",
        "Las estrellas titilan como promesas lejanas.",
        "La noche es un lienzo en blanco para los sueños.",
        "Es el momento de cerrar los ojos y viajar.",
        "La oscuridad no es miedo, es misterio.",
        "Las luces de la ciudad son luciérnagas modernas.",
        "La noche es un refugio para los pensamientos profundos.",
        "Es hora de dejar que el corazón hable.",
        "La luna llena ilumina los caminos perdidos.",
        "Las estrellas son los ojos del universo.",
        "La noche es un suspiro del día.",
        "Es el momento de escuchar el silencio.",
        "La oscuridad esconde historias por contar.",
        "Las luces lejanas son faros en la distancia.",
        "La noche es el escenario de los sueños.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena es un espejo del alma.",
        "Las estrellas son las huellas del tiempo.",
        "La noche es un abrazo cálido y silencioso.",
        "Es el momento de dejarse llevar por la imaginación.",
        "La oscuridad esconde belleza en su interior.",
        "Las luces de la ciudad son estrellas atrapadas.",
        "La noche invita a la reflexión y el descanso.",
        "Es hora de dejar que el alma se relaje.",
        "La luna llena ilumina los secretos del corazón.",
        "Las estrellas son las risas del universo.",
        "La noche es un viaje sin mapas.",
        "Es el momento de soltar y descansar.",
        "La oscuridad esconde magia en su silencio.",
        "Las luces lejanas son sueños por cumplir.",
        "La noche es el refugio de los poetas.",
        "Es hora de dejar que los pensamientos fluyan.",
        "La luna llena refleja la belleza del alma.",
        "Las estrellas son las palabras del cielo.",
        "La noche es un lienzo para los sueños.",
        "Es el momento de cerrar los ojos y volar.",
        "La oscuridad esconde historias por descubrir.",
        "Las luces de la ciudad son estrellas en movimiento.",
        "La noche invita a la calma y la serenidad.",
        "Es hora de dejar que el corazón se exprese.",
        "La luna llena ilumina los deseos ocultos.",
        "Las estrellas son los suspiros del universo.",
        "La noche es un poema sin fin.",
        "Es el momento de escuchar el murmullo del viento.",
        "La oscuridad esconde belleza en su misterio.",
        "Las luces lejanas son recuerdos olvidados.",
        "La noche es el refugio de los sueños perdidos.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena refleja la luz interior.",
        "Las estrellas son las huellas de los dioses.",
        "La noche es un abrazo silencioso.",
        "Es el momento de dejarse llevar por la paz.",
        "La oscuridad esconde secretos por revelar.",
        "Las luces de la ciudad son estrellas fugaces.",
        "La noche invita a la reflexión y la calma.",
        "Es hora de dejar que el alma se relaje.",
        "La luna llena ilumina los caminos solitarios.",
        "Las estrellas son los ojos del cielo.",
        "La noche es un suspiro del día.",
        "Es el momento de escuchar el silencio.",
        "La oscuridad esconde historias por contar.",
        "Las luces lejanas son faros en la distancia.",
        "La noche es el escenario de los sueños.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena es un espejo del alma.",
        "Las estrellas son las huellas del tiempo.",
        "La noche es un abrazo cálido y silencioso.",
        "Es el momento de dejarse llevar por la imaginación.",
        "La oscuridad esconde belleza en su interior.",
        "Las luces de la ciudad son estrellas atrapadas.",
        "La noche invita a la reflexión y el descanso.",
        "Es hora de dejar que el alma se relaje.",
        "La luna llena ilumina los secretos del corazón.",
        "Las estrellas son las risas del universo.",
        "La noche es un viaje sin mapas.",
        "Es el momento de soltar y descansar.",
        "La oscuridad esconde magia en su silencio.",
        "Las luces lejanas son sueños por cumplir.",
        "La noche es el refugio de los poetas.",
        "Es hora de dejar que los pensamientos fluyan.",
        "La luna llena refleja la belleza del alma.",
        "Las estrellas son las palabras del cielo.",
        "La noche es un lienzo para los sueños.",
        "Es el momento de cerrar los ojos y volar.",
        "La oscuridad esconde historias por descubrir.",
        "Las luces de la ciudad son estrellas en movimiento.",
        "La noche invita a la calma y la serenidad.",
        "Es hora de dejar que el corazón se exprese.",
        "La luna llena ilumina los deseos ocultos.",
        "Las estrellas son los suspiros del universo.",
        "La noche es un poema sin fin.",
        "Es el momento de escuchar el murmullo del viento.",
        "La oscuridad esconde belleza en su misterio.",
        "Las luces lejanas son recuerdos olvidados.",
        "La noche es el refugio de los sueños perdidos.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena refleja la luz interior.",
        "Las estrellas son las huellas de los dioses.",
        "La noche es un abrazo silencioso.",
        "Es el momento de dejarse llevar por la paz.",
        "La oscuridad esconde secretos por revelar.",
        "Las luces de la ciudad son estrellas fugaces.",
        "La noche invita a la reflexión y la calma.",
        "Es hora de dejar que el alma se relaje.",
        "La luna llena ilumina los caminos solitarios.",
        "Las estrellas son los ojos del cielo.",
        "La noche es un suspiro del día.",
        "Es el momento de escuchar el silencio.",
        "La oscuridad esconde historias por contar.",
        "Las luces lejanas son faros en la distancia.",
        "La noche es el escenario de los sueños.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena es un espejo del alma.",
        "Las estrellas son las huellas del tiempo.",
        "La noche es un abrazo cálido y silencioso.",
        "Es el momento de dejarse llevar por la imaginación.",
        "La oscuridad esconde belleza en su interior.",
        "Las luces de la ciudad son estrellas atrapadas.",
        "La noche invita a la reflexión y el descanso.",
        "Es hora de dejar que el alma se relaje.",
        "La luna llena ilumina los secretos del corazón.",
        "Las estrellas son las risas del universo.",
        "La noche es un viaje sin mapas.",
        "Es el momento de soltar y descansar.",
        "La oscuridad esconde magia en su silencio.",
        "Las luces lejanas son sueños por cumplir.",
        "La noche es el refugio de los poetas.",
        "Es hora de dejar que los pensamientos fluyan.",
        "La luna llena refleja la belleza del alma.",
        "Las estrellas son las palabras del cielo.",
        "La noche es un lienzo para los sueños.",
        "Es el momento de cerrar los ojos y volar.",
        "La oscuridad esconde historias por descubrir.",
        "Las luces de la ciudad son estrellas en movimiento.",
        "La noche invita a la calma y la serenidad.",
        "Es hora de dejar que el corazón se exprese.",
        "La luna llena ilumina los deseos ocultos.",
        "Las estrellas son los suspiros del universo.",
        "La noche es un poema sin fin.",
        "Es el momento de escuchar el murmullo del viento.",
        "La oscuridad esconde belleza en su misterio.",
        "Las luces lejanas son recuerdos olvidados.",
        "La noche es el refugio de los sueños perdidos.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena refleja la luz interior.",
        "Las estrellas son las huellas de los dioses.",
        "La noche es un abrazo silencioso.",
        "Es el momento de dejarse llevar por la paz.",
        "La oscuridad esconde secretos por revelar.",
        "Las luces de la ciudad son estrellas fugaces.",
        "La noche invita a la reflexión y la calma.",
        "Es hora de dejar que el alma se relaje.",
        "La luna se asoma tímidamente.",
        "El silencio de la noche susurra secretos.",
        "Las estrellas titilan como suspiros lejanos.",
        "La oscuridad abraza con su manto cálido.",
        "El viento nocturno canta canciones olvidadas.",
        "Las sombras se alargan con elegancia.",
        "La ciudad duerme, pero los sueños despiertan.",
        "La noche es un lienzo en blanco para los pensamientos.",
        "La brisa nocturna acaricia el alma.",
        "La luna llena ilumina los rincones oscuros.",
        "Las estrellas son los ojos del universo.",
        "La quietud de la noche invita a la reflexión.",
        "El murmullo del viento es la voz de la noche.",
        "La oscuridad esconde historias por contar.",
        "Las luces lejanas parecen susurrar canciones.",
        "La noche es un poema sin palabras.",
        "Las sombras bailan al ritmo del viento.",
        "Es el instante perfecto para un abrazo silencioso.",
        "La oscuridad esconde belleza en cada rincón.",
        "Las luces de la ciudad parpadean como luciérnagas.",
        "La noche se viste de gala.",
        "El cielo nocturno es un lienzo estrellado.",
        "La brisa nocturna trae consigo secretos.",
        "Las calles se vacían, pero la ciudad sigue viva.",
        "Es el momento perfecto para una taza de té.",
        "La oscuridad no es ausencia, sino presencia.",
        "Las estrellas cuentan historias antiguas.",
        "La luna llena ilumina el camino.",
        "La noche es joven y llena de promesas.",
        "Es hora de dejar que la mente vuele libre.",
        "La serenidad de la noche envuelve el alma.",
        "Las luces lejanas parecen susurrar canciones.",
        "La quietud nocturna es un bálsamo para el espíritu.",
        "Es el momento de soltar y descansar.",
        "La noche se convierte en un refugio acogedor.",
        "Las estrellas parecen más cerca que nunca.",
        "La luna llena refleja sueños olvidados.",
        "La ciudad duerme, pero los pensamientos despiertan.",
        "La noche es un poema sin palabras.",
        "Las sombras bailan al ritmo del viento.",
        "Es el instante perfecto para un abrazo silencioso.",
        "La oscuridad esconde belleza en cada rincón.",
        "Las luces de la ciudad son estrellas en la tierra.",
        "La noche invita a la calma y la introspección.",
        "Es hora de dejarse llevar por la música del alma.",
        "La luna llena refleja secretos compartidos.",
        "Las estrellas titilan como promesas lejanas.",
        "La noche es un lienzo en blanco para los sueños.",
        "Es el momento de cerrar los ojos y viajar.",
        "La oscuridad no es miedo, es misterio.",
        "Las luces de la ciudad son luciérnagas modernas.",
        "La noche es un refugio para los pensamientos profundos.",
        "Es hora de dejar que el corazón hable.",
        "La luna llena ilumina los caminos perdidos.",
        "Las estrellas son los ojos del universo.",
        "La noche es un suspiro del día.",
        "Es el momento de escuchar el silencio.",
        "La oscuridad esconde historias por contar.",
        "Las luces lejanas son faros en la distancia.",
        "La noche es el escenario de los sueños.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena es un espejo del alma.",
        "Las estrellas son las huellas del tiempo.",
        "La noche es un abrazo cálido y silencioso.",
        "Es el momento de dejarse llevar por la imaginación.",
        "La oscuridad esconde belleza en su interior.",
        "Las luces de la ciudad son estrellas atrapadas.",
        "La noche invita a la reflexión y el descanso.",
        "Es hora de dejar que el alma se relaje.",
        "La luna llena ilumina los secretos del corazón.",
        "Las estrellas son las risas del universo.",
        "La noche es un viaje sin mapas.",
        "Es el momento de soltar y descansar.",
        "La oscuridad esconde magia en su silencio.",
        "Las luces lejanas son sueños por cumplir.",
        "La noche es el refugio de los poetas.",
        "Es hora de dejar que los pensamientos fluyan.",
        "La luna llena refleja la belleza del alma.",
        "Las estrellas son las palabras del cielo.",
        "La noche es un lienzo para los sueños.",
        "Es el momento de cerrar los ojos y volar.",
        "La oscuridad esconde historias por descubrir.",
        "Las luces de la ciudad son estrellas en movimiento.",
        "La noche invita a la calma y la serenidad.",
        "Es hora de dejar que el corazón se exprese.",
        "La luna llena ilumina los deseos ocultos.",
        "Las estrellas son los suspiros del universo.",
        "La noche es un poema sin fin.",
        "Es el momento de escuchar el murmullo del viento.",
        "La oscuridad esconde belleza en su misterio.",
        "Las luces lejanas son recuerdos olvidados.",
        "La noche es el refugio de los sueños perdidos.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena refleja la luz interior.",
        "Las estrellas son las huellas de los dioses.",
        "La noche es un abrazo silencioso.",
        "Es el momento de dejarse llevar por la paz.",
        "La oscuridad esconde secretos por revelar.",
        "Las luces de la ciudad son estrellas fugaces.",
        "La noche invita a la reflexión y la calma.",
        "Es hora de dejar que el alma se relaje.",
        "La luna llena ilumina los caminos solitarios.",
        "Las estrellas son los ojos del cielo.",
        "La noche es un suspiro del día.",
        "Es el momento de escuchar el silencio.",
        "La oscuridad esconde historias por contar.",
        "Las luces lejanas son faros en la distancia.",
        "La noche es el escenario de los sueños.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena es un espejo del alma.",
        "Las estrellas son las huellas del tiempo.",
        "La noche es un abrazo cálido y silencioso.",
        "Es el momento de dejarse llevar por la imaginación.",
        "La oscuridad esconde belleza en su interior.",
        "Las luces de la ciudad son estrellas atrapadas.",
        "La noche invita a la reflexión y el descanso.",
        "Es hora de dejar que el alma se relaje.",
        "La luna llena ilumina los secretos del corazón.",
        "Las estrellas son las risas del universo.",
        "La noche es un viaje sin mapas.",
        "Es el momento de soltar y descansar.",
        "La oscuridad esconde magia en su silencio.",
        "Las luces lejanas son sueños por cumplir.",
        "La noche es el refugio de los poetas.",
        "Es hora de dejar que los pensamientos fluyan.",
        "La luna llena refleja la belleza del alma.",
        "Las estrellas son las palabras del cielo.",
        "La noche es un lienzo para los sueños.",
        "Es el momento de cerrar los ojos y volar.",
        "La oscuridad esconde historias por descubrir.",
        "Las luces de la ciudad son estrellas en movimiento.",
        "La noche invita a la calma y la serenidad.",
        "Es hora de dejar que el corazón se exprese.",
        "La luna llena ilumina los deseos ocultos.",
        "Las estrellas son los suspiros del universo.",
        "La noche es un poema sin fin.",
        "Es el momento de escuchar el murmullo del viento.",
        "La oscuridad esconde belleza en su misterio.",
        "Las luces lejanas son recuerdos olvidados.",
        "La noche es el refugio de los sueños perdidos.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena refleja la luz interior.",
        "Las estrellas son las huellas de los dioses.",
        "La noche es un abrazo silencioso.",
        "Es el momento de dejarse llevar por la paz.",
        "La oscuridad esconde secretos por revelar.",
        "Las luces de la ciudad son estrellas fugaces.",
        "La noche invita a la reflexión y la calma.",
        "Es hora de dejar que el alma se relaje.",
        "La luna llena ilumina los caminos solitarios.",
        "Las estrellas son los ojos del cielo.",
        "La noche es un suspiro del día.",
        "Es el momento de escuchar el silencio.",
        "La oscuridad esconde historias por contar.",
        "Las luces lejanas son faros en la distancia.",
        "La noche es el escenario de los sueños.",
        "Es hora de dejar que la mente se libere.",
        "La luna llena es un espejo del alma.",
        "Las estrellas son las huellas del tiempo.",
        "La noche es un abrazo cálido y silencioso.",
        "Es el momento de dejarse llevar por la imaginación.",
        "La oscuridad esconde belleza en su interior.",
        "Las luces de la ciudad son estrellas atrapadas.",
        "La noche invita a la reflexión y el descanso.",
        "Es hora de dejar que el alma se relaje.",
        "La luna llena ilumina los secretos del corazón.",
        "Las estrellas son las risas del universo.",
        "La noche es un viaje sin mapas.",
        "Es el momento de soltar y descansar.",
        "La oscuridad esconde magia en su silencio.",
        "Las luces lejanas son sueños por cumplir.",
        "La noche es el refugio de los poetas.",
        "Es hora de dejar que los pensamientos fluyan.",
        "La luna llena refleja la belleza del alma.",
        "Las estrellas son las palabras del cielo.",
        "La noche es un lienzo para los sueños.",
        "Es el momento de cerrar los ojos y volar.",
        "La oscuridad esconde historias por descubrir.",
        "Las luces de la ciudad son estrellas en movimiento.",
        "La noche invita a la calma y la serenidad.",
        "Es hora de dejar que el corazón se exprese.",
        "La luna llena ilumina los deseos ocultos.",
        "Las estrellas son los suspiros del universo.",
        "La noche es un poema sin fin.",
        "Es el momento de escuchar el murmullo del viento.",
        "La oscuridad esconde belleza en su misterio.",
        "Las luces lejanas son recuerdos olvidados.",
        "La noche es el refugio de los sueños perdidos.",
        "La noche susurra secretos al oído del viento.",
        "El cielo nocturno es un lienzo de estrellas perdidas.",
        "La luna observa en silencio los sueños que nacen.",
        "La oscuridad acoge a los pensamientos errantes.",
        "Las estrellas titilan como suspiros olvidados.",
        "La madrugada es un susurro entre las sombras.",
        "El viento nocturno canta canciones lejanas.",
        "La luna llena ilumina los caminos solitarios.",
        "El silencio de la noche es un refugio para el alma.",
        "Las estrellas son los ojos del universo observando.",
        "La noche es un poema sin palabras.",
        "El murmullo del viento es la voz de la oscuridad.",
        "La luna refleja los sueños que aún no se han contado.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo nocturno es un mar de estrellas navegantes.",
        "La noche es un lienzo donde los sueños se pintan.",
        "El silencio de la madrugada es un canto profundo.",
        "Las estrellas son las joyas del manto nocturno.",
        "La luna llena es un faro en la oscuridad.",
        "La noche es un abrazo cálido y silencioso.",
        "Las sombras bailan al ritmo del viento nocturno.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana.",
        "La noche es un suspiro del universo.",
        "Las estrellas son las promesas del cielo.",
        "La luna llena es un espejo de la noche.",
        "El silencio de la madrugada es un canto profundo.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana.",
        "La noche es un suspiro del universo.",
        "Las estrellas son las promesas del cielo.",
        "La luna llena es un espejo de la noche.",
        "El silencio de la madrugada es un canto profundo.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana.",
        "La noche es un suspiro del universo.",
        "Las estrellas son las promesas del cielo.",
        "La luna llena es un espejo de la noche.",
        "El silencio de la madrugada es un canto profundo.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana.",
        "La noche es un suspiro del universo.",
        "Las estrellas son las promesas del cielo.",
        "La luna llena es un espejo de la noche.",
        "El silencio de la madrugada es un canto profundo.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana.",
        "La noche es un suspiro del universo.",
        "Las estrellas son las promesas del cielo.",
        "La luna llena es un espejo de la noche.",
        "El silencio de la madrugada es un canto profundo.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana.",
        "La noche es un suspiro del universo.",
        "Las estrellas son las promesas del cielo.",
        "La luna llena es un espejo de la noche.",
        "El silencio de la madrugada es un canto profundo.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana.",
        "La noche es un suspiro del universo.",
        "Las estrellas son las promesas del cielo.",
        "La luna llena es un espejo de la noche.",
        "El silencio de la madrugada es un canto profundo.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana.",
        "La noche es un suspiro del universo.",
        "Las estrellas son las promesas del cielo.",
        "La luna llena es un espejo de la noche.",
        "El silencio de la madrugada es un canto profundo.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana.",
        "La noche es un suspiro del universo.",
        "Las estrellas son las promesas del cielo.",
        "La luna llena es un espejo de la noche.",
        "El silencio de la madrugada es un canto profundo.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana.",
        "La noche es un suspiro del universo.",
        "Las estrellas son las promesas del cielo.",
        "La luna llena es un espejo de la noche.",
        "El silencio de la madrugada es un canto profundo.",
        "Las sombras se alargan como recuerdos perdidos.",
        "El cielo estrellado es un mapa de sueños perdidos.",
        "La luna observa en silencio los secretos del mundo.",
        "La oscuridad esconde historias por descubrir.",
        "Las estrellas son las huellas de los dioses en el cielo.",
        "La noche es un refugio para los pensamientos solitarios.",
        "El viento nocturno acaricia los recuerdos olvidados.",
        "La luna llena ilumina los caminos del alma errante.",
        "Las sombras se alargan como suspiros en la penumbra.",
        "El cielo nocturno es un espejo del alma humana."
    ]
}

export default collectionPhrasesES;