const collectionPhrasesIT = {
    // Amanecer
    dawnPhrasesIT : [
        "Il mattino sussurra promesse al vento.",
        "L'alba si risveglia con un sospiro di luce.",
        "Un balsamo dorato accarezza l'orizzonte.",
        "Il cielo si veste di morbidi acquerelli.",
        "Un mormorio di speranza viaggia nell'aria.",
        "Il silenzio lascia il posto alla luce timida.",
        "Il mondo si stira e sbadiglia a colori.",
        "L'aurora insegna la magia senza parole.",
        "Tutto rinasce in quel momento sacro.",
        "Un battito dorato dà inizio al giorno.",
        "La brezza mattutina porta nuovi inizi.",
        "Una poesia di luce nasce nel cielo.",
        "La penombra si arrende alla luce dorata.",
        "Un sussurro caldo risveglia la terra.",
        "L'orizzonte si illumina di calma.",
        "Una melodia silenziosa governa l'alba.",
        "Il cielo respira in toni pastello.",
        "La vita fa capolino da dietro il velo della notte.",
        "Il sole alza il suo primo timido saluto.",
        "La speranza si filtra attraverso ogni raggio.",
        "Il mondo si risveglia in mormorii dorati.",
        "Un momento eterno bagnato di luce.",
        "L'aurora dipinge le sue prime linee.",
        "Un abbraccio di luce copre il mattino.",
        "Il giorno inizia con un caldo sospiro.",
        "Una tela di calma si dispiega.",
        "La chiarezza si insinua nell'aria fresca.",
        "Un canto silenzioso annuncia il giorno.",
        "L'essenza dell'alba riempie l'anima.",
        "Il cielo rivela il suo volto pacifico.",
        "Un mormorio dorato culla l'orizzonte.",
        "La promessa di un nuovo capitolo vibra.",
        "L'aria vibra di toni di speranza.",
        "Sussurri di luce accarezzano la penombra.",
        "L'aurora si risveglia con morbidezza.",
        "Un alone dorato avvolge la terra.",
        "Ogni mattina rinasce una nuova possibilità.",
        "Il silenzio dell'alba sussurra vita.",
        "Una carezza di sole si fa strada lentamente.",
        "La notte si dissolve con dolcezza.",
        "Un leggero barlume bacia il cielo.",
        "L'aurora abbraccia il silenzio notturno.",
        "Un verso di luce è recitato dall'orizzonte.",
        "La freschezza dell'alba riempie i polmoni.",
        "Un'aria nuova porta la promessa.",
        "La calma prima del battito del giorno.",
        "Un soffio di luce viaggia senza fretta.",
        "L'atmosfera vibra di toni morbidi.",
        "Un cielo nascente offre serenità.",
        "Il mondo si risveglia in un sussurro.",
        "Una carezza dell'alba penetra l'anima.",
        "Lo spazio si riempie di luce delicata.",
        "L'alba scrive poesie senza inchiostro.",
        "Un bacio di sole risveglia la calma.",
        "L'aurora apre le sue ali viola.",
        "Il giorno inizia con un gesto di pace.",
        "Un caldo sospiro sulla brughiera addormentata.",
        "La luce danza nella nebbia del mattino.",
        "Un morbido crescendo di chiarezza.",
        "Il sole mormora il suo buongiorno.",
        "L'aurora riversa il suo oro tiepido.",
        "Un palcoscenico di calma e colore.",
        "L'orizzonte respira in calma.",
        "Una poesia visiva nasce nel cielo.",
        "La freschezza scivola attraverso ogni finestra.",
        "L'aurora dispiega le sue morbide ali.",
        "Un momento di eternità all'alba.",
        "La promessa della luce si può sentire.",
        "L'aria del mattino sa di speranza.",
        "Un risveglio nella calma e nella luce.",
        "Il giorno si annuncia senza fretta.",
        "Una carezza solare per l'anima.",
        "La penombra si arrende lentamente.",
        "Un canto senza voce avvolge il mondo.",
        "L'aurora soffia con dolcezza.",
        "Un barlume dà inizio al battito del giorno.",
        "Il mattino regala il suo primo respiro.",
        "Un bacio dorato ravviva i sensi.",
        "La promessa del giorno viene disegnata.",
        "Un sospiro di colore apre gli occhi.",
        "Il sole fa capolino con rispetto.",
        "La calma è adornata di luce.",
        "Un alone caldo tocca il paesaggio.",
        "Il mattino si dispiega in silenzio.",
        "Un mormorio luminoso inonda l'aria.",
        "L'aurora canta senza parole.",
        "Un abbraccio pacifico al risveglio.",
        "La bellezza nasce senza clamore.",
        "Un momento di pura serenità.",
        "L'aurora sboccia nel cielo.",
        "L'alba scrive il suo proprio inno.",
        "La luce danza nella calma.",
        "Un sussurro di colori tenui.",
        "Il mattino indossa il suo nuovo manto.",
        "Una promessa in ogni folata.",
        "La penombra si fonde nell'oro.",
        "Nasce un mormorio di giorno.",
        "L'aurora esala pace.",
        "Un battito silenzioso si risveglia.",
        "La luce veste il mondo d'alba.",
        "Un bacio d'aurora risveglia gli spiriti.",
        "Il mattino respira senza fretta.",
        "Un'alba dal tocco morbido.",
        "L'aurora accarezza il silenzio.",
        "Un alone dorato bacia il giorno.",
        "Un momento tinto di calma.",
        "La luce sussurra nella penombra.",
        "Un canto senza note annuncia il giorno.",
        "Il mattino danza senza suono.",
        "L'aurora nasce con delicatezza.",
        "Un mormorio caldo si risveglia.",
        "La luce avvolge l'orizzonte.",
        "Un sospiro dorato si espande.",
        "L'aurora offre il suo manto.",
        "Un momento in cui tutto è possibile.",
        "Il mattino fa capolino nella calma.",
        "Un verso di luce viaggia attraverso il cielo.",
        "La penombra si trasforma in speranza.",
        "Un mormorio d'aurora avvolge.",
        "La calma dell'alba ti abbraccia.",
        "Un bacio caldo risveglia i sensi.",
        "L'aurora respira serenità.",
        "Un momento dorato di pace.",
        "La luce tocca l'anima.",
        "Un sussurro mattutino culla.",
        "Il mattino nasce tra i sussurri.",
        "Un alone di calma si estende.",
        "L'aurora accarezza senza fretta.",
        "Un morbido barlume riempie l'aria.",
        "La luce ti invita a sorridere.",
        "Un momento d'oro nel mattino.",
        "L'aurora si riflette nei tuoi occhi.",
        "Un mormorio di calma ti avvolge.",
        "Il mattino esordisce con la luce.",
        "Un sospiro dorato abita il cielo.",
        "L'aurora sussurra al cuore.",
        "Un momento senza rumore, solo luce.",
        "La luce ti risveglia con tenerezza.",
        "Un alone di speranza all'alba.",
        "L'aurora ti abbraccia dolcemente.",
        "Un mormorio dorato percorre il giorno.",
        "Il mattino inizia nella calma.",
        "Un momento d'amore al risveglio.",
        "La luce veste l'orizzonte di pace.",
        "Un sussurro d'aurora riposa l'anima.",
        "L'aurora ti regala un nuovo canto.",
        "Un alone di luce danza con te.",
        "Il mattino è una poesia vivente.",
        "Un momento eterno di serenità.",
        "L'aurora ti invita a rinascere."
    ],
    // Mañana
    dayPhrasesIT : [
        "Il giorno inizia con un sussurro di luce.",
        "Il mattino è vestito di toni morbidi.",
        "Un soffio di speranza viaggia nell'aria.",
        "La chiarezza inonda i sensi.",
        "Un momento di pace inonda ogni cosa.",
        "L'energia del giorno risveglia i tuoi sogni.",
        "Il mondo si stira nella calma e nel colore.",
        "Un canto interiore annuncia l'alba.",
        "La brezza mattutina ti sussurra promesse.",
        "L'atmosfera vibra di ottimismo.",
        "Risveglia l'anima con una melodia soave.",
        "La luce del giorno canta in silenzio.",
        "I raggi delicati accarezzano la pelle.",
        "Il giorno esordisce con delicatezza.",
        "Una tela bianca ti invita a creare.",
        "Ogni respiro mattutino è un rinnovamento.",
        "Il mattino brilla di serenità.",
        "Un abbraccio di luce illumina l'anima.",
        "L'alba lascia una scia di tenerezza.",
        "La chiarezza ti avvolge nella calma.",
        "Un mormorio di pace dà inizio al giorno.",
        "La freschezza mattutina riempie i polmoni.",
        "Un sussurro dorato risveglia lo spirito.",
        "La speranza sboccia con la luce.",
        "Il mattino ti invita a sognare ad occhi aperti.",
        "Il giorno si presenta con dolcezza.",
        "La luce del primo mattino abbraccia i sensi.",
        "Il silenzio e la luce conversano.",
        "Un alone di energia inonda il giorno.",
        "Il mattino danza in una calma dorata.",
        "Si accende un momento di gratitudine.",
        "La brezza leggera accarezza la mente.",
        "Un lampo di chiarezza ravviva.",
        "Il mattino sembra un abbraccio.",
        "Un soffio di vita scorre nelle tue vene.",
        "La luce del mattino ti dà speranza.",
        "Una poesia senza parole emerge all'alba.",
        "Il mattino ti invita a respirare profondamente.",
        "Un momento di bellezza ti avvolge.",
        "La luce soffusa ti risveglia con dolcezza.",
        "Inizia un mormorio di ispirazione.",
        "Il giorno offre una nuova opportunità.",
        "La chiarezza mattutina purifica lo spirito.",
        "Un occhiolino di luce segna l'inizio.",
        "L'energia del sole ti avvolge.",
        "Un'aria fresca ti scorre sulla pelle.",
        "Il mattino dispiega la sua magia.",
        "Un canto silenzioso richiama la tua attenzione.",
        "La luce si insinua in ogni angolo.",
        "Un sospiro di calma abita l'ambiente.",
        "La gentilezza del giorno si mostra per prima.",
        "Un'aura di ottimismo emerge dolcemente.",
        "Il mattino ci regala un nuovo capitolo.",
        "Un mormorio interiore alimenta la passione.",
        "La luce aumenta la tua chiarezza mentale.",
        "Un soffio di luce guida la tua mente.",
        "Il mattino si offre con generosità.",
        "Un sussurro di amor proprio risuona.",
        "La chiarezza ti dà fiducia.",
        "Un momento di gratitudine apre il giorno.",
        "La luce soffusa ispira i tuoi passi.",
        "Un'eco di serenità invade l'ambiente.",
        "Il mattino celebra le piccole cose.",
        "Un alone di freschezza permea ogni cosa.",
        "La calma mattutina si intreccia nei tuoi sensi.",
        "Un sussurro di luce dà il benvenuto.",
        "Il mattino distilla energia rinnovata.",
        "Un mormorio dorato ti accompagna.",
        "La luce annuncia la possibilità.",
        "Un soffio di ottimismo rischiara il giorno.",
        "Il mattino sembra un dono.",
        "Un momento di bellezza senza sforzo.",
        "La chiarezza mattutina riempie il tuo sguardo.",
        "Un'eco di ispirazione ti percorre.",
        "La luce inizia a danzare nel tuo ambiente.",
        "Un sospiro leggero rinnova il tuo spirito.",
        "Il mattino brilla di promesse.",
        "Un mormorio interiore ti spinge.",
        "La luce ti avvolge con tenerezza.",
        "Un soffio di speranza inonda il giorno.",
        "Il mattino vibra di energia pura.",
        "Un momento di magia accompagna il tuo risveglio.",
        "La chiarezza ti dà una nuova prospettiva.",
        "Un'eco di gratitudine viaggia nell'aria.",
        "La luce apre la strada ai tuoi sogni.",
        "Un sussurro d'amore per il giorno.",
        "Il mattino diventa un abbraccio.",
        "Un mormorio di luce avvolge la stanza.",
        "La freschezza mattutina nutre la tua anima.",
        "Un soffio di serenità precede il giorno.",
        "La chiarezza organizza le tue idee.",
        "Un momento di pace ti accompagna.",
        "Il mattino mormora dolci possibilità.",
        "Un alone di energia sostiene l'invisibile.",
        "La luce del giorno accarezza la tua mente.",
        "Un sussurro di calma avvolge il momento.",
        "Il mattino si veste di ottimismo.",
        "Un mormorio di tenerezza accarezza la tua bocca.",
        "La chiarezza ti dà nuovo slancio.",
        "Un soffio di gratitudine alimenta il tuo viaggio.",
        "La luce rinnova la tua forza interiore.",
        "Un momento di connessione con la vita.",
        "Il mattino risuona di buone vibrazioni.",
        "Un alone di chiarezza avvolge i tuoi pensieri.",
        "La luce del mattino dipinge i tuoi piani.",
        "Un sussurro di possibilità abita ogni cosa.",
        "La calma del giorno si posa in te.",
        "Un mormorio di luce rinasce nel tuo sguardo.",
        "La chiarezza ti connette con ciò che è autentico.",
        "Un soffio di energia dona nuova serenità.",
        "Il mattino respira con te.",
        "Un momento di gratitudine germoglia nel tuo petto.",
        "La luce ti accompagna in ogni respiro.",
        "Un sussurro interiore alimenta l'illusione.",
        "La chiarezza mattutina apre la mente.",
        "Un mormorio di tenerezza riempie l'ambiente.",
        "Il mattino offre un momento di pace.",
        "Un alone di speranza placa ogni cosa.",
        "La luce ammorbidisce il tuo ambiente immediato.",
        "Un soffio di calma precede la tua azione.",
        "La chiarezza ti dà le ali per iniziare.",
        "Un sussurro di bellezza ti avvolge.",
        "Il mattino vibra con il tuo entusiasmo.",
        "Un mormorio interiore accompagna il tuo cammino.",
        "La luce ti dà un nuovo respiro.",
        "Un momento di gratitudine illumina.",
        "La chiarezza apre sentieri interiori.",
        "Un alone di energia ti invita a vivere.",
        "La luce del mattino ispira la tua giornata.",
        "Un sussurro di calma ti dà concentrazione.",
        "Il mattino si rivela come un compagno.",
        "Un mormorio interiore guida il tuo risveglio.",
        "La chiarezza inizia a scorrere dentro di te.",
        "Un soffio di speranza alimenta il tuo desiderio.",
        "La luce sostiene il tuo momento presente.",
        "Un momento di bellezza ti rallegra.",
        "Il mattino ti offre la sua versione migliore.",
        "Un sussurro di pace accompagna la tua prima tazza.",
        "La chiarezza mattutina guida i tuoi pensieri.",
        "Ogni mattina porta una nuova pagina da scrivere.",
        "Un solo pensiero positivo può cambiare l'intera giornata.",
        "Apri gli occhi alla bellezza che ti circonda.",
        "Ogni alba dipinge la tua anima di speranza rinnovata.",
        "Risveglia il tuo spirito; il giorno attende il tuo splendore.",
        "Ogni giorno è una nuova opportunità mascherata da luce.",
        "Il silenzio del mattino custodisce la pace che cerchi.",
        "Semina un sorriso oggi e raccogli gioia domani.",
        "Ogni nuova alba porta una promessa nascosta.",
        "Possa la tua luce interiore competere con quella del sole.",
        "La tarda mattinata offre infinite opportunità.",
        "Sii l'energia che vuoi vedere riflessa intorno a te.",
        "Nella quiete del mattino, ascolta il tuo cuore.",
        "Ogni respiro risveglia una scintilla di possibilità.",
        "Brilla oggi con uno scopo coraggioso e sereno.",
        "Con ogni passo mattutino, crei il tuo sentiero verso la grandezza.",
        "Il profumo dei tuoi sogni fluttua nell'aria del mattino.",
        "L'alba continua a sorridere anche se non la vedi.",
        "Oggi è la pagina 101 della tua grande storia.",
        "Un sospiro di gratitudine può trasformare il tuo viaggio.",
        "Tra luce e ombre, scegli di irradiare il meglio di te.",
        "Il mattino avanza, anche il tuo spirito dovrebbe farlo.",
        "Risvegliati allo splendore nascosto dentro di te.",
        "I raggi del cielo illuminano ciò che ti appassiona.",
        "Trasforma l'aria del mattino in energia per la tua anima.",
        "Possa la tua calma interiore superare il trambusto del giorno.",
        "Il presente è la tua tela più importante.",
        "Rinasci ad ogni inspirazione mattutina.",
        "Il giorno ti offre opportunità, coglile con fede.",
        "Il tuo sorriso può cambiare il ritmo del mondo.",
        "Innaffia i tuoi sogni con la luce che riempie il giorno.",
        "Oggi è un nuovo capitolo: rendilo indimenticabile.",
        "La tua gratitudine dipinge il mattino con colori vivaci.",
        "Inizia la giornata con determinazione e finirai con orgoglio.",
        "L'armonia del giorno si costruisce in questo istante.",
        "Credi che il giorno possa sorprenderti; di solito lo fa.",
        "Lascia che il battito del tuo cuore scandisca il ritmo del giorno.",
        "La tua energia può illuminare un'intera mattinata.",
        "Inizia questa parte della giornata con una mente calma e aperta.",
        "In ogni raggio, vedi la promessa di qualcosa di bello.",
        "Lascia che la tua pace interiore guidi la tua prossima azione.",
        "I tuoi sogni meritano luce: questo mattino è il loro rifugio.",
        "Senti l'espansione del tuo essere ad ogni inspirazione.",
        "Il vento del mattino porta con sé infinite possibilità.",
        "Oggi, riconnettiti con ciò che ti fa vibrare.",
        "Il tuo potenziale si rivela quando decidi di brillare.",
        "Respira gratitudine e lascia che tutto fluisca.",
        "Tu sei la scintilla che accende un'intera mattinata.",
        "Costruisci il resto della giornata con un atto di gentilezza.",
        "Il tuo atteggiamento definisce se la giornata sarà epica o comune.",
        "Lascia che ogni gesto conti in questa tarda mattinata.",
        "Lascia andare tutto, respira e dai una nuova possibilità al giorno.",
        "La tua presenza brilla più del sole del mattino.",
        "Fa' di ogni momento un'opera d'arte personale.",
        "Inizia questa parte della giornata con lo sguardo concentrato sul bello.",
        "Ogni passo che fai nella calma è una vittoria intima.",
        "Possa la tua mente trovare serenità in questa parte della giornata.",
        "Lascia che il mattino sia testimone della tua versione migliore.",
        "Trova il miracolo nel quotidiano di ogni mattina.",
        "La tua emozione positiva può riscrivere completamente la giornata.",
        "Questo pezzo di mattino è la tua occasione per rinascere.",
        "Possa la chiarezza guidarti in ogni decisione mattutina.",
        "Respira pace e lascia che il giorno si adatti a te.",
        "Oggi, scegli di alzarti con gratitudine e amore.",
        "L'aria ti regala freschezza e possibilità.",
        "Permettiti di brillare senza chiedere il permesso.",
        "Senti la magia che esiste in questo momento presente.",
        "Il calore del tuo sorriso può calmare qualsiasi mattinata.",
        "Respira profondamente; questo istante definisce il giorno che vivrai.",
        "Le tue decisioni mattutine seminano il resto della tua giornata.",
        "Scegli di vedere il buono; il mattino ti ricompensa con la bellezza.",
        "Possa la tua luce interiore essere anche un rifugio per gli altri.",
        "Questa parte della giornata è il tuo gradino per raggiungere i tuoi obiettivi.",
        "Respira ispirazione e lascia che tutto si allinei.",
        "Cammina con intenzione; anche i piccoli passi contano.",
        "Il tuo cuore conosce la strada, ascolta solo il suo mormorio.",
        "Lascia che la luce ti ricordi quanto puoi essere grande.",
        "Senti la compagnia silenziosa della tarda mattinata.",
        "Questo tratto di giornata ti invita a creare, a sognare e ad amare.",
        "Fa' della calma il tuo miglior strumento per andare avanti.",
        "La tua determinazione è la scintilla che accende il giorno.",
        "La gratitudine trasforma un giorno qualunque in un giorno memorabile.",
        "Sii il riflesso della pace che desideri per il mondo.",
        "Possano i tuoi sogni avere le ali questa mattina.",
        "Rinasci in questo tratto tra il passato e il futuro immediato.",
        "L'energia del giorno matura con te, senza fretta.",
        "Trova la bellezza nella semplicità di questo istante.",
        "Possa il tuo cuore sentirsi leggero come l'aria del mattino.",
        "Respira la certezza che oggi può essere straordinario."
    ],
    // Mediodia
    middayPhrasesIT : [
        "Il sole raggiunge il suo punto più generoso.",
        "Un respiro profondo ti invita a raccoglierti.",
        "La luce inonda il giorno di chiarezza.",
        "Ogni momento può essere una tela bianca.",
        "Il giorno sembra più ampio e luminoso.",
        "L'energia del mezzogiorno viaggia nell'aria.",
        "Un momento per apprezzare ciò di cui sei capace.",
        "La chiarezza del giorno fa piovere opportunità.",
        "Il silenzio e la luce ti abbracciano forte.",
        "Il tuo sorriso può illuminare quest'ora calda.",
        "Un soffio di vento accarezza i sensi.",
        "Questo momento è un dono di sole e calma.",
        "La vita pulsa con intensità a questo punto.",
        "Un mormorio di ispirazione ti avvolge.",
        "La calma del mezzogiorno equilibra l'anima.",
        "Una pausa per essere grati di ciò che si ha.",
        "L'orizzonte si mostra nella sua massima luce.",
        "La tua giornata scopre il livello successivo.",
        "Un momento di splendore in piena pienezza.",
        "Energia e serenità si mescolano nel tuo petto.",
        "Un respiro consapevole rilassa e centra.",
        "La luce rivela possibilità nascoste.",
        "Tutto sembra più possibile sotto questo sole.",
        "Un momento per riconnetterti con te stesso.",
        "La chiarezza del mezzogiorno ispira idee.",
        "Il tuo spirito danza con una luce intensa.",
        "L'aria calda ti sussurra fiducia.",
        "Un momento di tregua tra i piani.",
        "Luce e silenzio dialogano dolcemente.",
        "Fai una pausa e osserva il tuo respiro.",
        "Questo tratto di giornata ti invita a creare.",
        "L'energia pulsa con totale chiarezza.",
        "Un mormorio di gratitudine scorre dentro di te.",
        "Il calore del giorno sostiene i tuoi passi.",
        "Un momento pieno di concentrazione e calma.",
        "La luce del sole dipinge i tuoi obiettivi.",
        "Silenzio interiore in piena chiarezza.",
        "L'intensità della luce dà forza allo spirito.",
        "Un respiro profondo per rafforzare la giornata.",
        "La chiarezza mentale raggiunge il suo apice.",
        "Un momento di connessione con l'essenziale.",
        "La luce offre forza e bellezza concentrate.",
        "La tua attenzione si risveglia a questo punto.",
        "Un soffio di calore per accendere le tue idee.",
        "Calma ed energia convergono in te.",
        "Un momento per essere grati del tuo cammino.",
        "L'armonia del giorno si sente al massimo.",
        "La luce rivela ciò che conta davvero.",
        "Un momento per riconnetterti con i tuoi sogni.",
        "La chiarezza del sole equilibra l'anima.",
        "Un mormorio di fiducia nasce dentro di te.",
        "La pienezza del mezzogiorno abbraccia il tuo spirito.",
        "Un respiro per ricaricare le tue intenzioni.",
        "La luce scopre nuove direzioni.",
        "Un momento per seminare gratitudine.",
        "L'energia del giorno vibra nel tuo essere.",
        "Un momento per allineare mente e cuore.",
        "Il calore del sole accarezza il tuo spirito.",
        "Un soffio di calma in mezzo al trambusto.",
        "La luce del giorno è poesia senza parole.",
        "Uno spazio interiore per guardare te stesso.",
        "La chiarezza del mezzogiorno ti sostiene.",
        "Un mormorio di pace vibra nell'aria.",
        "L'energia del sole risveglia l'azione.",
        "Un momento per essere grati e andare avanti.",
        "Il calore del giorno rinnova le tue forze.",
        "Un respiro per connetterti con la tua essenza.",
        "La luce intensa rivela ciò che porti dentro.",
        "Un momento per rafforzare le tue intenzioni.",
        "La chiarezza mentale raggiunge la sua versione migliore.",
        "Un mormorio di speranza avvolge il tuo petto.",
        "L'energia del giorno ti spinge in avanti.",
        "Un momento per riordinare i tuoi pensieri.",
        "Il calore del sole ti riempie di ottimismo.",
        "Un respiro pacato prima di riprendere il cammino.",
        "La luce del mezzogiorno è forza concentrata.",
        "Un momento per onorare il tuo sforzo.",
        "La chiarezza del giorno illumina il tuo scopo.",
        "Un mormorio di luce attiva il tuo io interiore.",
        "L'energia irradiata ti spinge con certezza.",
        "Un momento per essere grati del viaggio finora.",
        "Il calore del giorno rafforza le tue ali.",
        "Un respiro pieno di chiarezza e fiducia.",
        "La luce rivela il valore di ciò che stai facendo.",
        "Un momento per riconnetterti con i tuoi obiettivi.",
        "La chiarezza del mezzogiorno ispira decisioni.",
        "Un mormorio di serenità accompagna il tuo passo.",
        "L'energia del giorno ti avvolge in pienezza.",
        "Un momento per allineare cuore e azione.",
        "Il calore solare ti ricorda le tue capacità.",
        "Un respiro per coltivare la gratitudine interiore.",
        "La luce del giorno accresce la tua determinazione.",
        "Un momento per sentire la tua forza interiore.",
        "La chiarezza mentale brilla in questo tratto.",
        "Un mormorio di pace rafforza il tuo spirito.",
        "L'energia del mezzogiorno ti riempie di concentrazione.",
        "Un momento per essere grati e riconnettersi.",
        "Il calore del sole incarna la tua passione.",
        "Un respiro per centrare le tue intenzioni.",
        "La luce rivela la bellezza del quotidiano.",
        "Un momento per onorare il tuo impegno.",
        "La chiarezza del giorno ti dà nuove ali.",
        "Un mormorio di luce accompagna i tuoi sensi.",
        "L'energia del mezzogiorno guida i tuoi passi.",
        "Un momento per seminare nuove intenzioni.",
        "Il calore del cielo protegge il tuo scopo.",
        "Il sole abbraccia la tua energia con tenerezza.",
        "Un momento di pace nel mezzo della giornata.",
        "La luce intensa accarezza i tuoi progetti.",
        "Un respiro caldo per l'anima.",
        "L'energia del mezzogiorno rinnova il tuo slancio.",
        "Un momento per essere grati di questa giornata vibrante.",
        "Il calore del sole conforta lo spirito.",
        "Un soffio di vitalità scorre nel tuo essere.",
        "La pienezza del giorno ricarica il tuo spirito.",
        "Un momento di connessione interiore sotto la luce.",
        "La chiarezza del mezzogiorno ispira nuove idee.",
        "Un mormorio di sole nutre le tue emozioni.",
        "La luce risveglia la tua creatività dormiente.",
        "Un respiro leggero tra azioni intense.",
        "Il calore avvolge ogni cellula del tuo corpo.",
        "Un momento per riconnetterti con le tue intenzioni.",
        "L'energia del mezzogiorno guida il tuo scopo.",
        "Un momento per ritrovare il tuo centro.",
        "La luce del sole rivela l'essenziale.",
        "Un sospiro di calma nel mezzo della giornata.",
        "La chiarezza ti guida con fermezza e tenerezza.",
        "Un mormorio di gratitudine illumina il tuo ambiente.",
        "Il calore del giorno nutre il tuo cuore.",
        "Un respiro pieno di chiarezza ed equilibrio.",
        "L'energia del mezzogiorno potenzia la tua anima.",
        "Un momento per contemplare i tuoi progressi.",
        "La luce ti ispira a continuare con passione.",
        "Un soffio di serenità in piena attività.",
        "La pienezza del giorno riempie il tuo spazio interiore.",
        "Un momento gioioso in mezzo al quotidiano.",
        "Il calore solare rafforza il tuo spirito.",
        "Un respiro consapevole per allineare la tua mente.",
        "La chiarezza del sole avanza con te.",
        "Un mormorio di pace riempie il tuo petto.",
        "L'energia del giorno vibra dentro di te.",
        "Un momento di gratitudine per ciò che è stato vissuto.",
        "La luce ti accompagna in ogni decisione.",
        "Un soffio di calma in mezzo alla routine.",
        "La pienezza ti avvolge con dolcezza.",
        "Un momento per riflettere e ricaricare.",
        "Il calore del mezzogiorno bacia il tuo spirito.",
        "Un respiro di creazione sotto il sole.",
        "La chiarezza ti spinge verso i tuoi obiettivi.",
        "Un mormorio di luce rafforza la tua essenza.",
        "L'energia del giorno si sente potente.",
        "Un momento di armonia nel tuo viaggio.",
        "La luce ti sostiene con delicatezza.",
        "Un soffio di gratitudine illumina il tuo passo.",
        "La pienezza del mezzogiorno nutre il tuo essere.",
        "Un momento di connessione con l'autentico.",
        "Il calore solare ti ispira a continuare.",
        "Un respiro per riscoprire te stesso.",
        "La chiarezza del giorno risveglia la tua concentrazione.",
        "Un mormorio di pace scorre nei tuoi pensieri.",
        "L'energia del mezzogiorno vibra nel tuo sangue.",
        "Un momento di pausa con intenzione.",
        "La luce del sole dipinge il tuo essere di ottimismo.",
        "Un soffio di calma in mezzo al trambusto.",
        "La pienezza del giorno si sente nell'aria.",
        "Un momento per allineare corpo, mente e anima.",
        "Il calore del mezzogiorno ti regala pienezza.",
        "Un respiro per affinare le tue intenzioni.",
        "La chiarezza ti rafforza in ogni scelta.",
        "Un mormorio di luce riempie il tuo spazio interiore.",
        "L'energia del sole ti avvolge di vita.",
        "Un momento di riconnessione interna.",
        "La luce del mezzogiorno accarezza il tuo scopo.",
        "Un soffio di serenità ti accompagna.",
        "La pienezza del giorno vibra in te.",
        "Un momento per onorare il tuo percorso.",
        "Il calore solare rafforza la tua presenza.",
        "Un respiro vitale nel mezzo della giornata.",
        "La chiarezza del sole guida il tuo cammino.",
        "Un mormorio di gratitudine sostiene il tuo viaggio.",
        "L'energia del mezzogiorno rinnova il tuo slancio.",
        "Un momento di calma nel turbine.",
        "La luce ti ispira a brillare con trasparenza.",
        "Un soffio di serenità ti rinnova.",
        "La pienezza del giorno si filtra nelle tue giornate.",
        "Un momento per essere grati di ciò che è stato raggiunto.",
        "Il calore del sole accompagna i tuoi passi.",
        "Un respiro interiore in mezzo al trambusto.",
        "La chiarezza del mezzogiorno riconosce il tuo valore.",
        "Un mormorio di pace rivitalizza la tua essenza.",
        "L'energia del giorno pulsa nel tuo cuore.",
        "Un momento consapevole di gratitudine.",
        "La luce ti abbraccia con dolcezza.",
        "Un soffio di calma per nutrire il tuo spirito.",
        "La pienezza del mezzogiorno ti ispira.",
        "Un momento per ritrovare la tua armonia.",
        "Il calore solare rafforza la tua fiducia.",
        "Un respiro pieno di pura chiarezza.",
        "La chiarezza ti spinge verso nuovi obiettivi.",
        "Un mormorio di luce sostiene la tua essenza.",
        "L'energia del sole vibra nel tuo essere.",
        "Un momento di piena riconnessione.",
        "La luce del mezzogiorno accarezza il tuo io interiore.",
        "Un soffio di serenità illumina il tuo essere.",
        "La pienezza del giorno ricarica la tua mente.",
        "Un momento per onorare il tuo cammino.",
        "Il calore del sole ti regala presenza.",
        "Un respiro vitale rafforza il tuo spirito.",
        "La chiarezza del mezzogiorno guida i tuoi passi.",
        "Un mormorio di gratitudine scorre in te.",
        "L'energia del giorno sostiene il tuo slancio.",
        "Un momento consapevole di benessere.",
        "La luce del sole accompagna la tua crescita.",
        "Un soffio di calma eleva la tua intenzione.",
        "La pienezza del mezzogiorno nutre il tuo essere.",
        "Un momento per riconnetterti con la tua essenza.",
        "Il calore solare ispira il tuo cammino."
    ],
    // Tarde
    afternoonPhrasesIT : [
        "Il pomeriggio ti avvolge con la sua luce dorata.",
        "Un sospiro di sole ammorbidisce il giorno.",
        "Questo tratto della giornata invita alla riflessione.",
        "La luce diventa calda e avvolgente.",
        "Un mormorio di calma permea l'ambiente.",
        "Il pomeriggio accarezza i tuoi pensieri.",
        "Un momento per riconnettersi con il presente.",
        "La serenità si diffonde con ogni raggio.",
        "Un momento dorato per respirare profondamente.",
        "La luce del pomeriggio dipinge le tue emozioni.",
        "Un soffio di pace attraversa la tua essenza.",
        "L'atmosfera sussurra tranquillità.",
        "Questo tratto della giornata risveglia l'ispirazione.",
        "Il pomeriggio porta con sé dolci promesse.",
        "Un mormorio sereno accompagna il tuo cammino.",
        "La luce diventa più morbida e confortante.",
        "Un momento per essere grati di ciò che si è.",
        "Il pomeriggio invita a una pausa consapevole.",
        "Un caldo abbraccio di luce ti circonda.",
        "La calma del giorno trova il suo culmine.",
        "Un respiro per allineare il tuo io interiore.",
        "La luce si filtra con una delicata tenerezza.",
        "Un morbido silenzio risveglia la tua intuizione.",
        "Il pomeriggio risuona di un canto silenzioso.",
        "Un mormorio dorato riempie l'aria.",
        "La luce tiepida rafforza le tue idee.",
        "Un momento per apprezzare le cose semplici.",
        "L'atmosfera diventa contemplativa.",
        "Un soffio di chiarezza illumina la tua mente.",
        "Il pomeriggio ti abbraccia senza fretta.",
        "Un momento di gratitudine nella luce temperata.",
        "La luce diventa un rifugio intimo.",
        "Un morbido mormorio ti porta serenità.",
        "La calma si diffonde in ogni raggio.",
        "Un respiro dorato conforta il giorno.",
        "Il pomeriggio dispiega il suo manto pacifico.",
        "Un caldo sospiro inonda l'ambiente.",
        "La luce dorata risveglia la creatività.",
        "Un momento per riconnetterti con te stesso.",
        "Il pomeriggio ti regala la sua pace interiore.",
        "Un debole mormorio ti avvolge.",
        "La luce si posa sui tuoi pensieri.",
        "Un respiro profondo ti rinnova.",
        "Il pomeriggio costruisce spazi di calma.",
        "Un momento per seminare gratitudine.",
        "La luce disegna ombre tranquille.",
        "Un soffio di ispirazione ti accarezza.",
        "L'atmosfera vibra di armonia.",
        "Un mormorio di luce rafforza il tuo essere.",
        "Il pomeriggio equilibra la tua energia.",
        "Un momento per rafforzare i tuoi sogni.",
        "La luce ti invita a creare senza rumore.",
        "Un respiro consapevole ti sostiene.",
        "L'atmosfera batte con serenità.",
        "Un soffio di bellezza abita questo tratto.",
        "Il pomeriggio ti sussurra piena presenza.",
        "Un caldo mormorio rafforza la tua anima.",
        "La luce si aggrappa alla tua serenità.",
        "Un momento per creare dal cuore.",
        "Il pomeriggio accarezza i tuoi sensi.",
        "Un soffio di gratitudine ti accompagna.",
        "L'atmosfera diventa un rifugio.",
        "Un soffio di calma anima il tuo essere.",
        "La luce ti avvolge con morbidezza.",
        "Un mormorio dorato armonizza le tue idee.",
        "Il pomeriggio consolida il tuo equilibrio interiore.",
        "Un momento per onorare il tuo viaggio.",
        "La luce ammorbidisce ogni pensiero.",
        "Un respiro vitale rafforza il tuo essere.",
        "L'atmosfera vibra di una luce calmante.",
        "Un soffio di chiarezza illumina la tua essenza.",
        "Il pomeriggio ti regala una creatività silenziosa.",
        "Un mormorio di gratitudine risuona.",
        "La luce riempie il tuo spirito di tenerezza.",
        "Un momento di dolce introspezione.",
        "L'atmosfera diventa pura contemplazione.",
        "Un respiro per riallineare la tua energia.",
        "Il pomeriggio ti abbraccia senza pretese.",
        "Un soffio di speranza scorre nelle tue vene.",
        "La luce dorata impreziosisce il momento.",
        "Un mormorio sereno calma le tue preoccupazioni.",
        "Il pomeriggio ti offre la sua versione migliore.",
        "Un momento per assaporare la quiete.",
        "La luce si filtra nel tuo io interiore.",
        "Un respiro consapevole abbraccia la tua mente.",
        "L'atmosfera irradia una luce confortante.",
        "Un soffio di pace attraversa il tuo essere.",
        "Il pomeriggio sembra una poesia visiva.",
        "Un mormorio di calma rafforza il tuo centro.",
        "La luce ti guida verso l'essenziale.",
        "Un momento di connessione autentica.",
        "L'atmosfera ti offre un rifugio interno.",
        "Un soffio di luce rinnova il tuo slancio.",
        "Il pomeriggio ti regala una serena chiarezza.",
        "Un soffio di gratitudine abbraccia la tua giornata.",
        "La luce si posa dolcemente sul tuo spirito.",
        "Un momento per riaffermare i tuoi propositi.",
        "L'atmosfera ti avvolge nella calma.",
        "Un mormorio interiore risveglia la tua anima.",
        "Il pomeriggio vibra di un canto silenzioso.",
        "Un respiro per valorizzare ciò che è stato raggiunto.",
        "La luce ti nutre di pienezza.",
        "Un soffio di serenità radica il tuo ambiente.",
        "L'atmosfera calma batte insieme a te.",
        "Un momento per sentire la tua forza.",
        "Il pomeriggio risuona di segreti dorati.",
        "Un soffio di luce accarezza lo spirito.",
        "Il calore serale risveglia i tuoi sogni.",
        "Un momento per ascoltare il tuo respiro.",
        "Il pomeriggio ti avvolge in una sottile serenità.",
        "Un morbido mormorio rafforza il tuo io interiore.",
        "La luce entra nel tuo essere senza fretta.",
        "Un respiro consapevole riconnette l'anima.",
        "La calma pomeridiana si diffonde nell'ambiente.",
        "Un momento per seminare il silenzio interiore.",
        "La luce dorata sostiene ogni passo.",
        "Un momento di gratitudine si filtra in te.",
        "Il pomeriggio sussurra una dolce confidenza.",
        "Un soffio di tenerezza avvolge i tuoi sensi.",
        "L'atmosfera batte con la dolcezza serale.",
        "Un respiro lento centra i tuoi pensieri.",
        "Il pomeriggio abbraccia la fine della giornata.",
        "Un mormorio di calma ti accompagna.",
        "La luce intensa rilascia un'armonia interiore.",
        "Un momento per riconnettersi con il profondo.",
        "La quiete serale accarezza la tua mente.",
        "Un soffio di ispirazione ti scorre sulla pelle.",
        "Il pomeriggio sembra un caldo abbraccio.",
        "Un respiro per valorizzare ciò che è stato raggiunto.",
        "La luce ti regala un'oasi di pace.",
        "Un momento per allineare corpo e mente.",
        "Il pomeriggio scorre con un ritmo pacifico.",
        "Un mormorio interiore incoraggia la tua fiducia.",
        "La luce dorata ti impedisce di avere fretta.",
        "Un momento per essere grati di questo tratto.",
        "L'atmosfera si tinge di calma e dolcezza.",
        "Un soffio di gratitudine in ogni espirazione.",
        "Il pomeriggio respira insieme al tuo silenzio.",
        "Un respiro serale rinnova le energie.",
        "La luce si posa dolcemente sul tuo spirito.",
        "Un momento per sentire il tuo cuore battere.",
        "La calma serale rafforza il tuo spirito.",
        "Un mormorio sereno ti guida.",
        "Il pomeriggio ti protegge nel suo manto caldo.",
        "Un respiro per riconnetterti con il tuo centro.",
        "La luce dorata avvolge i tuoi pensieri.",
        "Un momento di introspezione acustica.",
        "L'atmosfera vibra dolcemente e costantemente.",
        "Un soffio di calma attraversa la tua coscienza.",
        "Il pomeriggio ti offre un rifugio interiore.",
        "Un momento per rivitalizzare il tuo scopo.",
        "La luce serale sostiene il tuo equilibrio.",
        "Un mormorio di gratitudine emerge.",
        "Il pomeriggio si presenta con nobiltà.",
        "Un respiro per continuare con intenzione.",
        "La calma dorata conforta i tuoi passi.",
        "Un momento per ridefinire il tuo benessere.",
        "La luce soffusa affina la tua sensibilità.",
        "Un soffio di chiarezza dentro di te.",
        "Il pomeriggio canta senza parole.",
        "Un respiro consapevole accompagna la tua essenza.",
        "L'atmosfera fluisce con serenità.",
        "Un momento per enfatizzare il tuo presente.",
        "La luce dorata armonizza le tue idee.",
        "Un mormorio calmo nutre il tuo spirito.",
        "Il pomeriggio inebria i tuoi sensi.",
        "Un soffio di pace ti conforta.",
        "Il pomeriggio illumina la tua quiete.",
        "Un respiro profondo allinea il tuo essere.",
        "La luce serale invita alla riflessione.",
        "Un momento per essere grati di questo viaggio.",
        "L'atmosfera sussurra tranquillità.",
        "Un momento per aprire il cuore.",
        "La luce dorata evoca una tenerezza interiore.",
        "Un soffio di calma rafforza il tuo io interiore.",
        "Il pomeriggio ti copre con il suo manto pacifico.",
        "Un morbido mormorio incoraggia i tuoi pensieri.",
        "La luce si filtra come un abbraccio silenzioso.",
        "Un respiro desiderato all'arrivo di questo tratto.",
        "La calma serale diventa una presenza.",
        "Un momento per nutrire la tua essenza.",
        "L'atmosfera pacifica trasmette sicurezza.",
        "Un soffio di ispirazione illumina il tuo sentiero.",
        "Il pomeriggio sembra un canto sereno.",
        "Un respiro che ordina le tue idee.",
        "La luce si posa delicatamente su di te.",
        "Un momento per approfondire la connessione interiore.",
        "Il pomeriggio riprende il polso della giornata.",
        "Un mormorio intimo ristora lo spirito.",
        "La luce serale rafforza la tua introspezione.",
        "Un respiro mite accompagna il tuo riposo.",
        "La calma avvolge il tuo istante presente.",
        "Un soffio di gratitudine ti abbraccia.",
        "Il pomeriggio ti regala una chiarezza silenziosa.",
        "Un momento per contemplare la tua energia.",
        "L'atmosfera si carica di gentilezza.",
        "Un mormorio confortante riempie l'aria.",
        "La luce dorata ti ancora al momento.",
        "Un respiro per chiudere il capitolo di questa giornata.",
        "Il pomeriggio respira con te nella calma.",
        "Un soffio di bellezza si rivela.",
        "La luce impreziosisce il tuo silenzio interiore.",
        "Un momento per valorizzare il tuo cammino.",
        "L'atmosfera diventa un rifugio interno.",
        "Un momento di pace ti avvolge.",
        "Il pomeriggio risuona con la tua essenza.",
        "Un morbido mormorio riposa sul tuo petto.",
        "La luce serale accompagna la tua riflessione.",
        "Un respiro che calma il trambusto.",
        "La calma ti accompagna in questo tratto.",
        "Un soffio di ispirazione ti sostiene.",
        "Il pomeriggio mostra il suo volto più gentile.",
        "Un momento per essere grati di ciò che si è imparato.",
        "L'atmosfera si apre davanti al tuo sguardo.",
        "Un mormorio di calma abbraccia il tuo cuore.",
        "La luce soffusa illumina il tuo benessere.",
        "Un respiro per completare la tua giornata.",
        "Il pomeriggio vibra di una speranza silenziosa."
    ],
    // Atardecer
    sunsetPhrasesIT : [
        "Il cielo si riversa in toni di fuoco.",
        "Un sospiro di luce scende sull'orizzonte.",
        "La calma serale dipinge tutto d'oro.",
        "Un momento per ritrovarsi nella bellezza.",
        "Il sole si congeda con un caldo abbraccio.",
        "Un mormorio di gratitudine tinge il pomeriggio.",
        "I colori del crepuscolo accarezzano l'anima.",
        "Un soffio di serenità in ogni riflesso.",
        "Il pomeriggio canta la sua canzone in silenzio.",
        "Un respiro per apprezzare l'effimero.",
        "L'atmosfera si veste di toni morbidi.",
        "Un momento in cui il giorno diventa arte.",
        "Il cielo galleggia in una tavolozza dorata.",
        "Un mormorio di calma attraversa il tuo petto.",
        "La luce discendente equilibra lo spirito.",
        "Un soffio di poesia nel crepuscolo.",
        "Il pomeriggio diventa un dolce sussurro.",
        "Un momento per essere grati di questo dono.",
        "La calma del tramonto avvolge l'ambiente.",
        "Un caldo mormorio nutre i tuoi pensieri.",
        "La luce si placa al calar del giorno.",
        "Un soffio di nostalgia trasforma il cielo.",
        "Il pomeriggio ti accompagna nella sua pienezza.",
        "Un momento di introspezione dorata.",
        "L'atmosfera vibra di toni crepuscolari.",
        "Un dolce mormorio ti sostiene dal cielo.",
        "La luce dorata delinea i tuoi sogni.",
        "Un sospiro autunnale veste il pomeriggio.",
        "La calma del crepuscolo riempie i tuoi sensi.",
        "Un rifugio istantaneo di pace e colore.",
        "Il pomeriggio onirico ti toglie il fiato.",
        "Un soffio di luce placa la mente.",
        "L'atmosfera brilla come pennellate.",
        "Un mormorio serale nutre l'io interiore.",
        "Il pomeriggio diventa un palcoscenico emotivo.",
        "Un momento per riconnettersi con la pazienza.",
        "La luce scivola dolcemente nell'aria.",
        "Un soffio di calma sigilla il giorno.",
        "La calma del tramonto sussurra al tuo orecchio.",
        "Un mormorio dorato abbraccia i tuoi sogni.",
        "Il pomeriggio sboccia in tonalità morbide.",
        "Un momento per assaporare la leggerezza.",
        "L'atmosfera si espande lentamente.",
        "Un mormorio intimo accompagna il cielo.",
        "La luce soffusa ti invita a contemplare.",
        "Un soffio di gratitudine colora l'ambiente.",
        "Il pomeriggio respira con raffinata eleganza.",
        "Un momento per fondersi con la natura.",
        "La serenità serale ravviva i tuoi sensi.",
        "Un mormorio dorato culla il giorno.",
        "La luce del crepuscolo equilibra lo spirito.",
        "Un momento di inaspettata bellezza.",
        "L'atmosfera si veste di calma dorata.",
        "Un sospiro serale accarezza il cuore.",
        "Il pomeriggio diventa un canto senza parole.",
        "Un soffio di luce rafforza la tua pace.",
        "La calma del crepuscolo ti protegge.",
        "Un momento per chiudere con gratitudine.",
        "La luce che si affievolisce ti avvolge dolcemente.",
        "Un caldo mormorio riempie i tuoi pensieri.",
        "Il pomeriggio diventa una poesia visiva.",
        "Un soffio di serenità ti ripara.",
        "L'atmosfera fluisce con dolcezza serale.",
        "Un momento di introspezione luminosa.",
        "La luce dorata delinea le tue idee.",
        "Un mormorio di calma sostiene il tuo spirito.",
        "Il pomeriggio ti offre un rifugio intimo.",
        "Un soffio di gratitudine ti attraversa il petto.",
        "La serenità del tramonto ti abbraccia.",
        "Un momento per riconnetterti con la tua essenza.",
        "La luce discendente ti guida al riposo.",
        "Un mormorio di luce afferma il tuo io interiore.",
        "Il pomeriggio irradia un silenzio confortante.",
        "Un soffio di pace abita ogni respiro.",
        "L'atmosfera si trasforma in poesia silenziosa.",
        "Un momento per essere grati del presente.",
        "La luce serale dissolve la tua stanchezza.",
        "Un mormorio dorato ripara il tuo equilibrio.",
        "Il pomeriggio ti avvolge con tonalità morbide.",
        "Un soffio di calma dissolve le tensioni.",
        "La serenità serale ti riconnette.",
        "Un momento per nutrire la tua tranquillità.",
        "La luce che si affievolisce illumina la tua introspezione.",
        "Un mormorio serale ispira calma.",
        "Il pomeriggio offre il suo abbraccio dorato.",
        "Un soffio di gratitudine matura la tua calma.",
        "L'atmosfera si adorna di un leggero silenzio.",
        "Un momento per fondersi con il giorno.",
        "La luce finale delinea le tue aspirazioni.",
        "Un dolce mormorio accompagna il tuo crepuscolo.",
        "Il pomeriggio diventa uno specchio interiore.",
        "Un soffio di serenità ti connette al qui e ora.",
        "La calma serale ti avvolge senza fretta.",
        "Un momento di pienezza e profondità.",
        "La luce dorata rafforza il tuo benessere.",
        "Un mormorio interiore sostiene il tuo spirito.",
        "Il pomeriggio raccoglie il meglio della tua giornata.",
        "Un soffio di gratitudine accompagna la chiusura.",
        "L'atmosfera serale ti invita al silenzio.",
        "Un momento per allineare cuore e mente.",
        "La luce si congeda, impreziosendo il paesaggio.",
        "Un mormorio dorato ravviva la tua essenza.",
        "Il pomeriggio è sigillato da un caldo sospiro.",
        "Un soffio di calma si congeda dal crepuscolo.",
        "La serenità del crepuscolo conforta i tuoi passi.",
        "Un momento per rilasciare le tensioni.",
        "La luce serale copre i tuoi pensieri.",
        "Un mormorio intimo incornicia il tuo sorriso.",
        "Il pomeriggio si estende nel suo abbraccio dorato.",
        "Un soffio di gratitudine culmina la giornata.",
        "L'atmosfera diventa una testimone serena.",
        "Un momento per essere grati e lasciare andare.",
        "La luce discendente offre un gentile addio.",
        "Un dolce mormorio conclude il viaggio.",
        "Il pomeriggio offre il suo bacio finale di luce.",
        "Un soffio di calma accarezza il crepuscolo.",
        "La serenità serale nutre il tuo io interiore."
    ],
    // Noche
    nightPhrasesIT : [
        "La notte inizia a sussurrare.",
        "Il cielo si tinge di un blu profondo.",
        "Le stelle si risvegliano lentamente.",
        "La luna fa capolino timidamente.",
        "L'aria fresca accarezza la pelle.",
        "Le luci della città tremolano come lucciole.",
        "È ora di lasciarsi trasportare dai sogni.",
        "Il giorno si congeda con un sospiro.",
        "La quiete della notte invita alla riflessione.",
        "Il silenzio diventa compagnia.",
        "Le ombre si allungano con eleganza.",
        "La notte si veste a festa.",
        "Il cielo notturno è una tela stellata.",
        "La brezza notturna porta con sé segreti.",
        "Le strade si svuotano, ma la città è ancora viva.",
        "È il momento perfetto per una tazza di tè.",
        "L'oscurità non è assenza, ma presenza.",
        "Le stelle raccontano storie antiche.",
        "La luna piena illumina il cammino.",
        "La notte è giovane e piena di promesse.",
        "È ora di lasciare che la mente voli libera.",
        "La serenità della notte avvolge l'anima.",
        "Le luci lontane sembrano sussurrare canzoni.",
        "La quiete notturna è un balsamo per lo spirito.",
        "È ora di lasciare andare e riposare.",
        "La notte diventa un rifugio accogliente.",
        "Le stelle sembrano più vicine che mai.",
        "La luna piena riflette sogni dimenticati.",
        "La città dorme, ma i pensieri si risvegliano.",
        "La notte è una poesia senza parole.",
        "Le ombre danzano al ritmo del vento.",
        "È il momento perfetto per un abbraccio silenzioso.",
        "L'oscurità nasconde bellezza in ogni angolo.",
        "Le luci della città sono stelle sulla terra.",
        "La notte invita alla calma e all'introspezione.",
        "È ora di lasciarsi trasportare dalla musica dell'anima.",
        "La luna piena riflette segreti condivisi.",
        "Le stelle scintillano come promesse lontane.",
        "La notte è una tela bianca per i sogni.",
        "È ora di chiudere gli occhi e viaggiare.",
        "L'oscurità non è paura, è mistero.",
        "Le luci della città sono lucciole moderne.",
        "La notte è un rifugio per i pensieri profondi.",
        "È ora di lasciare che il cuore parli.",
        "La luna piena illumina i sentieri perduti.",
        "Le stelle sono gli occhi dell'universo.",
        "La notte è un sospiro del giorno.",
        "È ora di ascoltare il silenzio.",
        "L'oscurità nasconde storie da raccontare.",
        "Le luci lontane sono fari in lontananza.",
        "La notte è il palcoscenico dei sogni.",
        "È ora di lasciare che la mente si liberi.",
        "La luna piena è uno specchio dell'anima.",
        "Le stelle sono le impronte del tempo.",
        "La notte è un abbraccio caldo e silenzioso.",
        "È ora di lasciarsi trasportare dall'immaginazione.",
        "L'oscurità nasconde bellezza al suo interno.",
        "Le luci della città sono stelle intrappolate.",
        "La notte invita alla riflessione e al riposo.",
        "È ora di lasciare che l'anima si rilassi.",
        "La luna piena illumina i segreti del cuore.",
        "Le stelle sono le risate dell'universo.",
        "La notte è un viaggio senza mappe.",
        "È ora di lasciare andare e riposare.",
        "L'oscurità nasconde magia nel suo silenzio.",
        "Le luci lontane sono sogni da realizzare.",
        "La notte è il rifugio dei poeti.",
        "È ora di lasciare che i pensieri fluiscano.",
        "La luna piena riflette la bellezza dell'anima.",
        "Le stelle sono le parole del cielo.",
        "La notte è una tela per i sogni.",
        "È ora di chiudere gli occhi e volare.",
        "L'oscurità nasconde storie da scoprire.",
        "Le luci della città sono stelle in movimento.",
        "La notte invita alla calma e alla serenità.",
        "È ora di lasciare che il cuore si esprima.",
        "La luna piena illumina desideri nascosti.",
        "Le stelle sono i sospiri dell'universo.",
        "La notte è una poesia senza fine.",
        "È ora di ascoltare il mormorio del vento.",
        "L'oscurità nasconde bellezza nel suo mistero.",
        "Le luci lontane sono ricordi dimenticati.",
        "La notte è il rifugio dei sogni perduti.",
        "È ora di lasciare che la mente si liberi.",
        "La luna piena riflette la luce interiore.",
        "Le stelle sono le impronte degli dèi.",
        "La notte è un abbraccio silenzioso.",
        "È ora di lasciarsi trasportare dalla pace.",
        "L'oscurità nasconde segreti da rivelare.",
        "Le luci della città sono stelle cadenti.",
        "La notte invita alla riflessione e alla calma.",
        "È ora di lasciare che l'anima si rilassi.",
        "La luna piena illumina i sentieri solitari.",
        "Le stelle sono gli occhi del cielo.",
        "La notte è un sospiro del giorno.",
        "È ora di ascoltare il silenzio.",
        "L'oscurità nasconde storie da raccontare.",
        "Le luci lontane sono fari in lontananza.",
        "La notte è il palcoscenico dei sogni.",
        "È ora di lasciare che la mente si liberi.",
        "La luna piena è uno specchio dell'anima.",
        "Le stelle sono le impronte del tempo.",
        "La notte è un abbraccio caldo e silenzioso.",
        "È ora di lasciarsi trasportare dall'immaginazione.",
        "L'oscurità nasconde bellezza al suo interno.",
        "Le luci della città sono stelle intrappolate.",
        "La notte invita alla riflessione e al riposo.",
        "È ora di lasciare che l'anima si rilassi.",
        "La luna piena illumina i segreti del cuore.",
        "Le stelle sono le risate dell'universo.",
        "La notte è un viaggio senza mappe.",
        "È ora di lasciare andare e riposare.",
        "L'oscurità nasconde la magia nel suo silenzio.",
        "Le luci lontane sono sogni da realizzare.",
        "La notte è il rifugio dei poeti.",
        "È ora di lasciare che i pensieri fluiscano.",
        "La luna piena riflette la bellezza dell'anima.",
        "Le stelle sono le parole del cielo.",
        "La notte è una tela per i sogni.",
        "È ora di chiudere gli occhi e volare.",
        "L'oscurità nasconde storie da scoprire.",
        "Le luci della città sono stelle in movimento.",
        "La notte invita alla calma e alla serenità.",
        "È ora di lasciare che il cuore si esprima.",
        "La luna piena illumina desideri nascosti.",
        "Le stelle sono i sospiri dell'universo.",
        "La notte è una poesia senza fine.",
        "È ora di ascoltare il mormorio del vento.",
        "L'oscurità nasconde la bellezza nel suo mistero.",
        "Le luci lontane sono ricordi dimenticati.",
        "La notte è il rifugio dei sogni perduti.",
        "La notte sussurra segreti all'orecchio del vento.",
        "Il cielo notturno è una tela di stelle perdute.",
        "La luna osserva in silenzio i sogni che nascono.",
        "L'oscurità accoglie i pensieri erranti.",
        "Le stelle scintillano come sospiri dimenticati.",
        "Il primo mattino è un sussurro tra le ombre.",
        "Il vento notturno canta canzoni lontane.",
        "La luna piena illumina i sentieri solitari.",
        "Il silenzio della notte è un rifugio per l'anima.",
        "Le stelle sono gli occhi dell'universo che osserva.",
        "La notte è una poesia senza parole.",
        "Il mormorio del vento è la voce dell'oscurità.",
        "La luna riflette i sogni che non sono ancora stati raccontati.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo notturno è un mare di stelle naviganti.",
        "La notte è una tela dove i sogni vengono dipinti.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le stelle sono i gioielli del manto notturno.",
        "La luna piena è un faro nell'oscurità.",
        "La notte è un abbraccio caldo e silenzioso.",
        "Le ombre danzano al ritmo del vento notturno.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana.",
        "La notte è un sospiro dell'universo.",
        "Le stelle sono le promesse del cielo.",
        "La luna piena è uno specchio della notte.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana.",
        "La notte è un sospiro dell'universo.",
        "Le stelle sono le promesse del cielo.",
        "La luna piena è uno specchio della notte.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana.",
        "La notte è un sospiro dell'universo.",
        "Le stelle sono le promesse del cielo.",
        "La luna piena è uno specchio della notte.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana.",
        "La notte è un sospiro dell'universo.",
        "Le stelle sono le promesse del cielo.",
        "La luna piena è uno specchio della notte.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana.",
        "La notte è un sospiro dell'universo.",
        "Le stelle sono le promesse del cielo.",
        "La luna piena è uno specchio della notte.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana.",
        "La notte è un sospiro dell'universo.",
        "Le stelle sono le promesse del cielo.",
        "La luna piena è uno specchio della notte.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana.",
        "La notte è un sospiro dell'universo.",
        "Le stelle sono le promesse del cielo.",
        "La luna piena è uno specchio della notte.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana.",
        "La notte è un sospiro dell'universo.",
        "Le stelle sono le promesse del cielo.",
        "La luna piena è uno specchio della notte.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana.",
        "La notte è un sospiro dell'universo.",
        "Le stelle sono le promesse del cielo.",
        "La luna piena è uno specchio della notte.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana.",
        "La notte è un sospiro dell'universo.",
        "Le stelle sono le promesse del cielo.",
        "La luna piena è uno specchio della notte.",
        "Il silenzio del primo mattino è un canto profondo.",
        "Le ombre si allungano come ricordi perduti.",
        "Il cielo stellato è una mappa di sogni perduti.",
        "La luna osserva in silenzio i segreti del mondo.",
        "L'oscurità nasconde storie da scoprire.",
        "Le stelle sono le impronte degli dèi nel cielo.",
        "La notte è un rifugio per i pensieri solitari.",
        "Il vento notturno accarezza i ricordi dimenticati.",
        "La luna piena illumina i sentieri dell'anima errante.",
        "Le ombre si allungano come sospiri nella penombra.",
        "Il cielo notturno è uno specchio dell'anima umana."
    ]
};

export default collectionPhrasesIT;