const collectionPhrasesPT = {
    // Amanecer
    dawnPhrasesPT : [
        "A manhã sussurra promessas ao vento.",
        "A aurora desperta com um suspiro de luz.",
        "Um bálsamo dourado acaricia o horizonte.",
        "O céu se veste de aquarelas suaves.",
        "Um murmúrio de esperança viaja pelo ar.",
        "O silêncio dá lugar à luz tímida.",
        "O mundo se espreguiça e boceja em cores.",
        "A aurora ensina magia sem palavras.",
        "Tudo renasce nesse instante sagrado.",
        "Um pulsar dourado inicia o dia.",
        "A brisa matinal traz novos começos.",
        "Um poema de luz nasce no céu.",
        "A penumbra se rende à luz dourada.",
        "Um sussurro quente desperta a terra.",
        "O horizonte se ilumina em calma.",
        "Uma melodia silenciosa governa a aurora.",
        "O céu respira em tons pastéis.",
        "A vida espia por trás do véu da noite.",
        "O sol ergue sua primeira saudação tímida.",
        "A esperança se filtra por cada raio.",
        "O mundo desperta em murmúrios dourados.",
        "Um momento eterno banhado em luz.",
        "A aurora pinta suas primeiras linhas.",
        "Um abraço de luz cobre a manhã.",
        "O dia começa com um suspiro quente.",
        "Uma tela de calma se desdobra.",
        "A claridade se insinua no ar fresco.",
        "Uma canção silenciosa anuncia o dia.",
        "A essência da aurora preenche a alma.",
        "O céu revela seu rosto pacífico.",
        "Um murmúrio dourado embala o horizonte.",
        "A promessa de um novo capítulo vibra.",
        "O ar vibra com tons de esperança.",
        "Sussurros de luz acariciam a penumbra.",
        "A aurora desperta com suavidade.",
        "Um halo dourado envolve a terra.",
        "Toda manhã, uma nova possibilidade renasce.",
        "O silêncio da aurora sussurra vida.",
        "Uma carícia de sol rompe lentamente.",
        "A noite se dissolve com doçura.",
        "Um brilho suave beija o céu.",
        "A aurora abraça o silêncio noturno.",
        "Um verso de luz é recitado pelo horizonte.",
        "O frescor da aurora enche os pulmões.",
        "Um novo ar carrega a promessa.",
        "A calma antes do pulsar do dia.",
        "Um sopro de luz viaja sem pressa.",
        "A atmosfera vibra em tons suaves.",
        "Um céu nascente oferece serenidade.",
        "O mundo desperta em um sussurro.",
        "Uma carícia da aurora penetra na alma.",
        "O espaço se enche de luz delicada.",
        "A aurora escreve poemas sem tinta.",
        "Um beijo de sol desperta a calma.",
        "A aurora abre suas asas púrpuras.",
        "O dia começa com um gesto de paz.",
        "Um suspiro quente sobre a charneca adormecida.",
        "A luz dança na névoa matinal.",
        "Um suave crescendo de claridade.",
        "O sol murmura seu bom dia.",
        "A aurora derrama seu ouro morno.",
        "Um palco de calma e cor.",
        "O horizonte respira em calma.",
        "Um poema visual nasce no céu.",
        "O frescor entra por todas as janelas.",
        "A aurora desdobra suas asas suaves.",
        "Um momento de eternidade na aurora.",
        "A promessa de luz pode ser sentida.",
        "O ar da manhã tem gosto de esperança.",
        "Um despertar em calma e luz.",
        "O dia se anuncia sem pressa.",
        "Uma carícia solar para a alma.",
        "A penumbra se rende lentamente.",
        "Uma canção sem voz envolve o mundo.",
        "A aurora sopra com doçura.",
        "Um brilho inicia o pulsar do dia.",
        "A manhã oferece seu primeiro sopro.",
        "Um beijo dourado reaviva os sentidos.",
        "A promessa do dia é desenhada.",
        "Um suspiro de cor abre os olhos.",
        "O sol espia com respeito.",
        "A calma é adornada com luz.",
        "Um halo quente toca a paisagem.",
        "A manhã se desdobra em silêncio.",
        "Um murmúrio luminoso inunda o ar.",
        "A aurora canta sem palavras.",
        "Um abraço pacífico ao despertar.",
        "A beleza nasce sem alarde.",
        "Um momento de pura serenidade.",
        "A aurora floresce no céu.",
        "A alvorada escreve seu próprio hino.",
        "A luz dança na calma.",
        "Um sussurro de cores suaves.",
        "A manhã veste seu novo manto.",
        "Uma promessa em cada rajada.",
        "A penumbra se derrete em ouro.",
        "Um murmúrio de dia nasce.",
        "A aurora exala paz.",
        "Um pulsar silencioso desperta.",
        "A luz veste o mundo de alvorada.",
        "Um beijo da aurora desperta os espíritos.",
        "A manhã respira sem pressa.",
        "Uma aurora com um toque suave.",
        "A aurora acaricia o silêncio.",
        "Um halo dourado beija o dia.",
        "Um momento tingido de calma.",
        "A luz sussurra na penumbra.",
        "Uma canção sem notas anuncia o dia.",
        "A manhã dança sem som.",
        "A aurora nasce com delicadeza.",
        "Um murmúrio quente desperta.",
        "A luz envolve o horizonte.",
        "Um suspiro dourado se expande.",
        "A aurora oferece seu manto.",
        "Um momento onde tudo é possível.",
        "A manhã espia em calma.",
        "Um verso de luz viaja pelo céu.",
        "A penumbra se transforma em esperança.",
        "Um murmúrio da aurora envolve.",
        "A calma da aurora te abraça.",
        "Um beijo quente desperta os sentidos.",
        "A aurora respira serenidade.",
        "Um momento dourado de paz.",
        "A luz toca a alma.",
        "Um sussurro matinal embala.",
        "A manhã nasce em sussurros.",
        "Um halo de calma se estende.",
        "A aurora acaricia sem pressa.",
        "Um brilho suave preenche o ar.",
        "A luz te convida a sorrir.",
        "Um momento de ouro na manhã.",
        "A aurora se reflete em seus olhos.",
        "Um murmúrio de calma te envolve.",
        "A manhã estreia com luz.",
        "Um suspiro dourado habita o céu.",
        "A aurora sussurra ao coração.",
        "Um momento sem ruído, apenas luz.",
        "A luz te desperta com ternura.",
        "Um halo de esperança na aurora.",
        "A aurora te abraça suavemente.",
        "Um murmúrio dourado percorre o dia.",
        "A manhã começa em calma.",
        "Um momento de amor ao despertar.",
        "A luz veste o horizonte de paz.",
        "Um sussurro da aurora repousa a alma.",
        "A aurora te dá uma nova canção.",
        "Um halo de luz dança com você.",
        "A manhã é um poema vivo.",
        "Um momento eterno de serenidade.",
        "A aurora te convida a renascer."
    ],
    // Mañana
    dayPhrasesPT : [
        "O dia começa com um sussurro de luz.",
        "A manhã se veste de tons suaves.",
        "Um sopro de esperança viaja pelo ar.",
        "A clareza inunda os sentidos.",
        "Um momento de paz inunda tudo.",
        "A energia do dia desperta seus sonhos.",
        "O mundo se espreguiça em calma e cor.",
        "Uma canção interior anuncia a aurora.",
        "A brisa da manhã sussurra promessas para você.",
        "A atmosfera vibra com otimismo.",
        "Desperte a alma com uma melodia suave.",
        "A luz do dia canta em silêncio.",
        "Os raios suaves acariciam a pele.",
        "O dia estreia com delicadeza.",
        "Uma tela em branco te convida a criar.",
        "Cada respiração matinal é uma renovação.",
        "A manhã brilha com serenidade.",
        "Um abraço de luz ilumina a alma.",
        "A aurora deixa um rastro de ternura.",
        "A clareza te envolve em calma.",
        "Um murmúrio de paz inicia o dia.",
        "O frescor da manhã enche os pulmões.",
        "Um sussurro dourado desperta o ânimo.",
        "A esperança floresce com a luz.",
        "A manhã convida a sonhar acordado.",
        "O dia se apresenta com suavidade.",
        "A luz da manhã abraça os sentidos.",
        "O silêncio e a luz conversam.",
        "Um halo de energia inunda o dia.",
        "A manhã dança em calma dourada.",
        "Um momento de gratidão se acende.",
        "A brisa suave acaricia a mente.",
        "Um flash de clareza reaviva.",
        "A manhã parece um abraço.",
        "Um sopro de vida corre por suas veias.",
        "A luz da manhã te dá esperança.",
        "Um poema sem palavras emerge na aurora.",
        "A manhã te convida a respirar fundo.",
        "Um momento de beleza te envolve.",
        "A luz suave te desperta com doçura.",
        "Um murmúrio de inspiração começa.",
        "O dia oferece uma nova oportunidade.",
        "A clareza matinal limpa o espírito.",
        "Uma piscadela de luz marca o começo.",
        "A energia do sol te envolve.",
        "Um ar fresco percorre sua pele.",
        "A manhã desdobra sua magia.",
        "Uma canção silenciosa chama sua atenção.",
        "A luz se infiltra por todos os cantos.",
        "Um suspiro de calma habita o ambiente.",
        "A bondade do dia se mostra primeiro.",
        "Uma aura de otimismo emerge suavemente.",
        "A manhã nos dá um novo capítulo.",
        "Um murmúrio interior alimenta a paixão.",
        "A luz aumenta sua clareza mental.",
        "Um sopro de luz guia sua mente.",
        "A manhã se oferece com generosidade.",
        "Um sussurro de amor-próprio ressoa.",
        "A clareza te dá confiança.",
        "Um momento de gratidão abre o dia.",
        "A luz suave inspira seus passos.",
        "Um eco de serenidade invade o ambiente.",
        "A manhã celebra as pequenas coisas.",
        "Um halo de frescor permeia tudo.",
        "A calma matinal se enrosca em seus sentidos.",
        "Um sussurro de luz dá as boas-vindas.",
        "A manhã destila energia renovada.",
        "Um murmúrio dourado te acompanha.",
        "A luz anuncia a possibilidade.",
        "Um sopro de otimismo clareia o dia.",
        "A manhã parece um presente.",
        "Um momento de beleza sem esforço.",
        "A clareza matinal preenche seu olhar.",
        "Um eco de inspiração percorre você.",
        "A luz começa a dançar ao seu redor.",
        "Um suspiro suave renova seu espírito.",
        "A manhã brilha com promessas.",
        "Um murmúrio interior te impulsiona.",
        "A luz te envolve com ternura.",
        "Um sopro de esperança inunda o dia.",
        "A manhã vibra com energia pura.",
        "Um momento de magia acompanha seu despertar.",
        "A clareza te dá uma nova perspectiva.",
        "Um eco de gratidão viaja pelo ar.",
        "A luz abre o caminho para seus sonhos.",
        "Um sussurro de amor pelo dia.",
        "A manhã se torna um abraço.",
        "Um murmúrio de luz envolve o ambiente.",
        "O frescor da manhã alimenta sua alma.",
        "Um sopro de serenidade precede o dia.",
        "A clareza organiza suas ideias.",
        "Um momento de paz te acompanha.",
        "A manhã murmura doces possibilidades.",
        "Um halo de energia sustenta o invisível.",
        "A luz do dia acaricia sua mente.",
        "Um sussurro de calma envolve o momento.",
        "A manhã se veste de otimismo.",
        "Um murmúrio de ternura acaricia sua boca.",
        "A clareza te dá um segundo fôlego.",
        "Um sopro de gratidão impulsiona sua jornada.",
        "A luz renova sua força interior.",
        "Um momento de conexão com a vida.",
        "A manhã ressoa com boas vibrações.",
        "Um halo de clareza envolve seus pensamentos.",
        "A luz da manhã pinta seus planos.",
        "Um sussurro de possibilidade habita tudo.",
        "A calma do dia se instala em você.",
        "Um murmúrio de luz renasce em seu olhar.",
        "A clareza te conecta com o que é autêntico.",
        "Um sopro de energia proporciona nova serenidade.",
        "A manhã respira com você.",
        "Um momento de gratidão brota em seu peito.",
        "A luz te acompanha em cada respiração.",
        "Um sussurro interior alimenta a ilusão.",
        "A clareza matinal abre a mente.",
        "Um murmúrio de ternura preenche o ambiente.",
        "A manhã oferece um momento de paz.",
        "Um halo de esperança acalma tudo.",
        "A luz suaviza seu entorno imediato.",
        "Um sopro de calma precede sua ação.",
        "A clareza te dá asas para começar.",
        "Um sussurro de beleza te envolve.",
        "A manhã vibra com seu entusiasmo.",
        "Um murmúrio interior acompanha seu caminhar.",
        "A luz te dá um novo fôlego.",
        "Um momento de gratidão ilumina.",
        "A clareza abre caminhos interiores.",
        "Um halo de energia te convida a viver.",
        "A luz da manhã inspira seu dia.",
        "Um sussurro de calma te dá foco.",
        "A manhã se revela como uma companheira.",
        "Um murmúrio interior impulsiona seu despertar.",
        "A clareza começa a fluir dentro de você.",
        "Um sopro de esperança alimenta seu desejo.",
        "A luz sustenta seu momento presente.",
        "Um momento de beleza te alegra.",
        "A manhã te entrega sua melhor versão.",
        "Um sussurro de paz acompanha sua primeira xícara.",
        "A clareza matinal guia seus pensamentos.",
        "Cada manhã traz uma nova página para escrever.",
        "Apenas um pensamento positivo pode mudar o dia inteiro.",
        "Abra seus olhos para a beleza que te rodeia.",
        "Cada amanhecer pinta sua alma com esperança renovada.",
        "Desperte seu espírito; o dia espera seu brilho.",
        "Cada dia é uma nova oportunidade disfarçada de luz.",
        "O silêncio da manhã contém a paz que você procura.",
        "Semeie um sorriso hoje e colha alegria amanhã.",
        "Cada novo amanhecer traz uma promessa oculta.",
        "Que sua luz interior compita com a do sol.",
        "O fim da manhã oferece oportunidades infinitas.",
        "Seja a energia que você quer ver refletida ao seu redor.",
        "Na quietude da manhã, ouça seu coração.",
        "Cada respiração desperta uma centelha de possibilidade.",
        "Brilhe hoje com um propósito corajoso e sereno.",
        "A cada passo matinal, você cria seu caminho para a grandeza.",
        "O aroma dos seus sonhos flutua no ar da manhã.",
        "A aurora continua sorrindo mesmo que você não a veja.",
        "Hoje é a página 101 da sua grande história.",
        "Um suspiro de gratidão pode transformar sua jornada.",
        "Entre luz e sombras, escolha irradiar o melhor de você.",
        "A manhã avança, seu espírito também deveria.",
        "Desperte para o brilho escondido dentro de você.",
        "Os raios do céu iluminam o que te apaixona.",
        "Transforme o ar da manhã em energia para sua alma.",
        "Que sua calma interior supere a agitação do dia.",
        "O presente é sua tela mais importante.",
        "Renasça em cada inspiração matinal.",
        "O dia te oferece oportunidades, aceite-as com fé.",
        "Seu sorriso pode mudar o ritmo do mundo.",
        "Regue seus sonhos com a luz que preenche o dia.",
        "Hoje é um novo capítulo: torne-o inesquecível.",
        "Sua gratidão pinta a manhã com cores vivas.",
        "Comece o dia com determinação e você terminará com orgulho.",
        "A harmonia do dia é construída neste momento.",
        "Acredite que o dia pode te surpreender; geralmente o faz.",
        "Deixe a batida do seu coração marcar o ritmo do dia.",
        "Sua energia pode iluminar uma manhã inteira.",
        "Comece esta parte do dia com a mente calma e aberta.",
        "Em cada raio, você vê a promessa de algo belo.",
        "Deixe sua paz interior guiar sua próxima ação.",
        "Seus sonhos merecem luz: esta manhã é seu refúgio.",
        "Sinta a expansão do seu ser a cada inspiração.",
        "O vento da manhã traz consigo infinitas possibilidades.",
        "Hoje, reconecte-se com o que te faz vibrar.",
        "Seu potencial se revela quando você decide brilhar.",
        "Respire gratidão e deixe tudo fluir.",
        "Você é a centelha que acende uma manhã inteira.",
        "Construa o resto do dia com um ato de bondade.",
        "Sua atitude define se o dia será épico ou comum.",
        "Deixe cada gesto contar neste fim de manhã.",
        "Deixe tudo ir, respire e dê uma nova chance ao dia.",
        "Sua presença brilha mais que o sol da manhã.",
        "Faça de cada momento uma obra de arte pessoal.",
        "Comece esta parte do dia com o olhar focado no belo.",
        "Cada passo que você dá em calma é uma vitória íntima.",
        "Que sua mente encontre serenidade nesta parte do dia.",
        "Deixe a manhã testemunhar sua melhor versão.",
        "Encontre o milagre no cotidiano de cada manhã.",
        "Sua emoção positiva pode reescrever o dia completamente.",
        "Este pedaço da manhã é sua chance de renascer.",
        "Que a clareza te guie em cada decisão matinal.",
        "Respire paz e deixe o dia se ajustar a você.",
        "Hoje, escolha se levantar com gratidão e amor.",
        "O ar te dá frescor e possibilidade.",
        "Permita-se brilhar sem pedir permissão.",
        "Sinta a magia que existe neste momento presente.",
        "O calor do seu sorriso pode acalmar qualquer manhã.",
        "Respire fundo; este momento define o dia que você viverá.",
        "Suas decisões matinais semeiam o resto da sua jornada.",
        "Escolha ver o bem; a manhã te recompensa com beleza.",
        "Que sua luz interior também seja um refúgio para outros.",
        "Esta parte do dia é seu degrau para alcançar seus objetivos.",
        "Respire inspiração e deixe tudo se alinhar.",
        "Caminhe com intenção; até os pequenos passos importam.",
        "Seu coração sabe o caminho, apenas ouça seu murmúrio.",
        "Deixe a luz te lembrar do quão grande você pode ser.",
        "Sinta a companhia silenciosa do fim da manhã.",
        "Este trecho do dia te convida a criar, sonhar e amar.",
        "Faça da calma sua melhor ferramenta para avançar.",
        "Sua determinação é a centelha que acende o dia.",
        "A gratidão transforma um dia comum em um dia memorável.",
        "Seja o reflexo da paz que você deseja para o mundo.",
        "Que seus sonhos tenham asas esta manhã.",
        "Renasça neste trecho entre o passado e o futuro imediato.",
        "A energia do dia amadurece com você, sem pressa.",
        "Encontre beleza na simplicidade deste momento.",
        "Que seu coração se sinta tão leve quanto o ar da manhã.",
        "Respire a certeza de que hoje pode ser extraordinário."
    ],
    // Mediodia
    middayPhrasesPT : [
        "O sol atinge seu ponto mais generoso.",
        "Uma respiração profunda te convida a se recompor.",
        "A luz inunda o dia com clareza.",
        "Cada momento pode ser uma tela em branco.",
        "O dia parece mais amplo e mais brilhante.",
        "A energia do meio-dia viaja pelo ar.",
        "Um momento para apreciar do que você é capaz.",
        "A clareza do dia chove oportunidades.",
        "O silêncio e a luz te abraçam fortemente.",
        "Seu sorriso pode iluminar esta hora quente.",
        "Um sopro de vento acaricia os sentidos.",
        "Este momento é um presente de sol e calma.",
        "A vida pulsa com intensidade neste ponto.",
        "Um murmúrio de inspiração te envolve.",
        "A calma do meio-dia equilibra a alma.",
        "Uma pausa para agradecer pelo que você tem.",
        "O horizonte se mostra em sua luz máxima.",
        "Seu dia descobre o próximo nível.",
        "Um momento de brilho em plena plenitude.",
        "Energia e serenidade se misturam em seu peito.",
        "Uma respiração consciente relaxa e centra.",
        "A luz revela possibilidades ocultas.",
        "Tudo parece mais possível sob este sol.",
        "Um momento para se reconectar consigo mesmo.",
        "A clareza do meio-dia inspira ideias.",
        "Seu espírito dança com luz intensa.",
        "O ar quente sussurra confiança para você.",
        "Um momento de respiro entre os planos.",
        "Luz e silêncio dialogam suavemente.",
        "Faça uma pausa e observe sua respiração.",
        "Este trecho do dia te convida a criar.",
        "A energia pulsa com clareza total.",
        "Um murmúrio de gratidão flui dentro de você.",
        "O calor do dia apoia seus passos.",
        "Um momento pleno de foco e calma.",
        "A luz do sol pinta suas metas.",
        "Silêncio interior em plena clareza.",
        "A intensidade da luz fortalece o espírito.",
        "Uma respiração profunda para fortalecer o dia.",
        "A clareza mental atinge seu auge.",
        "Um momento de conexão com o essencial.",
        "A luz oferece força e beleza concentradas.",
        "Sua atenção desperta neste ponto.",
        "Um sopro de calor para acender suas ideias.",
        "Calma e energia convergem em você.",
        "Um momento para agradecer por seu caminho.",
        "A harmonia do dia é sentida ao máximo.",
        "A luz revela o que realmente importa.",
        "Um momento para se reconectar com seus sonhos.",
        "A clareza do sol equilibra a alma.",
        "Um murmúrio de confiança nasce dentro de você.",
        "A plenitude do meio-dia abraça seu espírito.",
        "Uma respiração para recarregar suas intenções.",
        "A luz descobre novas direções.",
        "Um momento para semear gratidão.",
        "A energia do dia vibra em seu ser.",
        "Um momento para alinhar mente e coração.",
        "O calor do sol acaricia seu espírito.",
        "Um sopro de calma no meio da agitação.",
        "A luz do dia é poesia sem palavras.",
        "Um espaço interior para olhar para si mesmo.",
        "A clareza do meio-dia te sustenta.",
        "Um murmúrio de paz vibra no ar.",
        "A energia do sol desperta a ação.",
        "Um momento para agradecer e seguir em frente.",
        "O calor do dia renova suas forças.",
        "Uma respiração para se conectar com sua essência.",
        "A luz intensa revela o que você carrega por dentro.",
        "Um momento para fortalecer suas intenções.",
        "A clareza mental atinge sua melhor versão.",
        "Um murmúrio de esperança envolve seu peito.",
        "A energia do dia te impulsiona para a frente.",
        "Um momento para reordenar seus pensamentos.",
        "O calor do sol te enche de otimismo.",
        "Uma respiração pausada antes de retomar o rumo.",
        "A luz do meio-dia é força concentrada.",
        "Um momento para honrar seu esforço.",
        "A clareza do dia ilumina seu propósito.",
        "Um murmúrio de luz ativa seu eu interior.",
        "A energia irradiada te impulsiona com certeza.",
        "Um momento para agradecer pela jornada até agora.",
        "O calor do dia fortalece suas asas.",
        "Uma respiração cheia de clareza e confiança.",
        "A luz revela o valor do que você está fazendo.",
        "Um momento para se reconectar com suas metas.",
        "A clareza do meio-dia inspira decisões.",
        "Um murmúrio de serenidade acompanha seus passos.",
        "A energia do dia te envolve em plenitude.",
        "Um momento para alinhar coração e ação.",
        "O calor solar te lembra de sua capacidade.",
        "Uma respiração para cultivar a gratidão interior.",
        "A luz do dia aumenta sua determinação.",
        "Um momento para sentir sua força interior.",
        "A clareza mental brilha neste trecho.",
        "Um murmúrio de paz fortalece seu espírito.",
        "A energia do meio-dia te enche de foco.",
        "Um momento para agradecer e se reconectar.",
        "O calor do sol personifica sua paixão.",
        "Uma respiração para centrar suas intenções.",
        "A luz revela a beleza do cotidiano.",
        "Um momento para honrar seu compromisso.",
        "A clareza do dia te dá novas asas.",
        "Um murmúrio de luz acompanha seus sentidos.",
        "A energia do meio-dia guia seus passos.",
        "Um momento para semear novas intenções.",
        "O calor do céu abriga seu propósito.",
        "O sol abraça sua energia com ternura.",
        "Um momento de paz no meio do dia.",
        "A luz intensa acaricia seus projetos.",
        "Um sopro quente para a alma.",
        "A energia do meio-dia renova seu impulso.",
        "Um momento para agradecer por este dia vibrante.",
        "O calor do sol conforta o espírito.",
        "Um sopro de vitalidade percorre seu ser.",
        "A plenitude do dia recarrega seu espírito.",
        "Um momento de conexão interior sob a luz.",
        "A clareza do meio-dia inspira novas ideias.",
        "Um murmúrio de sol alimenta suas emoções.",
        "A luz desperta sua criatividade adormecida.",
        "Uma respiração suave entre ações intensas.",
        "O calor envolve cada célula do seu corpo.",
        "Um momento para se reconectar com suas intenções.",
        "A energia do meio-dia impulsiona seu propósito.",
        "Um momento para recuperar seu centro.",
        "A luz do sol revela o essencial.",
        "Um suspiro de calma no meio do dia.",
        "A clareza te guia com firmeza e ternura.",
        "Um murmúrio de gratidão ilumina seu entorno.",
        "O calor do dia nutre seu coração.",
        "Uma respiração cheia de clareza e equilíbrio.",
        "A energia do meio-dia potencializa sua alma.",
        "Um momento para contemplar seu progresso.",
        "A luz te inspira a continuar com paixão.",
        "Um sopro de serenidade em meio à atividade.",
        "A plenitude do dia preenche seu espaço interior.",
        "Um momento alegre em meio ao cotidiano.",
        "O calor solar fortalece seu espírito.",
        "Uma respiração consciente para alinhar sua mente.",
        "A clareza do sol avança com você.",
        "Um murmúrio de paz enche seu peito.",
        "A energia do dia vibra dentro de você.",
        "Um momento de gratidão pelo que foi vivido.",
        "A luz te acompanha em cada decisão.",
        "Um sopro de calma no meio da rotina.",
        "A plenitude te envolve com suavidade.",
        "Um momento para refletir e recarregar.",
        "O calor do meio-dia beija seu espírito.",
        "Um sopro de criação sob o sol.",
        "A clareza te impulsiona em direção às suas metas.",
        "Um murmúrio de luz fortalece sua essência.",
        "A energia do dia parece poderosa.",
        "Um momento de harmonia em sua jornada.",
        "A luz te sustenta com delicadeza.",
        "Um sopro de gratidão ilumina seus passos.",
        "A plenitude do meio-dia nutre seu ser.",
        "Um momento de conexão com o autêntico.",
        "O calor solar te inspira a continuar.",
        "Uma respiração para se redescobrir.",
        "A clareza do dia desperta seu foco.",
        "Um murmúrio de paz percorre seus pensamentos.",
        "A energia do meio-dia vibra em seu sangue.",
        "Um momento de pausa com intenção.",
        "A luz do sol pinta seu ser de otimismo.",
        "Um sopro de calma no meio da agitação.",
        "A plenitude do dia é sentida no ar.",
        "Um momento para alinhar corpo, mente e alma.",
        "O calor do meio-dia te presenteia com plenitude.",
        "Uma respiração para refinar suas intenções.",
        "A clareza te fortalece em cada escolha.",
        "Um murmúrio de luz preenche seu espaço interior.",
        "A energia do sol te envolve com vida.",
        "Um momento de reconexão interna.",
        "A luz do meio-dia acaricia seu propósito.",
        "Um sopro de serenidade te acompanha.",
        "A plenitude do dia vibra em você.",
        "Um momento para honrar sua jornada.",
        "O calor solar fortalece sua presença.",
        "Uma respiração vital no meio do dia.",
        "A clareza do sol guia seu caminho.",
        "Um murmúrio de gratidão sustenta sua jornada.",
        "A energia do meio-dia renova seu impulso.",
        "Um momento de calma no turbilhão.",
        "A luz te inspira a brilhar com transparência.",
        "Um sopro de serenidade te renova.",
        "A plenitude do dia se filtra em seus dias.",
        "Um momento para agradecer pelo que foi alcançado.",
        "O calor do sol acompanha seus passos.",
        "Uma respiração interior no meio da agitação.",
        "A clareza do meio-dia reconhece seu valor.",
        "Um murmúrio de paz revitaliza sua essência.",
        "A energia do dia pulsa em seu coração.",
        "Um momento consciente de gratidão.",
        "A luz te abraça com suavidade.",
        "Um sopro de calma para nutrir seu espírito.",
        "A plenitude do meio-dia te inspira.",
        "Um momento para recuperar sua harmonia.",
        "O calor solar fortalece sua confiança.",
        "Uma respiração cheia de pura clareza.",
        "A clareza te impulsiona para novas metas.",
        "Um murmúrio de luz sustenta sua essência.",
        "A energia do sol vibra em seu ser.",
        "Um momento de reconexão plena.",
        "A luz do meio-dia acaricia seu eu interior.",
        "Um sopro de serenidade ilumina seu ser.",
        "A plenitude do dia recarrega sua mente.",
        "Um momento para honrar seu caminho.",
        "O calor do sol te presenteia com presença.",
        "Uma respiração vital fortalece seu espírito.",
        "A clareza do meio-dia guia seus passos.",
        "Um murmúrio de gratidão flui em você.",
        "A energia do dia sustenta seu impulso.",
        "Um momento consciente de bem-estar.",
        "A luz do sol acompanha seu crescimento.",
        "Um sopro de calma eleva sua intenção.",
        "A plenitude do meio-dia nutre seu ser.",
        "Um momento para se reconectar com sua essência.",
        "O calor solar inspira seu caminhar."
    ],
    // Tarde
    afternoonPhrasesPT : [
        "A tarde te envolve com sua luz dourada.",
        "Um suspiro de sol suaviza o dia.",
        "Este trecho do dia convida à reflexão.",
        "A luz se torna quente e envolvente.",
        "Um murmúrio de calma permeia o ambiente.",
        "A tarde acaricia seus pensamentos.",
        "Um momento para se reconectar com o presente.",
        "A serenidade se espalha a cada raio.",
        "Um momento dourado para respirar fundo.",
        "A luz da tarde pinta suas emoções.",
        "Um sopro de paz percorre sua essência.",
        "A atmosfera sussurra tranquilidade.",
        "Este trecho do dia desperta a inspiração.",
        "A tarde traz consigo doces promessas.",
        "Um murmúrio sereno acompanha seu caminhar.",
        "A luz se torna mais suave e reconfortante.",
        "Um momento para agradecer por quem você é.",
        "A tarde convida a uma pausa consciente.",
        "Um abraço quente de luz te rodeia.",
        "A calma do dia encontra seu auge.",
        "Uma respiração para alinhar seu eu interior.",
        "A luz se filtra com uma terna suavidade.",
        "Um silêncio suave desperta sua intuição.",
        "A tarde ressoa com uma canção silenciosa.",
        "Um murmúrio dourado enche o ar.",
        "A luz morna fortalece suas ideias.",
        "Um momento para apreciar as coisas simples.",
        "A atmosfera se torna contemplativa.",
        "Um sopro de clareza ilumina sua mente.",
        "A tarde te abraça sem pressa.",
        "Um momento de gratidão na luz amena.",
        "A luz se torna um refúgio íntimo.",
        "Um murmúrio suave te traz serenidade.",
        "A calma se difunde em cada raio.",
        "Uma respiração dourada conforta o dia.",
        "A tarde desdobra seu manto pacífico.",
        "Um suspiro quente inunda o ambiente.",
        "A luz dourada desperta a criatividade.",
        "Um momento para se reconectar consigo mesmo.",
        "A tarde te presenteia com sua paz interior.",
        "Um murmúrio fraco te envolve.",
        "A luz pousa sobre seus pensamentos.",
        "Uma respiração profunda te renova.",
        "A tarde constrói espaços de calma.",
        "Um momento para semear gratidão.",
        "A luz desenha sombras tranquilas.",
        "Um sopro de inspiração te acaricia.",
        "A atmosfera vibra com harmonia.",
        "Um murmúrio de luz fortalece seu ser.",
        "A tarde equilibra sua energia.",
        "Um momento para fortalecer seus sonhos.",
        "A luz te convida a criar sem ruído.",
        "Uma respiração consciente te apoia.",
        "A atmosfera pulsa com serenidade.",
        "Um sopro de beleza habita este trecho.",
        "A tarde sussurra presença plena para você.",
        "Um murmúrio quente fortalece sua alma.",
        "A luz se agarra à sua serenidade.",
        "Um momento para criar a partir do coração.",
        "A tarde acaricia seus sentidos.",
        "Um sopro de gratidão te acompanha.",
        "A atmosfera se torna um refúgio.",
        "Um sopro de calma anima seu ser.",
        "A luz te envolve com suavidade.",
        "Um murmúrio dourado harmoniza suas ideias.",
        "A tarde consolida seu equilíbrio interno.",
        "Um momento para honrar sua jornada.",
        "A luz suaviza cada pensamento.",
        "Uma respiração vital fortalece seu ser.",
        "A atmosfera vibra com luz calmante.",
        "Um sopro de clareza ilumina sua essência.",
        "A tarde te presenteia com criatividade silenciosa.",
        "Um murmúrio de gratidão ressoa.",
        "A luz enche seu espírito de ternura.",
        "Um momento de introspecção suave.",
        "A atmosfera se torna pura contemplação.",
        "Uma respiração para realinhar sua energia.",
        "A tarde te abraça sem exigências.",
        "Um sopro de esperança corre por suas veias.",
        "A luz dourada embeleza o momento.",
        "Um murmúrio sereno acalma suas preocupações.",
        "A tarde te oferece sua melhor versão.",
        "Um momento para saborear a quietude.",
        "A luz se filtra para dentro de você.",
        "Uma respiração consciente abraça sua mente.",
        "A atmosfera irradia luz reconfortante.",
        "Um sopro de paz percorre seu ser.",
        "A tarde parece um poema visual.",
        "Um murmúrio de calma fortalece seu centro.",
        "A luz te guia em direção ao essencial.",
        "Um momento de conexão autêntica.",
        "A atmosfera te oferece um refúgio interno.",
        "Um sopro de luz renova seu impulso.",
        "A tarde te presenteia com clareza serena.",
        "Um sopro de gratidão abraça seu dia.",
        "A luz pousa suavemente sobre seu ânimo.",
        "Um momento para reafirmar seus propósitos.",
        "A atmosfera te envolve em calma.",
        "Um murmúrio interior desperta sua alma.",
        "A tarde vibra com uma canção silenciosa.",
        "Uma respiração para valorizar o que foi alcançado.",
        "A luz te alimenta com plenitude.",
        "Um sopro de serenidade ancora seu entorno.",
        "A atmosfera calma pulsa junto com você.",
        "Um momento para sentir sua força.",
        "A tarde ressoa com segredos dourados.",
        "Um sopro de luz acaricia o espírito.",
        "O calor do entardecer desperta seus sonhos.",
        "Um momento para ouvir sua respiração.",
        "A tarde te envolve em serenidade sutil.",
        "Um murmúrio suave fortalece seu eu interior.",
        "A luz entra em seu ser sem pressa.",
        "Uma respiração consciente reconecta a alma.",
        "A calma da tarde se espalha pelo ambiente.",
        "Um momento para semear o silêncio interior.",
        "A luz dourada apoia cada passo.",
        "Um momento de gratidão se filtra em você.",
        "A tarde sussurra uma doce confidência.",
        "Um sopro de ternura envolve seus sentidos.",
        "A atmosfera pulsa com a suavidade do entardecer.",
        "Uma respiração lenta centra seus pensamentos.",
        "A tarde abraça o final do dia.",
        "Um murmúrio de calma te acompanha.",
        "A luz intensa libera harmonia interior.",
        "Um momento para se reconectar com o profundo.",
        "A quietude do entardecer acaricia sua mente.",
        "Um sopro de inspiração percorre sua pele.",
        "A tarde parece um abraço morno.",
        "Uma respiração para valorizar o que foi alcançado.",
        "A luz te presenteia com um refúgio de paz.",
        "Um momento para alinhar corpo e mente.",
        "A tarde flui com um ritmo pacífico.",
        "Um murmúrio interior encoraja sua confiança.",
        "A luz dourada te impede de apressar.",
        "Um momento para agradecer por este trecho.",
        "A atmosfera se tinge de calma e doçura.",
        "Um sopro de gratidão em cada expiração.",
        "A tarde respira junto com seu silêncio.",
        "Uma respiração vespertina renova as energias.",
        "A luz repousa suavemente sobre seu ânimo.",
        "Um momento para sentir seu coração bater.",
        "A calma do entardecer fortalece seu espírito.",
        "Um murmúrio sereno te guia.",
        "A tarde te protege em seu manto morno.",
        "Uma respiração para se reconectar com seu centro.",
        "A luz dourada envolve seus pensamentos.",
        "Um momento de introspecção acústica.",
        "A atmosfera vibra suave e constantemente.",
        "Um sopro de calma percorre sua consciência.",
        "A tarde te oferece um refúgio interior.",
        "Um momento para revitalizar seu propósito.",
        "A luz do entardecer sustenta seu equilíbrio.",
        "Um murmúrio de gratidão emerge.",
        "A tarde se apresenta com nobreza.",
        "Uma respiração para continuar com intenção.",
        "A calma dourada conforta seus passos.",
        "Um momento para redefinir seu bem-estar.",
        "A luz suave refina sua sensibilidade.",
        "Um sopro de clareza dentro de você.",
        "A tarde canta sem palavras.",
        "Uma respiração consciente acompanha sua essência.",
        "A atmosfera flui com serenidade.",
        "Um momento para enfatizar seu presente.",
        "A luz dourada harmoniza suas ideias.",
        "Um murmúrio calmo nutre seu ânimo.",
        "A tarde embriaga seus sentidos.",
        "Um sopro de paz te conforta.",
        "A tarde ilumina sua quietude.",
        "Uma respiração profunda alinha seu ser.",
        "A luz do entardecer convida à reflexão.",
        "Um momento para agradecer por esta jornada.",
        "A atmosfera sussurra tranquilidade.",
        "Um momento para abrir o coração.",
        "A luz dourada evoca ternura interior.",
        "Um sopro de calma fortalece seu eu interior.",
        "A tarde te cobre com seu manto pacífico.",
        "Um murmúrio suave encoraja seus pensamentos.",
        "A luz se filtra como um abraço silencioso.",
        "Uma respiração esperada ao chegar neste trecho.",
        "A calma do entardecer se torna uma presença.",
        "Um momento para nutrir sua essência.",
        "A atmosfera pacífica transmite segurança.",
        "Um sopro de inspiração ilumina seu caminho.",
        "A tarde parece uma canção serena.",
        "Uma respiração que ordena suas ideias.",
        "A luz pousa delicadamente em você.",
        "Um momento para aprofundar a conexão interior.",
        "A tarde retoma o pulso do dia.",
        "Um murmúrio íntimo restaura o ânimo.",
        "A luz do entardecer fortalece sua introspecção.",
        "Uma respiração mansa acompanha seu repouso.",
        "A calma envolve seu momento presente.",
        "Um sopro de gratidão te abraça.",
        "A tarde te presenteia com clareza silenciosa.",
        "Um momento para contemplar sua energia.",
        "A atmosfera se carrega de bondade.",
        "Um murmúrio reconfortante enche o ar.",
        "A luz dourada te ancora no momento.",
        "Uma respiração para fechar o capítulo deste dia.",
        "A tarde respira com você em calma.",
        "Um sopro de beleza se revela.",
        "A luz embeleza seu silêncio interior.",
        "Um momento para valorizar seu caminho.",
        "A atmosfera se torna um refúgio interno.",
        "Um momento de paz te envolve.",
        "A tarde ressoa com sua essência.",
        "Um murmúrio suave repousa em seu peito.",
        "A luz do entardecer acompanha sua reflexão.",
        "Uma respiração que acalma a agitação.",
        "A calma te acompanha neste trecho.",
        "Um sopro de inspiração te sustenta.",
        "A tarde mostra seu rosto mais amável.",
        "Um momento para agradecer pelo que aprendeu.",
        "A atmosfera se abre diante de seu olhar.",
        "Um murmúrio de calma abraça seu coração.",
        "A luz suave ilumina seu bem-estar.",
        "Uma respiração para completar sua jornada.",
        "A tarde vibra com esperança silenciosa."
    ],
    // Atardecer
    sunsetPhrasesPT : [
        "O céu se derrama em tons de fogo.",
        "Um suspiro de luz desce no horizonte.",
        "A calma do entardecer pinta tudo de dourado.",
        "Um momento para se encontrar na beleza.",
        "O sol se despede com um abraço caloroso.",
        "Um murmúrio de gratidão tinge a tarde.",
        "As cores do crepúsculo acariciam a alma.",
        "Um sopro de serenidade em cada reflexo.",
        "A tarde canta sua canção em silêncio.",
        "Uma respiração para apreciar o efêmero.",
        "A atmosfera se veste de tons suaves.",
        "Um momento onde o dia se torna arte.",
        "O céu flutua numa paleta dourada.",
        "Um murmúrio de calma atravessa seu peito.",
        "A luz descendente equilibra o espírito.",
        "Um sopro de poesia no crepúsculo.",
        "A tarde se torna um sussurro suave.",
        "Um momento para agradecer por este presente.",
        "A calma do pôr do sol envolve o ambiente.",
        "Um murmúrio caloroso nutre seus pensamentos.",
        "A luz se acalma ao cair do dia.",
        "Um sopro de nostalgia transforma o céu.",
        "A tarde te acompanha em sua plenitude.",
        "Um momento de introspecção dourada.",
        "A atmosfera vibra em tons crepusculares.",
        "Um murmúrio suave te sustenta desde o céu.",
        "A luz dourada delineia seus sonhos.",
        "Um suspiro outonal veste a tarde.",
        "A calma do crepúsculo preenche seus sentidos.",
        "Um refúgio instantâneo de paz e cor.",
        "A tarde onírica te deixa sem fôlego.",
        "Um sopro de luz acalma a mente.",
        "A atmosfera brilha como pinceladas.",
        "Um murmúrio vespertino nutre o eu interior.",
        "A tarde se torna um palco emocional.",
        "Um momento para se reconectar com a paciência.",
        "A luz desliza docemente pelo ar.",
        "Um sopro de calma sela o dia.",
        "A calma do pôr do sol sussurra em seu ouvido.",
        "Um murmúrio dourado abraça seus sonhos.",
        "A tarde floresce em matizes suaves.",
        "Um momento para saborear a leveza.",
        "A atmosfera se expande lentamente.",
        "Um murmúrio íntimo acompanha o céu.",
        "A luz suave te convida a contemplar.",
        "Um sopro de gratidão colore o ambiente.",
        "A tarde respira com elegância refinada.",
        "Um momento para se fundir com a natureza.",
        "A serenidade vespertina aviva seus sentidos.",
        "Um murmúrio dourado embala o dia.",
        "A luz do crepúsculo equilibra o ânimo.",
        "Um momento de beleza inesperada.",
        "A atmosfera se veste de calma dourada.",
        "Um suspiro vespertino acaricia o coração.",
        "A tarde se torna uma canção sem palavras.",
        "Um sopro de luz fortalece sua paz.",
        "A calma do crepúsculo te protege.",
        "Um momento para fechar com gratidão.",
        "A luz que se apaga te envolve suavemente.",
        "Um murmúrio caloroso preenche seus pensamentos.",
        "A tarde se torna um poema visual.",
        "Um sopro de serenidade te abriga.",
        "A atmosfera flui com doçura vespertina.",
        "Um momento de introspecção luminosa.",
        "A luz dourada delineia suas ideias.",
        "Um murmúrio de calma sustenta seu espírito.",
        "A tarde te oferece um refúgio íntimo.",
        "Um sopro de gratidão percorre seu peito.",
        "A serenidade do pôr do sol te abraça.",
        "Um momento para se reconectar com sua essência.",
        "A luz descendente te guia para o descanso.",
        "Um murmúrio de luz afirma seu eu interior.",
        "A tarde irradia um silêncio reconfortante.",
        "Um sopro de paz habita cada respiração.",
        "A atmosfera se transforma em poesia silenciosa.",
        "Um momento para agradecer pelo presente.",
        "A luz vespertina dissolve seu cansaço.",
        "Um murmúrio dourado repara seu equilíbrio.",
        "A tarde te envolve com matizes suaves.",
        "Um sopro de calma dissolve as tensões.",
        "A serenidade vespertina te reconecta.",
        "Um momento para nutrir sua tranquilidade.",
        "A luz que se apaga ilumina sua introspecção.",
        "Um murmúrio vespertino inspira calma.",
        "A tarde oferece seu abraço dourado.",
        "Um sopro de gratidão amadurece sua calma.",
        "A atmosfera se adorna com um leve silêncio.",
        "Um momento para se fundir com o dia.",
        "A luz final delineia suas aspirações.",
        "Um murmúrio suave acompanha seu crepúsculo.",
        "A tarde se torna um espelho interior.",
        "Um sopro de serenidade te conecta ao aqui e agora.",
        "A calma vespertina te envolve sem pressa.",
        "Um momento de plenitude e profundidade.",
        "A luz dourada fortalece seu bem-estar.",
        "Um murmúrio interior sustenta seu ânimo.",
        "A tarde recolhe o melhor do seu dia.",
        "Um sopro de gratidão acompanha o fechamento.",
        "A atmosfera vespertina te convida ao silêncio.",
        "Um momento para alinhar coração e mente.",
        "A luz se despede, embelezando a paisagem.",
        "Um murmúrio dourado reaviva sua essência.",
        "A tarde é selada com um suspiro caloroso.",
        "Um sopro de calma se despede do crepúsculo.",
        "A serenidade do crepúsculo conforta seus passos.",
        "Um momento para liberar as tensões.",
        "A luz vespertina cobre seus pensamentos.",
        "Um murmúrio íntimo emoldura seu sorriso.",
        "A tarde se estende em seu abraço dourado.",
        "Um sopro de gratidão culmina o dia.",
        "A atmosfera se torna uma testemunha serena.",
        "Um momento para agradecer e deixar ir.",
        "A luz descendente oferece uma despedida amável.",
        "Um murmúrio suave encerra a jornada.",
        "A tarde oferece seu beijo final de luz.",
        "Um sopro de calma acaricia o crepúsculo.",
        "A serenidade vespertina nutre seu eu interior."
    ],
    // Noche
    nightPhrasesPT : [
        "A noite começa a sussurrar.",
        "O céu se tinge de azul profundo.",
        "As estrelas despertam lentamente.",
        "A lua espia timidamente.",
        "O ar fresco acaricia a pele.",
        "As luzes da cidade piscam como vaga-lumes.",
        "É hora de se deixar levar pelos sonhos.",
        "O dia se despede com um suspiro.",
        "A quietude da noite convida à reflexão.",
        "O silêncio se torna companhia.",
        "As sombras se alongam com elegância.",
        "A noite se veste de gala.",
        "O céu noturno é uma tela estrelada.",
        "A brisa noturna traz segredos consigo.",
        "As ruas se esvaziam, mas a cidade continua viva.",
        "É o momento perfeito para uma xícara de chá.",
        "A escuridão não é ausência, mas presença.",
        "As estrelas contam histórias antigas.",
        "A lua cheia ilumina o caminho.",
        "A noite é jovem e cheia de promessas.",
        "É hora de deixar a mente voar livre.",
        "A serenidade da noite envolve a alma.",
        "As luzes distantes parecem sussurrar canções.",
        "A quietude noturna é um bálsamo para o espírito.",
        "É hora de soltar e descansar.",
        "A noite se torna um refúgio acolhedor.",
        "As estrelas parecem mais perto do que nunca.",
        "A lua cheia reflete sonhos esquecidos.",
        "A cidade dorme, mas os pensamentos despertam.",
        "A noite é um poema sem palavras.",
        "As sombras dançam ao ritmo do vento.",
        "É o momento perfeito para um abraço silencioso.",
        "A escuridão esconde beleza em cada canto.",
        "As luzes da cidade são estrelas na terra.",
        "A noite convida à calma e à introspecção.",
        "É hora de se deixar levar pela música da alma.",
        "A lua cheia reflete segredos compartilhados.",
        "As estrelas piscam como promessas distantes.",
        "A noite é uma tela em branco para os sonhos.",
        "É hora de fechar os olhos e viajar.",
        "A escuridão não é medo, é mistério.",
        "As luzes da cidade são vaga-lumes modernos.",
        "A noite é um refúgio para pensamentos profundos.",
        "É hora de deixar o coração falar.",
        "A lua cheia ilumina os caminhos perdidos.",
        "As estrelas são os olhos do universo.",
        "A noite é um suspiro do dia.",
        "É hora de ouvir o silêncio.",
        "A escuridão esconde histórias para contar.",
        "As luzes distantes são faróis à distância.",
        "A noite é o palco dos sonhos.",
        "É hora de deixar a mente se libertar.",
        "A lua cheia é um espelho da alma.",
        "As estrelas são as pegadas do tempo.",
        "A noite é um abraço quente e silencioso.",
        "É hora de se deixar levar pela imaginação.",
        "A escuridão esconde beleza em seu interior.",
        "As luzes da cidade são estrelas presas.",
        "A noite convida à reflexão e ao descanso.",
        "É hora de deixar a alma relaxar.",
        "A lua cheia ilumina os segredos do coração.",
        "As estrelas são o riso do universo.",
        "A noite é uma viagem sem mapas.",
        "É hora de soltar e descansar.",
        "A escuridão esconde magia em seu silêncio.",
        "As luzes distantes são sonhos a serem realizados.",
        "A noite é o refúgio dos poetas.",
        "É hora de deixar os pensamentos fluírem.",
        "A lua cheia reflete a beleza da alma.",
        "As estrelas são as palavras do céu.",
        "A noite é uma tela para os sonhos.",
        "É hora de fechar os olhos e voar.",
        "A escuridão esconde histórias a serem descobertas.",
        "As luzes da cidade são estrelas em movimento.",
        "A noite convida à calma e à serenidade.",
        "É hora de deixar o coração se expressar.",
        "A lua cheia ilumina os desejos ocultos.",
        "As estrelas são os suspiros do universo.",
        "A noite é um poema sem fim.",
        "É hora de ouvir o murmúrio do vento.",
        "A escuridão esconde beleza em seu mistério.",
        "As luzes distantes são memórias esquecidas.",
        "A noite é o refúgio dos sonhos perdidos.",
        "É hora de deixar a mente se libertar.",
        "A lua cheia reflete a luz interior.",
        "As estrelas são as pegadas dos deuses.",
        "A noite é um abraço silencioso.",
        "É hora de se deixar levar pela paz.",
        "A escuridão esconde segredos a serem revelados.",
        "As luzes da cidade são estrelas cadentes.",
        "A noite convida à reflexão e à calma.",
        "É hora de deixar a alma relaxar.",
        "A lua cheia ilumina os caminhos solitários.",
        "As estrelas são os olhos do céu.",
        "A noite é um suspiro do dia.",
        "É hora de ouvir o silêncio.",
        "A escuridão esconde histórias para contar.",
        "As luzes distantes são faróis à distância.",
        "A noite é o palco dos sonhos.",
        "É hora de deixar a mente se libertar.",
        "A lua cheia é um espelho da alma.",
        "As estrelas são as pegadas do tempo.",
        "A noite é um abraço quente e silencioso.",
        "É hora de se deixar levar pela imaginação.",
        "A escuridão esconde beleza em seu interior.",
        "As luzes da cidade são estrelas presas.",
        "A noite convida à reflexão e ao descanso.",
        "É hora de deixar a alma relaxar.",
        "A lua cheia ilumina os segredos do coração.",
        "As estrelas são o riso do universo.",
        "A noite é uma viagem sem mapas.",
        "É hora de soltar e descansar.",
        "A escuridão esconde magia em seu silêncio.",
        "As luzes distantes são sonhos a serem realizados.",
        "A noite é o refúgio dos poetas.",
        "É hora de deixar os pensamentos fluírem.",
        "A lua cheia reflete a beleza da alma.",
        "As estrelas são as palavras do céu.",
        "A noite é uma tela para os sonhos.",
        "É hora de fechar os olhos e voar.",
        "A escuridão esconde histórias a serem descobertas.",
        "As luzes da cidade são estrelas em movimento.",
        "A noite convida à calma e à serenidade.",
        "É hora de deixar o coração se expressar.",
        "A lua cheia ilumina desejos ocultos.",
        "As estrelas são os suspiros do universo.",
        "A noite é um poema sem fim.",
        "É hora de ouvir o murmúrio do vento.",
        "A escuridão esconde beleza em seu mistério.",
        "As luzes distantes são memórias esquecidas.",
        "A noite é o refúgio dos sonhos perdidos.",
        "É hora de deixar a mente se libertar.",
        "A lua cheia reflete a luz interior.",
        "As estrelas são as pegadas dos deuses.",
        "A noite é um abraço silencioso.",
        "É hora de se deixar levar pela paz.",
        "A escuridão esconde segredos a serem revelados.",
        "As luzes da cidade são estrelas cadentes.",
        "A noite convida à reflexão e à calma.",
        "É hora de deixar a alma relaxar.",
        "A lua cheia ilumina os caminhos solitários.",
        "As estrelas são os olhos do céu.",
        "A noite é um suspiro do dia.",
        "É hora de ouvir o silêncio.",
        "A escuridão esconde histórias para contar.",
        "As luzes distantes são faróis à distância.",
        "A noite é o palco dos sonhos.",
        "É hora de deixar a mente se libertar.",
        "A lua cheia é um espelho da alma.",
        "As estrelas são as pegadas do tempo.",
        "A noite é um abraço quente e silencioso.",
        "É hora de se deixar levar pela imaginação.",
        "A escuridão esconde beleza em seu interior.",
        "As luzes da cidade são estrelas presas.",
        "A noite convida à reflexão e ao descanso.",
        "É hora de deixar a alma relaxar.",
        "A lua cheia ilumina os segredos do coração.",
        "As estrelas são o riso do universo.",
        "A noite é uma viagem sem mapas.",
        "É hora de soltar e descansar.",
        "A escuridão esconde magia em seu silêncio.",
        "As luzes distantes são sonhos a serem realizados.",
        "A noite é o refúgio dos poetas.",
        "É hora de deixar os pensamentos fluírem.",
        "A lua cheia reflete a beleza da alma.",
        "As estrelas são as palavras do céu.",
        "A noite é uma tela para os sonhos.",
        "É hora de fechar os olhos e voar.",
        "A escuridão esconde histórias a serem descobertas.",
        "As luzes da cidade são estrelas em movimento.",
        "A noite convida à calma e à serenidade.",
        "É hora de deixar o coração se expressar.",
        "A lua cheia ilumina desejos ocultos.",
        "As estrelas são os suspiros do universo.",
        "A noite é um poema sem fim.",
        "É hora de ouvir o murmúrio do vento.",
        "A escuridão esconde beleza em seu mistério.",
        "As luzes distantes são memórias esquecidas.",
        "A noite é o refúgio dos sonhos perdidos.",
        "A noite sussurra segredos ao ouvido do vento.",
        "O céu noturno é uma tela de estrelas perdidas.",
        "A lua observa silenciosamente os sonhos que nascem.",
        "A escuridão acolhe os pensamentos errantes.",
        "As estrelas piscam como suspiros esquecidos.",
        "A madrugada é um sussurro entre as sombras.",
        "O vento noturno canta canções distantes.",
        "A lua cheia ilumina os caminhos solitários.",
        "O silêncio da noite é um refúgio para a alma.",
        "As estrelas são os olhos do universo observando.",
        "A noite é um poema sem palavras.",
        "O murmúrio do vento é a voz da escuridão.",
        "A lua reflete os sonhos que ainda não foram contados.",
        "As sombras se alongam como memórias perdidas.",
        "O céu noturno é um mar de estrelas navegantes.",
        "A noite é uma tela onde os sonhos são pintados.",
        "O silêncio da madrugada é um canto profundo.",
        "As estrelas são as joias do manto noturno.",
        "A lua cheia é um farol na escuridão.",
        "A noite é um abraço quente e silencioso.",
        "As sombras dançam ao ritmo do vento noturno.",
        "O céu estrelado é um mapa de sonhos perdidos.",
        "A lua observa em silêncio os segredos do mundo.",
        "A escuridão esconde histórias a serem descobertas.",
        "As estrelas são as pegadas dos deuses no céu.",
        "A noite é um refúgio para os pensamentos solitários.",
        "O vento noturno acaricia as memórias esquecidas.",
        "A lua cheia ilumina os caminhos da alma errante.",
        "As sombras se alongam como suspiros na penumbra.",
        "O céu noturno é um espelho da alma humana.",
        "A noite é um suspiro do universo.",
        "As estrelas são as promessas do céu.",
        "A lua cheia é um espelho da noite.",
        "O silêncio da madrugada é um canto profundo.",
        "As sombras se alongam como memórias perdidas.",
        "O céu estrelado é um mapa de sonhos perdidos.",
        "A lua observa em silêncio os segredos do mundo.",
        "A escuridão esconde histórias a serem descobertas.",
        "As estrelas são as pegadas dos deuses no céu.",
        "A noite é um refúgio para os pensamentos solitários.",
        "O vento noturno acaricia as memórias esquecidas.",
        "A lua cheia ilumina os caminhos da alma errante.",
        "As sombras se alongam como suspiros na penumbra.",
        "O céu noturno é um espelho da alma humana.",
        "A noite é um suspiro do universo.",
        "As estrelas são as promessas do céu.",
        "A lua cheia é um espelho da noite.",
        "O silêncio da madrugada é um canto profundo.",
        "As sombras se alongam como memórias perdidas.",
        "O céu estrelado é um mapa de sonhos perdidos.",
        "A lua observa em silêncio os segredos do mundo.",
        "A escuridão esconde histórias a serem descobertas.",
        "As estrelas são as pegadas dos deuses no céu.",
        "A noite é um refúgio para os pensamentos solitários.",
        "O vento noturno acaricia as memórias esquecidas.",
        "A lua cheia ilumina os caminhos da alma errante.",
        "As sombras se alongam como suspiros na penumbra.",
        "O céu noturno é um espelho da alma humana.",
        "A noite é um suspiro do universo.",
        "As estrelas são as promessas do céu.",
        "A lua cheia é um espelho da noite.",
        "O silêncio da madrugada é um canto profundo.",
        "As sombras se alongam como memórias perdidas.",
        "O céu estrelado é um mapa de sonhos perdidos.",
        "A lua observa em silêncio os segredos do mundo.",
        "A escuridão esconde histórias a serem descobertas.",
        "As estrelas são as pegadas dos deuses no céu.",
        "A noite é um refúgio para os pensamentos solitários.",
        "O vento noturno acaricia as memórias esquecidas.",
        "A lua cheia ilumina os caminhos da alma errante.",
        "As sombras se alongam como suspiros na penumbra.",
        "O céu noturno é um espelho da alma humana.",
        "A noite é um suspiro do universo.",
        "As estrelas são as promessas do céu.",
        "A lua cheia é um espelho da noite.",
        "O silêncio da madrugada é um canto profundo.",
        "As sombras se alongam como memórias perdidas.",
        "O céu estrelado é um mapa de sonhos perdidos.",
        "A lua observa em silêncio os segredos do mundo.",
        "A escuridão esconde histórias a serem descobertas.",
        "As estrelas são as pegadas dos deuses no céu.",
        "A noite é um refúgio para os pensamentos solitários.",
        "O vento noturno acaricia as memórias esquecidas.",
        "A lua cheia ilumina os caminhos da alma errante.",
        "As sombras se alongam como suspiros na penumbra.",
        "O céu noturno é um espelho da alma humana.",
        "A noite é um suspiro do universo.",
        "As estrelas são as promessas do céu.",
        "A lua cheia é um espelho da noite.",
        "O silêncio da madrugada é um canto profundo.",
        "As sombras se alongam como memórias perdidas.",
        "O céu estrelado é um mapa de sonhos perdidos.",
        "A lua observa em silêncio os segredos do mundo.",
        "A escuridão esconde histórias a serem descobertas.",
        "As estrelas são as pegadas dos deuses no céu.",
        "A noite é um refúgio para os pensamentos solitários.",
        "O vento noturno acaricia as memórias esquecidas.",
        "A lua cheia ilumina os caminhos da alma errante.",
        "As sombras se alongam como suspiros na penumbra.",
        "O céu noturno é um espelho da alma humana.",
        "A noite é um suspiro do universo.",
        "As estrelas são as promessas do céu.",
        "A lua cheia é um espelho da noite.",
        "O silêncio da madrugada é um canto profundo.",
        "As sombras se alongam como memórias perdidas.",
        "O céu estrelado é um mapa de sonhos perdidos.",
        "A lua observa em silêncio os segredos do mundo.",
        "A escuridão esconde histórias a serem descobertas.",
        "As estrelas são as pegadas dos deuses no céu.",
        "A noite é um refúgio para os pensamentos solitários.",
        "O vento noturno acaricia as memórias esquecidas.",
        "A lua cheia ilumina os caminhos da alma errante.",
        "As sombras se alongam como suspiros na penumbra.",
        "O céu noturno é um espelho da alma humana.",
        "A noite é um suspiro do universo.",
        "As estrelas são as promessas do céu.",
        "A lua cheia é um espelho da noite.",
        "O silêncio da madrugada é um canto profundo.",
        "As sombras se alongam como memórias perdidas.",
        "O céu estrelado é um mapa de sonhos perdidos.",
        "A lua observa em silêncio os segredos do mundo.",
        "A escuridão esconde histórias a serem descobertas.",
        "As estrelas são as pegadas dos deuses no céu.",
        "A noite é um refúgio para os pensamentos solitários.",
        "O vento noturno acaricia as memórias esquecidas.",
        "A lua cheia ilumina os caminhos da alma errante.",
        "As sombras se alongam como suspiros na penumbra.",
        "O céu noturno é um espelho da alma humana.",
        "A noite é um suspiro do universo.",
        "As estrelas são as promessas do céu.",
        "A lua cheia é um espelho da noite.",
        "O silêncio da madrugada é um canto profundo.",
        "As sombras se alongam como memórias perdidas.",
        "O céu estrelado é um mapa de sonhos perdidos.",
        "A lua observa em silêncio os segredos do mundo.",
        "A escuridão esconde histórias a serem descobertas.",
        "As estrelas são as pegadas dos deuses no céu.",
        "A noite é um refúgio para os pensamentos solitários.",
        "O vento noturno acaricia as memórias esquecidas.",
        "A lua cheia ilumina os caminhos da alma errante.",
        "As sombras se alongam como suspiros na penumbra.",
        "O céu noturno é um espelho da alma humana.",
        "A noite é um suspiro do universo.",
        "As estrelas são as promessas do céu.",
        "A lua cheia é um espelho da noite.",
        "O silêncio da madrugada é um canto profundo.",
        "As sombras se alongam como memórias perdidas.",
        "O céu estrelado é um mapa de sonhos perdidos.",
        "A lua observa em silêncio os segredos do mundo.",
        "A escuridão esconde histórias a serem descobertas.",
        "As estrelas são as pegadas dos deuses no céu.",
        "A noite é um refúgio para os pensamentos solitários.",
        "O vento noturno acaricia as memórias esquecidas.",
        "A lua cheia ilumina os caminhos da alma errante.",
        "As sombras se alongam como suspiros na penumbra.",
        "O céu noturno é um espelho da alma humana."
    ]
};

export default collectionPhrasesPT;